package com.swithun.cmpmermaid.core.zenuml.upstream.zenuml

/**
 * @zenuml/core 3.49.2:
 * src/emoji/builtinEmojis.ts and src/emoji/resolveEmoji.ts.
 */
internal fun resolveZenUmlEmoji(shortcode: String): String =
    ZEN_UML_EMOJIS[shortcode] ?: shortcode

internal fun resolveZenUmlEmojiInText(text: String): String =
    EMOJI_REFERENCE.replace(text) { match ->
        val name = match.groupValues[1]
        ZEN_UML_EMOJIS[name] ?: match.value
    }

internal fun isZenUmlEmoji(shortcode: String): Boolean = shortcode in ZEN_UML_EMOJIS

private val EMOJI_REFERENCE = Regex("""\[([^]]+)]""")

private val ZEN_UML_EMOJIS = mapOf(
    "check" to "✅",
    "x" to "❌",
    "warning" to "⚠️",
    "exclamation" to "❗",
    "question" to "❓",
    "bulb" to "💡",
    "eyes" to "👀",
    "rocket" to "🚀",
    "fire" to "🔥",
    "zap" to "⚡",
    "boom" to "💥",
    "sparkles" to "✨",
    "tada" to "🎉",
    "confetti_ball" to "🎊",
    "lock" to "🔒",
    "unlock" to "🔓",
    "key" to "🔑",
    "gear" to "⚙️",
    "hammer" to "🔨",
    "wrench" to "🔧",
    "package" to "📦",
    "email" to "📧",
    "link" to "🔗",
    "clipboard" to "📋",
    "bookmark" to "🔖",
    "speech_balloon" to "💬",
    "thought_balloon" to "💭",
    "bell" to "🔔",
    "megaphone" to "📣",
    "cloud" to "☁️",
    "sun" to "☀️",
    "star" to "⭐",
    "globe" to "🌐",
    "arrow_right" to "➡️",
    "arrow_left" to "⬅️",
    "arrow_up" to "⬆️",
    "arrow_down" to "⬇️",
    "wave" to "👋",
    "thumbsup" to "👍",
    "thumbsdown" to "👎",
    "computer" to "💻",
    "iphone" to "📱",
    "robot" to "🤖",
    "bug" to "🐛",
    "database" to "🗄️",
    "server" to "🖥️",
    "api" to "🔌",
    "gateway" to "🚪",
    "queue" to "📬",
    "cache" to "⚡",
    "service" to "⚙️",
    "processor" to "🔄",
    "store" to "🏪",
    "worker" to "👷",
    "container" to "📦",
    "network" to "🌐",
    "chart" to "📊",
    "chart_with_upwards_trend" to "📈",
    "chart_with_downwards_trend" to "📉",
    "inbox_tray" to "📥",
    "outbox_tray" to "📤",
    "file_folder" to "📁",
    "hourglass" to "⏳",
    "clock" to "🕐",
    "stopwatch" to "⏱️",
    "heavy_check_mark" to "✔️",
    "heavy_multiplication_x" to "✖️",
    "red" to "🔴",
    "red_circle" to "🔴",
    "green_circle" to "🟢",
    "blue_circle" to "🔵",
    "white_circle" to "⚪",
    "black_circle" to "⚫",
    "heart" to "❤️",
    "shield" to "🛡️",
    "coffee" to "☕",
    "pizza" to "🍕",
    "car" to "🚗",
    "bus" to "🚌",
    "airplane" to "✈️",
    "ship" to "🚢",
    "floppy_disk" to "💾",
    "cd" to "💿",
    "satellite" to "🛰️",
    "factory" to "🏭",
    "hospital" to "🏥",
    "bank" to "🏦",
    "construction" to "🚧",
    "recycle" to "♻️",
    "receipt" to "🧾",
    "cart" to "🛒",
    "cylinder" to "🪨",
    "dollar" to "💵",
)
