package com.swithun.cmpmermaid.core.zenuml.upstream.zenuml

import com.swithun.cmpmermaid.core.GMResult
import com.swithun.cmpmermaid.core.MermaidError
import com.swithun.cmpmermaid.core.MermaidRenderOptions

/**
 * Mermaid.js 12.0.0:
 * packages/mermaid/src/docs/syntax/zenuml.md and the external @zenuml/core 3.49.2
 * src/g4/sequenceLexer.g4 + src/g4/sequenceParser.g4.
 *
 * The upstream parser is generated by ANTLR. This scanner keeps the same statement boundaries,
 * hidden comment behavior, quoted names, nested blocks, and permissive expression text without
 * introducing an ANTLR runtime into commonMain.
 */
internal class ZenUmlParser(
    private val options: MermaidRenderOptions,
    private val lineOffset: Int = 0,
) {
    fun parse(source: String): GMResult<ZenUmlDocument, MermaidError> {
        val tokens = when (val result = ZenLexer(source, lineOffset).scan()) {
            is GMResult.Ok -> result.value
            is GMResult.Err -> return result
        }
        return Parser(source, tokens, options, lineOffset).parse()
    }

    private class Parser(
        private val source: String,
        private val tokens: List<Token>,
        private val options: MermaidRenderOptions,
        private val lineOffset: Int,
    ) {
        private val participants = linkedMapOf<String, MutableParticipant>()
        private var index = 0
        private var statementId = 0
        private var explicitStarter: String? = null
        private var hasMessageWithoutProvidedFrom = false

        fun parse(): GMResult<ZenUmlDocument, MermaidError> {
            skipTrivia()
            val header = current()
            if (header.kind != TokenKind.Word || header.value.lowercase() != "zenuml") {
                return error(header, "Expected ZenUML diagram header 'zenuml'")
            }
            index++
            while (!at(TokenKind.Newline) && !at(TokenKind.Eof)) {
                index++
            }
            consume(TokenKind.Newline)

            var title: String? = null
            skipTrivia()
            if (
                atWord("title") &&
                tokens.getOrNull(index + 1)?.kind !in setOf(
                    TokenKind.Dot,
                    TokenKind.Equal,
                    TokenKind.LParen,
                )
            ) {
                val titleToken = current()
                index++
                val end = findLineEnd(index)
                title = formatText(rawRange(index, end)).takeIf(String::isNotBlank)
                index = end
                consume(TokenKind.Newline)
                if (title == null && titleToken.value.isBlank()) {
                    title = ""
                }
            }

            when (val head = parseHead()) {
                is GMResult.Ok -> Unit
                is GMResult.Err -> return head
            }

            val statements = when (
                val result = parseBlock(
                    origin = explicitStarter ?: ZEN_UML_STARTER,
                    returnTarget = explicitStarter ?: ZEN_UML_STARTER,
                    stopAtBrace = false,
                )
            ) {
                is GMResult.Ok -> result.value
                is GMResult.Err -> return result
            }

            val messageCount = countMessages(statements)
            if (messageCount > options.maxEdges) {
                return GMResult.Err(
                    MermaidError.ResourceLimit(
                        resource = "ZenUML messages",
                        actual = messageCount,
                        maximum = options.maxEdges,
                    ),
                )
            }

            if ((messageCount == 0 && participants.isEmpty()) || hasMessageWithoutProvidedFrom) {
                prependDefaultStarter()
            }

            return GMResult.Ok(
                ZenUmlDocument(
                    title = title,
                    participants = participants.values.map(MutableParticipant::toModel),
                    statements = statements,
                    accessibilityTitle = null,
                    accessibilityDescription = null,
                ),
            )
        }

        private fun parseHead(): GMResult<Unit, MermaidError> {
            while (true) {
                val triviaStart = index
                skipTrivia()
                when {
                    atWord("group") -> {
                        when (val result = parseGroup()) {
                            is GMResult.Ok -> Unit
                            is GMResult.Err -> return result
                        }
                    }
                    atAnnotation("@starter") -> {
                        when (val result = parseStarter()) {
                            is GMResult.Ok -> Unit
                            is GMResult.Err -> return result
                        }
                    }
                    isParticipantStart() && !isStatementStart() -> {
                        when (val result = parseParticipant(groupId = null)) {
                            is GMResult.Ok -> Unit
                            is GMResult.Err -> return result
                        }
                    }
                    else -> {
                        index = triviaStart
                        return GMResult.Ok(Unit)
                    }
                }
            }
        }

        private fun parseGroup(): GMResult<Unit, MermaidError> {
            val groupToken = current()
            index++
            skipInlineTrivia()
            val groupName = if (!at(TokenKind.LBrace) && isName(current())) {
                parseName()
            } else {
                null
            }
            skipInlineTrivia()
            if (!consume(TokenKind.LBrace)) {
                return GMResult.Ok(Unit)
            }
            while (true) {
                skipTrivia()
                if (consume(TokenKind.RBrace)) {
                    return GMResult.Ok(Unit)
                }
                if (at(TokenKind.Eof)) {
                    return error(groupToken, "Unclosed ZenUML participant group")
                }
                when (val result = parseParticipant(groupName)) {
                    is GMResult.Ok -> Unit
                    is GMResult.Err -> return result
                }
            }
        }

        private fun parseStarter(): GMResult<Unit, MermaidError> {
            val starterToken = current()
            index++
            skipInlineTrivia()
            val name = if (consume(TokenKind.LParen)) {
                skipInlineTrivia()
                val parsed = parseName()
                    ?: return error(current(), "Expected participant name in @Starter(...)")
                skipInlineTrivia()
                if (!consume(TokenKind.RParen)) {
                    return error(current(), "Expected ')' after @Starter participant")
                }
                parsed
            } else {
                null
            } ?: return error(starterToken, "@Starter requires a participant name")

            explicitStarter = name
            addParticipant(name = name, isStarter = true)
            return GMResult.Ok(Unit)
        }

        private fun parseParticipant(groupId: String?): GMResult<Unit, MermaidError> {
            val start = current()
            var type: String? = null
            var stereotype: String? = null
            var emoji: String? = null

            if (at(TokenKind.Annotation) && !atAnnotation("@starter")) {
                type = current().value.removePrefix("@").takeIf(String::isNotBlank)
                index++
                skipInlineTrivia()
            }
            if (consume(TokenKind.StereotypeOpen)) {
                val stereotypeStart = index
                while (!at(TokenKind.StereotypeClose) && !at(TokenKind.Newline) && !at(TokenKind.Eof)) {
                    index++
                }
                stereotype = formatText(rawRange(stereotypeStart, index)).takeIf(String::isNotBlank)
                consume(TokenKind.StereotypeClose)
                skipInlineTrivia()
            }
            if (consume(TokenKind.LBracket)) {
                val emojiStart = index
                while (!at(TokenKind.RBracket) && !at(TokenKind.Newline) && !at(TokenKind.Eof)) {
                    index++
                }
                emoji = formatText(rawRange(emojiStart, index)).takeIf(String::isNotBlank)
                consume(TokenKind.RBracket)
                skipInlineTrivia()
            }

            val name = parseName()
                ?: return error(start, "Expected ZenUML participant name")
            skipInlineTrivia()
            if (at(TokenKind.Number)) {
                index++
                skipInlineTrivia()
            }
            var label: String? = null
            if (atWord("as")) {
                index++
                skipInlineTrivia()
                label = parseName()
                skipInlineTrivia()
            }
            val color = if (at(TokenKind.Color)) current().value.also { index++ } else null
            addParticipant(
                name = name,
                label = label,
                type = type,
                stereotype = stereotype,
                color = color,
                emoji = emoji,
                groupId = groupId,
                explicit = true,
            )
            return GMResult.Ok(Unit)
        }

        private fun parseBlock(
            origin: String,
            returnTarget: String,
            stopAtBrace: Boolean,
        ): GMResult<List<ZenUmlStatement>, MermaidError> {
            val statements = mutableListOf<ZenUmlStatement>()
            val pendingComments = mutableListOf<String>()
            while (true) {
                while (at(TokenKind.Newline) || at(TokenKind.Comment)) {
                    if (at(TokenKind.Comment)) {
                        pendingComments += current().value
                    }
                    index++
                }
                if (at(TokenKind.Eof)) {
                    return if (stopAtBrace) {
                        error(current(), "Unclosed ZenUML block")
                    } else {
                        GMResult.Ok(statements)
                    }
                }
                if (at(TokenKind.RBrace)) {
                    return if (stopAtBrace) {
                        index++
                        GMResult.Ok(statements)
                    } else {
                        error(current(), "Unexpected '}' in ZenUML diagram")
                    }
                }

                val comment = pendingComments.joinToString("\n").takeIf(String::isNotBlank)
                pendingComments.clear()
                val statement = when (
                    val result = parseStatement(origin, returnTarget, comment)
                ) {
                    is GMResult.Ok -> result.value
                    is GMResult.Err -> return result
                }
                statements += statement
                consume(TokenKind.Semicolon)
            }
        }

        private fun parseStatement(
            origin: String,
            returnTarget: String,
            comment: String?,
        ): GMResult<ZenUmlStatement, MermaidError> {
            val token = current()
            return when {
                token.kind == TokenKind.Divider -> {
                    index++
                    GMResult.Ok(
                        ZenUmlDivider(
                            id = nextStatementId(),
                            line = token.line,
                            comment = comment,
                            label = token.value,
                        ),
                    )
                }
                atWord("if") -> parseAlt(origin, returnTarget, comment)
                atWord("try") -> parseTryCatchFinally(origin, returnTarget, comment)
                atWordIn(LOOP_WORDS) -> parseSingleBlockFragment(
                    kind = ZenUmlFragmentKind.Loop,
                    origin = origin,
                    returnTarget = returnTarget,
                    comment = comment,
                )
                atWord("par") -> parseSingleBlockFragment(
                    ZenUmlFragmentKind.Par,
                    origin,
                    returnTarget,
                    comment,
                )
                atWord("opt") -> parseSingleBlockFragment(
                    ZenUmlFragmentKind.Opt,
                    origin,
                    returnTarget,
                    comment,
                )
                atWord("critical") -> parseSingleBlockFragment(
                    ZenUmlFragmentKind.Critical,
                    origin,
                    returnTarget,
                    comment,
                )
                atWord("section") || atWord("frame") || at(TokenKind.LBrace) ->
                    parseSingleBlockFragment(
                        ZenUmlFragmentKind.Section,
                        origin,
                        returnTarget,
                        comment,
                    )
                atWord("ref") -> parseRef(comment)
                atWord("return") -> parseKeywordReturn(origin, returnTarget, comment)
                atAnnotation("@return") || atAnnotation("@reply") ->
                    parseAnnotatedReturn(origin, returnTarget, comment)
                else -> parseMessage(origin, returnTarget, comment)
            }
        }

        private fun parseAlt(
            origin: String,
            returnTarget: String,
            comment: String?,
        ): GMResult<ZenUmlStatement, MermaidError> {
            val start = current()
            index++
            val condition = parseOptionalParenthesizedText()
            val first = when (val result = parseRequiredBody(origin, returnTarget, start)) {
                is GMResult.Ok -> result.value
                is GMResult.Err -> return result
            }
            val sections = mutableListOf(ZenUmlFragmentSection("Alt", first))

            while (true) {
                val saved = index
                skipTrivia()
                if (!atWord("else")) {
                    index = saved
                    break
                }
                index++
                skipTrivia()
                if (atWord("if")) {
                    index++
                    val elseIfCondition = parseOptionalParenthesizedText()
                    val body = when (val result = parseRequiredBody(origin, returnTarget, start)) {
                        is GMResult.Ok -> result.value
                        is GMResult.Err -> return result
                    }
                    sections += ZenUmlFragmentSection("[ $elseIfCondition ]", body)
                } else {
                    val body = when (val result = parseRequiredBody(origin, returnTarget, start)) {
                        is GMResult.Ok -> result.value
                        is GMResult.Err -> return result
                    }
                    sections += ZenUmlFragmentSection("[else]", body)
                    break
                }
            }
            return GMResult.Ok(
                ZenUmlFragment(
                    id = nextStatementId(),
                    line = start.line,
                    comment = comment,
                    kind = ZenUmlFragmentKind.Alt,
                    label = condition,
                    sections = sections,
                ),
            )
        }

        private fun parseTryCatchFinally(
            origin: String,
            returnTarget: String,
            comment: String?,
        ): GMResult<ZenUmlStatement, MermaidError> {
            val start = current()
            index++
            val tryBody = when (val result = parseRequiredBody(origin, returnTarget, start)) {
                is GMResult.Ok -> result.value
                is GMResult.Err -> return result
            }
            val sections = mutableListOf(ZenUmlFragmentSection("Try", tryBody))
            while (true) {
                val saved = index
                skipTrivia()
                when {
                    atWord("catch") -> {
                        index++
                        val detail = parseOptionalParenthesizedText()
                        val body = when (val result = parseRequiredBody(origin, returnTarget, start)) {
                            is GMResult.Ok -> result.value
                            is GMResult.Err -> return result
                        }
                        sections += ZenUmlFragmentSection(
                            label = "catch${detail.takeIf(String::isNotBlank)?.let { " $it" }.orEmpty()}",
                            statements = body,
                        )
                    }
                    atWord("finally") -> {
                        index++
                        val body = when (val result = parseRequiredBody(origin, returnTarget, start)) {
                            is GMResult.Ok -> result.value
                            is GMResult.Err -> return result
                        }
                        sections += ZenUmlFragmentSection("finally", body)
                        break
                    }
                    else -> {
                        index = saved
                        break
                    }
                }
            }
            return GMResult.Ok(
                ZenUmlFragment(
                    id = nextStatementId(),
                    line = start.line,
                    comment = comment,
                    kind = ZenUmlFragmentKind.TryCatchFinally,
                    label = "",
                    sections = sections,
                ),
            )
        }

        private fun parseSingleBlockFragment(
            kind: ZenUmlFragmentKind,
            origin: String,
            returnTarget: String,
            comment: String?,
        ): GMResult<ZenUmlStatement, MermaidError> {
            val start = current()
            if (!at(TokenKind.LBrace)) {
                index++
            }
            val condition = parseOptionalParenthesizedText()
            val body = when (val result = parseRequiredBody(origin, returnTarget, start)) {
                is GMResult.Ok -> result.value
                is GMResult.Err -> return result
            }
            // @zenuml/core 3.49.2: src/svg/walkStatements.ts -> extractFragmentInfo.
            // The section grammar accepts parExpr, but its rendered context has no condition.
            val visibleCondition = condition.takeUnless { kind == ZenUmlFragmentKind.Section }.orEmpty()
            return GMResult.Ok(
                ZenUmlFragment(
                    id = nextStatementId(),
                    line = start.line,
                    comment = comment,
                    kind = kind,
                    label = visibleCondition,
                    sections = listOf(ZenUmlFragmentSection(visibleCondition, body)),
                ),
            )
        }

        private fun parseRef(comment: String?): GMResult<ZenUmlStatement, MermaidError> {
            val startIndex = index
            val start = current()
            index++
            skipTrivia()
            if (!consume(TokenKind.LParen)) {
                return error(current(), "Expected '(' after ref")
            }
            val names = mutableListOf<String>()
            while (!at(TokenKind.RParen) && !at(TokenKind.Eof)) {
                skipInlineTrivia()
                parseName()?.let { name ->
                    names += name
                    addParticipant(name)
                } ?: index++
                skipInlineTrivia()
                consume(TokenKind.Comma)
            }
            if (!consume(TokenKind.RParen)) {
                return error(current(), "Expected ')' after ref participants")
            }
            return GMResult.Ok(
                ZenUmlFragment(
                    id = nextStatementId(),
                    line = start.line,
                    comment = comment,
                    kind = ZenUmlFragmentKind.Ref,
                    // @zenuml/core 3.49.2:
                    // src/svg/walkStatements.ts -> extractFragmentInfo(ref.getFormattedText()).
                    label = formatText(rawRange(startIndex, index)),
                    sections = emptyList(),
                ),
            )
        }

        private fun parseKeywordReturn(
            origin: String,
            returnTarget: String,
            comment: String?,
        ): GMResult<ZenUmlStatement, MermaidError> {
            val start = current()
            index++
            val end = findStatementEnd(index)
            val label = formatText(rawRange(index, end))
            index = end
            addParticipant(origin)
            addParticipant(returnTarget)
            return GMResult.Ok(
                ZenUmlMessage(
                    id = nextStatementId(),
                    line = start.line,
                    comment = comment,
                    kind = ZenUmlMessageKind.Return,
                    from = origin,
                    to = returnTarget,
                    label = label,
                    providedFrom = false,
                ),
            )
        }

        private fun parseAnnotatedReturn(
            origin: String,
            returnTarget: String,
            comment: String?,
        ): GMResult<ZenUmlStatement, MermaidError> {
            val start = current()
            index++
            skipTrivia()
            return parseMessage(
                origin = origin,
                returnTarget = returnTarget,
                comment = comment,
                forceReturn = true,
                lineOverride = start.line,
            )
        }

        private fun parseMessage(
            origin: String,
            returnTarget: String,
            comment: String?,
            forceReturn: Boolean = false,
            lineOverride: Int? = null,
        ): GMResult<ZenUmlStatement, MermaidError> {
            val start = current()
            val end = findStatementEnd(index)
            if (end == index) {
                return error(start, "Expected ZenUML statement")
            }
            val headerTokens = tokens.subList(index, end)
            val colon = findTopLevel(headerTokens, TokenKind.Colon)
            val returnArrow = findTopLevel(headerTokens, TokenKind.ReturnArrow)
            val arrow = findTopLevel(headerTokens, TokenKind.Arrow)
            val equal = findTopLevel(headerTokens, TokenKind.Equal)
            val newIndex = headerTokens.indexOfFirst {
                it.kind == TokenKind.Word && it.value.lowercase() == "new"
            }

            val message = when {
                forceReturn || returnArrow >= 0 -> parseAsyncLike(
                    headerTokens = headerTokens,
                    origin = origin,
                    returnTarget = returnTarget,
                    kind = ZenUmlMessageKind.Return,
                    colonIndex = colon,
                    arrowIndex = if (returnArrow >= 0) returnArrow else arrow,
                    comment = comment,
                    line = lineOverride ?: start.line,
                )
                colon >= 0 -> parseAsyncLike(
                    headerTokens = headerTokens,
                    origin = origin,
                    returnTarget = returnTarget,
                    kind = ZenUmlMessageKind.Async,
                    colonIndex = colon,
                    arrowIndex = arrow,
                    comment = comment,
                    line = lineOverride ?: start.line,
                )
                newIndex >= 0 -> parseCreationLike(
                    headerTokens = headerTokens,
                    newIndex = newIndex,
                    equalIndex = equal,
                    origin = origin,
                    comment = comment,
                    line = lineOverride ?: start.line,
                )
                else -> parseSyncLike(
                    headerTokens = headerTokens,
                    arrowIndex = arrow,
                    equalIndex = equal,
                    origin = origin,
                    comment = comment,
                    line = lineOverride ?: start.line,
                )
            }
            val parsed = when (message) {
                is GMResult.Ok -> message.value
                is GMResult.Err -> return message
            }
            index = end

            val body = if (at(TokenKind.LBrace) && parsed.kind in BODY_MESSAGE_KINDS) {
                index++
                when (
                    val result = parseBlock(
                        origin = parsed.to,
                        returnTarget = parsed.from,
                        stopAtBrace = true,
                    )
                ) {
                    is GMResult.Ok -> result.value
                    is GMResult.Err -> return result
                }
            } else {
                emptyList()
            }
            return GMResult.Ok(parsed.copy(body = body))
        }

        private fun parseAsyncLike(
            headerTokens: List<Token>,
            origin: String,
            returnTarget: String,
            kind: ZenUmlMessageKind,
            colonIndex: Int,
            arrowIndex: Int,
            comment: String?,
            line: Int,
        ): GMResult<ZenUmlMessage, MermaidError> {
            val leftEnd = if (colonIndex >= 0) colonIndex else headerTokens.size
            val left = headerTokens.subList(0, leftEnd)
            val from: String
            val to: String
            val providedFrom: Boolean
            if (arrowIndex >= 0 && arrowIndex < leftEnd) {
                from = nameFrom(left.subList(0, arrowIndex))
                    ?: return error(headerTokens.first(), "Expected sender before ZenUML arrow")
                to = nameFrom(left.subList(arrowIndex + 1, left.size))
                    ?: return error(headerTokens.first(), "Expected receiver after ZenUML arrow")
                providedFrom = true
            } else {
                val parsedTo = nameFrom(left)
                if (kind == ZenUmlMessageKind.Return && parsedTo == null) {
                    from = origin
                    to = returnTarget
                } else {
                    to = parsedTo
                        ?: return error(headerTokens.first(), "Expected ZenUML message receiver")
                    from = origin
                }
                providedFrom = explicitStarter != null
            }
            val label = if (colonIndex >= 0 && colonIndex + 1 < headerTokens.size) {
                formatText(rawRange(headerTokens, colonIndex + 1, headerTokens.size))
            } else {
                ""
            }
            if (!providedFrom && explicitStarter == null) {
                hasMessageWithoutProvidedFrom = true
            }
            addParticipant(from)
            addParticipant(to)
            return GMResult.Ok(
                ZenUmlMessage(
                    id = nextStatementId(),
                    line = line,
                    comment = comment,
                    kind = kind,
                    from = from,
                    to = to,
                    label = label,
                    providedFrom = providedFrom,
                ),
            )
        }

        private fun parseCreationLike(
            headerTokens: List<Token>,
            newIndex: Int,
            equalIndex: Int,
            origin: String,
            comment: String?,
            line: Int,
        ): GMResult<ZenUmlMessage, MermaidError> {
            val assignment = parseAssignment(headerTokens, equalIndex)
            val constructIndex = (newIndex + 1 until headerTokens.size).firstOrNull {
                isName(headerTokens[it])
            } ?: return error(headerTokens[newIndex], "Expected constructor name after new")
            val construct = headerTokens[constructIndex].value
            val to = assignment?.let { "${it.assignee}:$construct" } ?: construct
            val open = headerTokens.indexOfFirstFrom(TokenKind.LParen, constructIndex + 1)
            val close = if (open >= 0) matchingParen(headerTokens, open) else -1
            val parameters = if (open >= 0 && close > open) {
                formatCreationParameters(headerTokens, open + 1, close)
            } else {
                ""
            }
            val label = "«${parameters.ifBlank { "create" }}»"
            val providedFrom = explicitStarter != null || origin != ZEN_UML_STARTER
            if (!providedFrom) {
                hasMessageWithoutProvidedFrom = true
            }
            addParticipant(origin)
            addParticipant(to)
            return GMResult.Ok(
                ZenUmlMessage(
                    id = nextStatementId(),
                    line = line,
                    comment = comment,
                    kind = ZenUmlMessageKind.Creation,
                    from = origin,
                    to = to,
                    label = label,
                    providedFrom = providedFrom,
                    assignment = assignment,
                ),
            )
        }

        private fun parseSyncLike(
            headerTokens: List<Token>,
            arrowIndex: Int,
            equalIndex: Int,
            origin: String,
            comment: String?,
            line: Int,
        ): GMResult<ZenUmlMessage, MermaidError> {
            val assignment = parseAssignment(headerTokens, equalIndex)
            val bodyStart = if (equalIndex >= 0) equalIndex + 1 else 0
            val body = headerTokens.subList(bodyStart, headerTokens.size)
            val bodyArrow = if (arrowIndex >= bodyStart) arrowIndex - bodyStart else -1
            val dot = findTopLevel(body, TokenKind.Dot)
            val providedFrom = bodyArrow >= 0
            val from = if (providedFrom) {
                nameFrom(body.subList(0, bodyArrow))
                    ?: return error(headerTokens.first(), "Expected sender before ZenUML arrow")
            } else {
                origin
            }
            val targetStart = if (providedFrom) bodyArrow + 1 else 0
            val targetEnd = if (dot >= 0) dot else targetStart
            val to = if (dot >= 0) {
                nameFrom(body.subList(targetStart, targetEnd))
                    ?: return error(headerTokens.first(), "Expected receiver before method name")
            } else {
                origin
            }
            val signatureStart = if (dot >= 0) dot + 1 else targetStart
            val label = formatText(rawRange(body, signatureStart, body.size))
            if (label.isBlank()) {
                return error(headerTokens.first(), "Expected ZenUML method signature")
            }
            val effectiveProvidedFrom = providedFrom || explicitStarter != null || origin != ZEN_UML_STARTER
            if (!effectiveProvidedFrom) {
                hasMessageWithoutProvidedFrom = true
            }
            addParticipant(from)
            addParticipant(to)
            return GMResult.Ok(
                ZenUmlMessage(
                    id = nextStatementId(),
                    line = line,
                    comment = comment,
                    kind = ZenUmlMessageKind.Sync,
                    from = from,
                    to = to,
                    label = label,
                    providedFrom = effectiveProvidedFrom,
                    assignment = assignment,
                ),
            )
        }

        private fun parseAssignment(
            headerTokens: List<Token>,
            equalIndex: Int,
        ): ZenUmlAssignment? {
            if (equalIndex <= 0) return null
            val left = headerTokens.subList(0, equalIndex)
                .filterNot { it.kind == TokenKind.Newline || it.kind == TokenKind.Comment }
                .filterNot { it.kind == TokenKind.Word && it.value.lowercase() in MODIFIERS }
            val assignee = left.lastOrNull()?.takeIf(::isName)?.value ?: return null
            val type = left.dropLast(1).lastOrNull()?.takeIf(::isName)?.value
            return ZenUmlAssignment(assignee = assignee, type = type)
        }

        private fun parseRequiredBody(
            origin: String,
            returnTarget: String,
            owner: Token,
        ): GMResult<List<ZenUmlStatement>, MermaidError> {
            skipTrivia()
            if (!consume(TokenKind.LBrace)) {
                return error(owner, "Expected '{' for ZenUML block")
            }
            return parseBlock(origin, returnTarget, stopAtBrace = true)
        }

        private fun parseOptionalParenthesizedText(): String {
            skipTrivia()
            if (!consume(TokenKind.LParen)) return ""
            val start = index
            var depth = 1
            while (!at(TokenKind.Eof) && depth > 0) {
                when (current().kind) {
                    TokenKind.LParen -> depth++
                    TokenKind.RParen -> depth--
                    else -> Unit
                }
                if (depth > 0) index++
            }
            val end = index
            consume(TokenKind.RParen)
            return formatText(rawRange(start, end))
        }

        private fun isParticipantStart(): Boolean =
            isName(current()) ||
                current().kind == TokenKind.Annotation ||
                current().kind == TokenKind.StereotypeOpen ||
                current().kind == TokenKind.LBracket

        private fun isStatementStart(): Boolean {
            val token = current()
            if (token.kind == TokenKind.Divider || token.kind == TokenKind.LBrace) return true
            if (token.kind == TokenKind.Annotation) {
                return token.value.lowercase() in RETURN_ANNOTATIONS
            }
            if (token.kind == TokenKind.Word && token.value.lowercase() in STATEMENT_WORDS) {
                return true
            }
            var cursor = index
            while (
                cursor < tokens.size &&
                tokens[cursor].kind !in setOf(
                    TokenKind.Newline,
                    TokenKind.Semicolon,
                    TokenKind.RBrace,
                    TokenKind.Eof,
                )
            ) {
                if (
                    tokens[cursor].kind in setOf(
                        TokenKind.Dot,
                        TokenKind.Arrow,
                        TokenKind.ReturnArrow,
                        TokenKind.Colon,
                        TokenKind.Equal,
                        TokenKind.LParen,
                    )
                ) {
                    return true
                }
                cursor++
            }
            return false
        }

        private fun addParticipant(
            name: String,
            label: String? = null,
            type: String? = null,
            stereotype: String? = null,
            color: String? = null,
            emoji: String? = null,
            groupId: String? = null,
            explicit: Boolean = false,
            isStarter: Boolean = false,
        ) {
            if (name.isBlank() || name == ZEN_UML_STARTER) return
            val existing = participants[name]
            if (existing == null) {
                participants[name] = MutableParticipant(
                    name = name,
                    label = label,
                    type = type,
                    stereotype = stereotype,
                    color = color,
                    emoji = emoji,
                    groupId = groupId,
                    explicit = explicit,
                    isStarter = isStarter,
                )
            } else {
                existing.label = existing.label ?: label
                existing.type = existing.type ?: type
                existing.stereotype = existing.stereotype ?: stereotype
                existing.color = existing.color ?: color
                existing.emoji = existing.emoji ?: emoji
                existing.groupId = existing.groupId ?: groupId
                existing.explicit = existing.explicit || explicit
                existing.isStarter = existing.isStarter || isStarter
            }
        }

        private fun prependDefaultStarter() {
            if (participants.containsKey(ZEN_UML_STARTER)) return
            val reordered = linkedMapOf<String, MutableParticipant>()
            reordered[ZEN_UML_STARTER] = MutableParticipant(
                name = ZEN_UML_STARTER,
                isStarter = true,
            )
            reordered.putAll(participants)
            participants.clear()
            participants.putAll(reordered)
        }

        private fun countMessages(statements: List<ZenUmlStatement>): Int =
            statements.sumOf { statement ->
                when (statement) {
                    is ZenUmlMessage -> 1 + countMessages(statement.body)
                    is ZenUmlFragment -> statement.sections.sumOf { countMessages(it.statements) }
                    is ZenUmlDivider -> 0
                }
            }

        private fun findStatementEnd(start: Int): Int {
            var cursor = start
            var parenDepth = 0
            var bracketDepth = 0
            var inAsyncContent = false
            while (cursor < tokens.size) {
                val kind = tokens[cursor].kind
                if (kind == TokenKind.Colon && parenDepth == 0 && bracketDepth == 0) {
                    inAsyncContent = true
                }
                if (
                    inAsyncContent &&
                    kind in setOf(
                        TokenKind.RBrace,
                        TokenKind.Semicolon,
                        TokenKind.Newline,
                        TokenKind.Eof,
                    )
                ) {
                    return cursor
                }
                when (kind) {
                    TokenKind.LParen -> parenDepth++
                    TokenKind.RParen -> if (parenDepth > 0) parenDepth--
                    TokenKind.LBracket -> bracketDepth++
                    TokenKind.RBracket -> if (bracketDepth > 0) bracketDepth--
                    TokenKind.LBrace,
                    TokenKind.RBrace,
                    TokenKind.Semicolon,
                    TokenKind.Newline,
                    TokenKind.Eof,
                    -> if (parenDepth == 0 && bracketDepth == 0) return cursor
                    else -> Unit
                }
                cursor++
            }
            return cursor
        }

        private fun findLineEnd(start: Int): Int {
            var cursor = start
            while (cursor < tokens.size && tokens[cursor].kind !in setOf(TokenKind.Newline, TokenKind.Eof)) {
                cursor++
            }
            return cursor
        }

        private fun findTopLevel(
            values: List<Token>,
            kind: TokenKind,
        ): Int {
            var parenDepth = 0
            var bracketDepth = 0
            values.forEachIndexed { tokenIndex, token ->
                when (token.kind) {
                    TokenKind.LParen -> parenDepth++
                    TokenKind.RParen -> if (parenDepth > 0) parenDepth--
                    TokenKind.LBracket -> bracketDepth++
                    TokenKind.RBracket -> if (bracketDepth > 0) bracketDepth--
                    else -> Unit
                }
                if (token.kind == kind && parenDepth == 0 && bracketDepth == 0) {
                    return tokenIndex
                }
            }
            return -1
        }

        private fun matchingParen(
            values: List<Token>,
            openIndex: Int,
        ): Int {
            var depth = 0
            for (cursor in openIndex until values.size) {
                when (values[cursor].kind) {
                    TokenKind.LParen -> depth++
                    TokenKind.RParen -> {
                        depth--
                        if (depth == 0) return cursor
                    }
                    else -> Unit
                }
            }
            return -1
        }

        private fun List<Token>.indexOfFirstFrom(
            kind: TokenKind,
            start: Int,
        ): Int {
            for (cursor in start until size) {
                if (this[cursor].kind == kind) return cursor
            }
            return -1
        }

        private fun nameFrom(values: List<Token>): String? =
            values.firstOrNull(::isName)?.value

        private fun parseName(): String? {
            val token = current()
            return if (isName(token)) {
                index++
                token.value
            } else {
                null
            }
        }

        private fun isName(token: Token): Boolean =
            token.kind == TokenKind.Word ||
                token.kind == TokenKind.String ||
                token.kind == TokenKind.Number

        private fun rawRange(start: Int, end: Int): String =
            if (start >= end || start !in tokens.indices) {
                ""
            } else {
                source.substring(tokens[start].start, tokens[end - 1].end)
            }

        private fun rawRange(
            values: List<Token>,
            start: Int,
            end: Int,
        ): String =
            if (start >= end || start !in values.indices) {
                ""
            } else {
                source.substring(values[start].start, values[end - 1].end)
            }

        private fun formatText(value: String): String {
            var result = value
                .replace(Regex("[\\n\\r]"), " ")
                .replace(Regex("\\s+"), " ")
                .replace(Regex("\\s*([,;.])\\s*"), "$1")
                .replace(Regex("\\s*\\(\\s*"), "(")
                .replace(Regex("\\s*\\)"), ")")
                .trim()
            if (result.length >= 2 && result.first() == '"' && result.last() == '"') {
                result = result.substring(1, result.lastIndex)
            }
            return result.replace("\"\"", "\"")
        }

        /**
         * @zenuml/core 3.49.2:
         * src/parser/SignatureText.ts -> formatParameters + formatParameter.
         */
        private fun formatCreationParameters(
            values: List<Token>,
            start: Int,
            end: Int,
        ): String {
            val parameters = mutableListOf<String>()
            var parameterStart = start
            var depth = 0
            for (tokenIndex in start until end) {
                when (values[tokenIndex].kind) {
                    TokenKind.LParen,
                    TokenKind.LBracket,
                    TokenKind.LBrace,
                    -> depth++
                    TokenKind.RParen,
                    TokenKind.RBracket,
                    TokenKind.RBrace,
                    -> depth--
                    TokenKind.Comma -> if (depth == 0) {
                        formatCreationParameter(values, parameterStart, tokenIndex)
                            .takeIf(String::isNotEmpty)
                            ?.let(parameters::add)
                        parameterStart = tokenIndex + 1
                    }
                    else -> Unit
                }
            }
            formatCreationParameter(values, parameterStart, end)
                .takeIf(String::isNotEmpty)
                ?.let(parameters::add)
            return parameters.joinToString(",")
        }

        private fun formatCreationParameter(
            values: List<Token>,
            start: Int,
            end: Int,
        ): String {
            var depth = 0
            var assignmentIndex = -1
            for (tokenIndex in start until end) {
                when (values[tokenIndex].kind) {
                    TokenKind.LParen,
                    TokenKind.LBracket,
                    TokenKind.LBrace,
                    -> depth++
                    TokenKind.RParen,
                    TokenKind.RBracket,
                    TokenKind.RBrace,
                    -> depth--
                    TokenKind.Equal -> if (depth == 0 && assignmentIndex < 0) {
                        assignmentIndex = tokenIndex
                    }
                    else -> Unit
                }
            }
            if (assignmentIndex < 0) {
                return formatText(rawRange(values, start, end))
            }
            val name = formatText(rawRange(values, start, assignmentIndex))
            val expression = formatText(rawRange(values, assignmentIndex + 1, end))
            return "$name=$expression"
        }

        private fun skipTrivia() {
            while (at(TokenKind.Newline) || at(TokenKind.Comment)) index++
        }

        private fun skipInlineTrivia() {
            while (at(TokenKind.Comment)) index++
        }

        private fun current(): Token = tokens.getOrElse(index) { tokens.last() }

        private fun at(kind: TokenKind): Boolean = current().kind == kind

        private fun atWord(value: String): Boolean =
            current().kind == TokenKind.Word && current().value.equals(value, ignoreCase = true)

        private fun atWordIn(values: Set<String>): Boolean =
            current().kind == TokenKind.Word && current().value.lowercase() in values

        private fun atAnnotation(value: String): Boolean =
            current().kind == TokenKind.Annotation &&
                current().value.equals(value, ignoreCase = true)

        private fun consume(kind: TokenKind): Boolean {
            if (!at(kind)) return false
            index++
            return true
        }

        private fun nextStatementId(): Int = statementId++

        private fun <T> error(
            token: Token,
            message: String,
        ): GMResult<T, MermaidError> = GMResult.Err(
            MermaidError.Parse(
                line = token.line + lineOffset,
                column = token.column,
                message = message,
            ),
        )
    }

    private data class MutableParticipant(
        val name: String,
        var label: String? = null,
        var type: String? = null,
        var stereotype: String? = null,
        var color: String? = null,
        var emoji: String? = null,
        var groupId: String? = null,
        var explicit: Boolean = false,
        var isStarter: Boolean = false,
    ) {
        fun toModel(): ZenUmlParticipant = ZenUmlParticipant(
            name = name,
            label = label,
            type = type,
            stereotype = stereotype,
            color = color,
            emoji = emoji,
            groupId = groupId,
            explicit = explicit,
            isStarter = isStarter,
        )
    }

    private class ZenLexer(
        private val source: String,
        private val lineOffset: Int,
    ) {
        private val tokens = mutableListOf<Token>()
        private var index = 0
        private var line = 1
        private var column = 0
        private var lineOnlyWhitespace = true

        fun scan(): GMResult<List<Token>, MermaidError> {
            while (index < source.length) {
                val start = index
                val startLine = line
                val startColumn = column
                val character = source[index]
                when {
                    character == ' ' || character == '\t' -> advance()
                    character == '\r' || character == '\n' -> scanNewline(start, startLine, startColumn)
                    source.startsWith("//", index) -> scanLineToken(
                        kind = TokenKind.Comment,
                        prefixLength = 2,
                        start = start,
                        startLine = startLine,
                        startColumn = startColumn,
                    )
                    lineOnlyWhitespace && source.startsWith("==", index) -> scanLineToken(
                        kind = TokenKind.Divider,
                        prefixLength = 0,
                        start = start,
                        startLine = startLine,
                        startColumn = startColumn,
                    )
                    source.startsWith("-->", index) -> addFixed(
                        TokenKind.ReturnArrow,
                        "-->",
                        startLine,
                        startColumn,
                    )
                    source.startsWith("->", index) -> addFixed(
                        TokenKind.Arrow,
                        "->",
                        startLine,
                        startColumn,
                    )
                    source.startsWith("<<", index) -> addFixed(
                        TokenKind.StereotypeOpen,
                        "<<",
                        startLine,
                        startColumn,
                    )
                    source.startsWith(">>", index) -> addFixed(
                        TokenKind.StereotypeClose,
                        ">>",
                        startLine,
                        startColumn,
                    )
                    character == '"' -> scanString(start, startLine, startColumn)
                    character == '@' -> scanPrefixed(TokenKind.Annotation, start, startLine, startColumn)
                    character == '#' -> scanPrefixed(TokenKind.Color, start, startLine, startColumn)
                    character.isDigit() -> scanNumberOrWord(start, startLine, startColumn)
                    character in SYMBOLS -> {
                        addFixed(
                            kind = SYMBOL_KINDS.getValue(character),
                            value = character.toString(),
                            startLine = startLine,
                            startColumn = startColumn,
                        )
                    }
                    else -> scanWord(start, startLine, startColumn)
                }
            }
            tokens += Token(
                kind = TokenKind.Eof,
                value = "",
                start = source.length,
                end = source.length,
                line = line,
                column = column,
            )
            return GMResult.Ok(tokens)
        }

        private fun scanNewline(
            start: Int,
            startLine: Int,
            startColumn: Int,
        ) {
            if (source[index] == '\r') advance()
            if (index < source.length && source[index] == '\n') advance()
            tokens += Token(TokenKind.Newline, "\n", start, index, startLine, startColumn)
            line++
            column = 0
            lineOnlyWhitespace = true
        }

        private fun scanLineToken(
            kind: TokenKind,
            prefixLength: Int,
            start: Int,
            startLine: Int,
            startColumn: Int,
        ) {
            repeat(prefixLength) { advance() }
            val valueStart = index
            while (index < source.length && source[index] != '\n' && source[index] != '\r') {
                advance()
            }
            tokens += Token(
                kind = kind,
                value = source.substring(valueStart, index),
                start = start,
                end = index,
                line = startLine,
                column = startColumn,
            )
            lineOnlyWhitespace = false
        }

        private fun scanString(
            start: Int,
            startLine: Int,
            startColumn: Int,
        ) {
            advance()
            val value = StringBuilder()
            while (index < source.length && source[index] !in setOf('\n', '\r')) {
                if (source[index] == '"') {
                    if (index + 1 < source.length && source[index + 1] == '"') {
                        value.append('"')
                        advance()
                        advance()
                        continue
                    }
                    advance()
                    break
                }
                value.append(source[index])
                advance()
            }
            tokens += Token(
                kind = TokenKind.String,
                value = value.toString(),
                start = start,
                end = index,
                line = startLine,
                column = startColumn,
            )
            lineOnlyWhitespace = false
        }

        private fun scanPrefixed(
            kind: TokenKind,
            start: Int,
            startLine: Int,
            startColumn: Int,
        ) {
            advance()
            while (index < source.length && isWordCharacter(source[index])) advance()
            tokens += Token(
                kind = kind,
                value = source.substring(start, index),
                start = start,
                end = index,
                line = startLine,
                column = startColumn,
            )
            lineOnlyWhitespace = false
        }

        private fun scanNumberOrWord(
            start: Int,
            startLine: Int,
            startColumn: Int,
        ) {
            while (index < source.length && isWordCharacter(source[index])) advance()
            val value = source.substring(start, index)
            tokens += Token(
                kind = if (value.all(Char::isDigit)) TokenKind.Number else TokenKind.Word,
                value = value,
                start = start,
                end = index,
                line = startLine,
                column = startColumn,
            )
            lineOnlyWhitespace = false
        }

        private fun scanWord(
            start: Int,
            startLine: Int,
            startColumn: Int,
        ) {
            while (
                index < source.length &&
                !source[index].isWhitespace() &&
                source[index] !in WORD_BOUNDARIES
            ) {
                advance()
            }
            if (index == start) advance()
            tokens += Token(
                kind = TokenKind.Word,
                value = source.substring(start, index),
                start = start,
                end = index,
                line = startLine,
                column = startColumn,
            )
            lineOnlyWhitespace = false
        }

        private fun addFixed(
            kind: TokenKind,
            value: String,
            startLine: Int,
            startColumn: Int,
        ) {
            val start = index
            repeat(value.length) { advance() }
            tokens += Token(kind, value, start, index, startLine, startColumn)
            lineOnlyWhitespace = false
        }

        private fun advance() {
            index++
            column++
        }

        private fun isWordCharacter(character: Char): Boolean =
            !character.isWhitespace() && character !in WORD_BOUNDARIES

        companion object {
            private val SYMBOL_KINDS = mapOf(
                '.' to TokenKind.Dot,
                ':' to TokenKind.Colon,
                '=' to TokenKind.Equal,
                '(' to TokenKind.LParen,
                ')' to TokenKind.RParen,
                '{' to TokenKind.LBrace,
                '}' to TokenKind.RBrace,
                ',' to TokenKind.Comma,
                ';' to TokenKind.Semicolon,
                '[' to TokenKind.LBracket,
                ']' to TokenKind.RBracket,
            )
            private val SYMBOLS: Set<Char> = SYMBOL_KINDS.keys
            private val WORD_BOUNDARIES: Set<Char> =
                SYMBOLS + setOf('"', '@', '#', '<', '>', '-', '/', '+', '*', '%', '!', '&', '|')
        }
    }

    private data class Token(
        val kind: TokenKind,
        val value: String,
        val start: Int,
        val end: Int,
        val line: Int,
        val column: Int,
    )

    private enum class TokenKind {
        Word,
        String,
        Number,
        Annotation,
        Color,
        Arrow,
        ReturnArrow,
        Dot,
        Colon,
        Equal,
        LParen,
        RParen,
        LBrace,
        RBrace,
        Comma,
        Semicolon,
        LBracket,
        RBracket,
        StereotypeOpen,
        StereotypeClose,
        Comment,
        Divider,
        Newline,
        Eof,
    }

    companion object {
        private val LOOP_WORDS = setOf("while", "for", "foreach", "loop")
        private val RETURN_ANNOTATIONS = setOf("@return", "@reply")
        private val MODIFIERS = setOf("const", "readonly", "static", "await")
        private val BODY_MESSAGE_KINDS = setOf(
            ZenUmlMessageKind.Sync,
            ZenUmlMessageKind.Creation,
        )
        private val STATEMENT_WORDS = LOOP_WORDS + setOf(
            "if",
            "try",
            "par",
            "opt",
            "critical",
            "section",
            "frame",
            "ref",
            "return",
            "new",
        )
    }
}
