package io.github.cmpmermaid.core.xychart.upstream.mermaid

/**
 * Generated from Mermaid 12.0.0 xychart.jison.
 * Upstream xychart.jison SHA-256: ce1e4904b3c2036ac29cc62b6e6561058b00e4bc9c9bbf661873451bb55bf0fc
 * Distribution chunk SHA-256: d602c86e3513b44777118606f7190dbc4d260ecaba6f26ed3adb56f7375b2b7a
 *
 * Do not edit manually. Run:
 *   cd tools/official-reference && npm run generate:xychart-parser
 */
internal object XyJisonTables {
    val symbolIds: Map<String, Int> = mapOf(
        "error" to 2,
        "start" to 3,
        "eol" to 4,
        "XYCHART" to 5,
        "chartConfig" to 6,
        "document" to 7,
        "CHART_ORIENTATION" to 8,
        "statement" to 9,
        "title" to 10,
        "text" to 11,
        "X_AXIS" to 12,
        "parseXAxis" to 13,
        "Y_AXIS" to 14,
        "parseYAxis" to 15,
        "LINE" to 16,
        "plotData" to 17,
        "BAR" to 18,
        "acc_title" to 19,
        "acc_title_value" to 20,
        "acc_descr" to 21,
        "acc_descr_value" to 22,
        "acc_descr_multiline_value" to 23,
        "SQUARE_BRACES_START" to 24,
        "dataPoints" to 25,
        "SQUARE_BRACES_END" to 26,
        "dataPoint" to 27,
        "COMMA" to 28,
        "NUMBER_WITH_DECIMAL" to 29,
        "STR" to 30,
        "xAxisData" to 31,
        "bandData" to 32,
        "ARROW_DELIMITER" to 33,
        "commaSeparatedTexts" to 34,
        "yAxisData" to 35,
        "NEWLINE" to 36,
        "SEMI" to 37,
        "EOF" to 38,
        "alphaNum" to 39,
        "MD_STR" to 40,
        "alphaNumToken" to 41,
        "AMP" to 42,
        "NUM" to 43,
        "ALPHA" to 44,
        "PLUS" to 45,
        "EQUALS" to 46,
        "MULT" to 47,
        "DOT" to 48,
        "BRKT" to 49,
        "MINUS" to 50,
        "UNDERSCORE" to 51,
        "\$accept" to 0,
        "\$end" to 1,
    )

    val terminalNames: Map<Int, String> = mapOf(
        2 to "error",
        5 to "XYCHART",
        8 to "CHART_ORIENTATION",
        10 to "title",
        12 to "X_AXIS",
        14 to "Y_AXIS",
        16 to "LINE",
        18 to "BAR",
        19 to "acc_title",
        20 to "acc_title_value",
        21 to "acc_descr",
        22 to "acc_descr_value",
        23 to "acc_descr_multiline_value",
        24 to "SQUARE_BRACES_START",
        26 to "SQUARE_BRACES_END",
        28 to "COMMA",
        29 to "NUMBER_WITH_DECIMAL",
        30 to "STR",
        33 to "ARROW_DELIMITER",
        36 to "NEWLINE",
        37 to "SEMI",
        38 to "EOF",
        40 to "MD_STR",
        42 to "AMP",
        43 to "NUM",
        44 to "ALPHA",
        45 to "PLUS",
        46 to "EQUALS",
        47 to "MULT",
        48 to "DOT",
        49 to "BRKT",
        50 to "MINUS",
        51 to "UNDERSCORE",
    )

    val productions: Array<XyJisonProduction> = arrayOf(
        XyJisonProduction(symbol = 0, length = 0),
        XyJisonProduction(symbol = 3, length = 2),
        XyJisonProduction(symbol = 3, length = 3),
        XyJisonProduction(symbol = 3, length = 2),
        XyJisonProduction(symbol = 3, length = 1),
        XyJisonProduction(symbol = 6, length = 1),
        XyJisonProduction(symbol = 7, length = 0),
        XyJisonProduction(symbol = 7, length = 2),
        XyJisonProduction(symbol = 9, length = 2),
        XyJisonProduction(symbol = 9, length = 2),
        XyJisonProduction(symbol = 9, length = 2),
        XyJisonProduction(symbol = 9, length = 2),
        XyJisonProduction(symbol = 9, length = 2),
        XyJisonProduction(symbol = 9, length = 3),
        XyJisonProduction(symbol = 9, length = 2),
        XyJisonProduction(symbol = 9, length = 3),
        XyJisonProduction(symbol = 9, length = 2),
        XyJisonProduction(symbol = 9, length = 2),
        XyJisonProduction(symbol = 9, length = 1),
        XyJisonProduction(symbol = 17, length = 3),
        XyJisonProduction(symbol = 25, length = 3),
        XyJisonProduction(symbol = 25, length = 1),
        XyJisonProduction(symbol = 27, length = 2),
        XyJisonProduction(symbol = 27, length = 1),
        XyJisonProduction(symbol = 13, length = 1),
        XyJisonProduction(symbol = 13, length = 2),
        XyJisonProduction(symbol = 13, length = 1),
        XyJisonProduction(symbol = 31, length = 1),
        XyJisonProduction(symbol = 31, length = 3),
        XyJisonProduction(symbol = 32, length = 3),
        XyJisonProduction(symbol = 34, length = 3),
        XyJisonProduction(symbol = 34, length = 1),
        XyJisonProduction(symbol = 15, length = 1),
        XyJisonProduction(symbol = 15, length = 2),
        XyJisonProduction(symbol = 15, length = 1),
        XyJisonProduction(symbol = 35, length = 3),
        XyJisonProduction(symbol = 4, length = 1),
        XyJisonProduction(symbol = 4, length = 1),
        XyJisonProduction(symbol = 4, length = 1),
        XyJisonProduction(symbol = 11, length = 1),
        XyJisonProduction(symbol = 11, length = 1),
        XyJisonProduction(symbol = 11, length = 1),
        XyJisonProduction(symbol = 39, length = 1),
        XyJisonProduction(symbol = 39, length = 2),
        XyJisonProduction(symbol = 41, length = 1),
        XyJisonProduction(symbol = 41, length = 1),
        XyJisonProduction(symbol = 41, length = 1),
        XyJisonProduction(symbol = 41, length = 1),
        XyJisonProduction(symbol = 41, length = 1),
        XyJisonProduction(symbol = 41, length = 1),
        XyJisonProduction(symbol = 41, length = 1),
        XyJisonProduction(symbol = 41, length = 1),
        XyJisonProduction(symbol = 41, length = 1),
        XyJisonProduction(symbol = 41, length = 1),
    )

    val states: Array<Map<Int, XyJisonCell>> = buildList {
        addAll(stateChunk0())
        addAll(stateChunk1())
        addAll(stateChunk2())
        addAll(stateChunk3())
    }.toTypedArray()

    private fun stateChunk0(): Array<Map<Int, XyJisonCell>> = arrayOf(
        mapOf(
            1 to XyJisonCell.Reduce(6),
            3 to XyJisonCell.Goto(1),
            4 to XyJisonCell.Goto(2),
            5 to XyJisonCell.Shift(3),
            7 to XyJisonCell.Goto(4),
            10 to XyJisonCell.Reduce(6),
            12 to XyJisonCell.Reduce(6),
            14 to XyJisonCell.Reduce(6),
            16 to XyJisonCell.Reduce(6),
            18 to XyJisonCell.Reduce(6),
            19 to XyJisonCell.Reduce(6),
            21 to XyJisonCell.Reduce(6),
            23 to XyJisonCell.Reduce(6),
            36 to XyJisonCell.Shift(5),
            37 to XyJisonCell.Shift(6),
            38 to XyJisonCell.Shift(7),
        ),
        mapOf(
            1 to XyJisonCell.Accept,
        ),
        mapOf(
            1 to XyJisonCell.Reduce(6),
            3 to XyJisonCell.Goto(8),
            4 to XyJisonCell.Goto(2),
            5 to XyJisonCell.Shift(3),
            7 to XyJisonCell.Goto(4),
            10 to XyJisonCell.Reduce(6),
            12 to XyJisonCell.Reduce(6),
            14 to XyJisonCell.Reduce(6),
            16 to XyJisonCell.Reduce(6),
            18 to XyJisonCell.Reduce(6),
            19 to XyJisonCell.Reduce(6),
            21 to XyJisonCell.Reduce(6),
            23 to XyJisonCell.Reduce(6),
            36 to XyJisonCell.Shift(5),
            37 to XyJisonCell.Shift(6),
            38 to XyJisonCell.Shift(7),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(6),
            3 to XyJisonCell.Goto(10),
            4 to XyJisonCell.Goto(2),
            5 to XyJisonCell.Shift(3),
            6 to XyJisonCell.Goto(9),
            7 to XyJisonCell.Goto(4),
            8 to XyJisonCell.Shift(11),
            10 to XyJisonCell.Reduce(6),
            12 to XyJisonCell.Reduce(6),
            14 to XyJisonCell.Reduce(6),
            16 to XyJisonCell.Reduce(6),
            18 to XyJisonCell.Reduce(6),
            19 to XyJisonCell.Reduce(6),
            21 to XyJisonCell.Reduce(6),
            23 to XyJisonCell.Reduce(6),
            36 to XyJisonCell.Shift(5),
            37 to XyJisonCell.Shift(6),
            38 to XyJisonCell.Shift(7),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(4),
            9 to XyJisonCell.Goto(12),
            10 to XyJisonCell.Shift(13),
            12 to XyJisonCell.Shift(14),
            14 to XyJisonCell.Shift(15),
            16 to XyJisonCell.Shift(16),
            18 to XyJisonCell.Shift(17),
            19 to XyJisonCell.Shift(18),
            21 to XyJisonCell.Shift(19),
            23 to XyJisonCell.Shift(20),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(36),
            5 to XyJisonCell.Reduce(36),
            10 to XyJisonCell.Reduce(36),
            12 to XyJisonCell.Reduce(36),
            14 to XyJisonCell.Reduce(36),
            16 to XyJisonCell.Reduce(36),
            18 to XyJisonCell.Reduce(36),
            19 to XyJisonCell.Reduce(36),
            21 to XyJisonCell.Reduce(36),
            23 to XyJisonCell.Reduce(36),
            36 to XyJisonCell.Reduce(36),
            37 to XyJisonCell.Reduce(36),
            38 to XyJisonCell.Reduce(36),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(37),
            5 to XyJisonCell.Reduce(37),
            10 to XyJisonCell.Reduce(37),
            12 to XyJisonCell.Reduce(37),
            14 to XyJisonCell.Reduce(37),
            16 to XyJisonCell.Reduce(37),
            18 to XyJisonCell.Reduce(37),
            19 to XyJisonCell.Reduce(37),
            21 to XyJisonCell.Reduce(37),
            23 to XyJisonCell.Reduce(37),
            36 to XyJisonCell.Reduce(37),
            37 to XyJisonCell.Reduce(37),
            38 to XyJisonCell.Reduce(37),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(38),
            5 to XyJisonCell.Reduce(38),
            10 to XyJisonCell.Reduce(38),
            12 to XyJisonCell.Reduce(38),
            14 to XyJisonCell.Reduce(38),
            16 to XyJisonCell.Reduce(38),
            18 to XyJisonCell.Reduce(38),
            19 to XyJisonCell.Reduce(38),
            21 to XyJisonCell.Reduce(38),
            23 to XyJisonCell.Reduce(38),
            36 to XyJisonCell.Reduce(38),
            37 to XyJisonCell.Reduce(38),
            38 to XyJisonCell.Reduce(38),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(1),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(6),
            3 to XyJisonCell.Goto(21),
            4 to XyJisonCell.Goto(2),
            5 to XyJisonCell.Shift(3),
            7 to XyJisonCell.Goto(4),
            10 to XyJisonCell.Reduce(6),
            12 to XyJisonCell.Reduce(6),
            14 to XyJisonCell.Reduce(6),
            16 to XyJisonCell.Reduce(6),
            18 to XyJisonCell.Reduce(6),
            19 to XyJisonCell.Reduce(6),
            21 to XyJisonCell.Reduce(6),
            23 to XyJisonCell.Reduce(6),
            36 to XyJisonCell.Shift(5),
            37 to XyJisonCell.Shift(6),
            38 to XyJisonCell.Shift(7),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(3),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(5),
            5 to XyJisonCell.Reduce(5),
            10 to XyJisonCell.Reduce(5),
            12 to XyJisonCell.Reduce(5),
            14 to XyJisonCell.Reduce(5),
            16 to XyJisonCell.Reduce(5),
            18 to XyJisonCell.Reduce(5),
            19 to XyJisonCell.Reduce(5),
            21 to XyJisonCell.Reduce(5),
            23 to XyJisonCell.Reduce(5),
            36 to XyJisonCell.Reduce(5),
            37 to XyJisonCell.Reduce(5),
            38 to XyJisonCell.Reduce(5),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(7),
            4 to XyJisonCell.Goto(22),
            10 to XyJisonCell.Reduce(7),
            12 to XyJisonCell.Reduce(7),
            14 to XyJisonCell.Reduce(7),
            16 to XyJisonCell.Reduce(7),
            18 to XyJisonCell.Reduce(7),
            19 to XyJisonCell.Reduce(7),
            21 to XyJisonCell.Reduce(7),
            23 to XyJisonCell.Reduce(7),
            36 to XyJisonCell.Shift(5),
            37 to XyJisonCell.Shift(6),
            38 to XyJisonCell.Shift(7),
        ),
        mapOf(
            11 to XyJisonCell.Goto(23),
            30 to XyJisonCell.Shift(25),
            39 to XyJisonCell.Goto(24),
            40 to XyJisonCell.Shift(26),
            41 to XyJisonCell.Goto(27),
            42 to XyJisonCell.Shift(28),
            43 to XyJisonCell.Shift(29),
            44 to XyJisonCell.Shift(30),
            45 to XyJisonCell.Shift(31),
            46 to XyJisonCell.Shift(32),
            47 to XyJisonCell.Shift(33),
            48 to XyJisonCell.Shift(34),
            49 to XyJisonCell.Shift(35),
            50 to XyJisonCell.Shift(36),
            51 to XyJisonCell.Shift(37),
        ),
        mapOf(
            11 to XyJisonCell.Goto(39),
            13 to XyJisonCell.Goto(38),
            24 to XyJisonCell.Shift(43),
            29 to XyJisonCell.Shift(42),
            30 to XyJisonCell.Shift(25),
            31 to XyJisonCell.Goto(40),
            32 to XyJisonCell.Goto(41),
            39 to XyJisonCell.Goto(24),
            40 to XyJisonCell.Shift(26),
            41 to XyJisonCell.Goto(27),
            42 to XyJisonCell.Shift(28),
            43 to XyJisonCell.Shift(29),
            44 to XyJisonCell.Shift(30),
            45 to XyJisonCell.Shift(31),
            46 to XyJisonCell.Shift(32),
            47 to XyJisonCell.Shift(33),
            48 to XyJisonCell.Shift(34),
            49 to XyJisonCell.Shift(35),
            50 to XyJisonCell.Shift(36),
            51 to XyJisonCell.Shift(37),
        ),
        mapOf(
            11 to XyJisonCell.Goto(45),
            15 to XyJisonCell.Goto(44),
            29 to XyJisonCell.Shift(47),
            30 to XyJisonCell.Shift(25),
            35 to XyJisonCell.Goto(46),
            39 to XyJisonCell.Goto(24),
            40 to XyJisonCell.Shift(26),
            41 to XyJisonCell.Goto(27),
            42 to XyJisonCell.Shift(28),
            43 to XyJisonCell.Shift(29),
            44 to XyJisonCell.Shift(30),
            45 to XyJisonCell.Shift(31),
            46 to XyJisonCell.Shift(32),
            47 to XyJisonCell.Shift(33),
            48 to XyJisonCell.Shift(34),
            49 to XyJisonCell.Shift(35),
            50 to XyJisonCell.Shift(36),
            51 to XyJisonCell.Shift(37),
        ),
        mapOf(
            11 to XyJisonCell.Goto(49),
            17 to XyJisonCell.Goto(48),
            24 to XyJisonCell.Shift(50),
            30 to XyJisonCell.Shift(25),
            39 to XyJisonCell.Goto(24),
            40 to XyJisonCell.Shift(26),
            41 to XyJisonCell.Goto(27),
            42 to XyJisonCell.Shift(28),
            43 to XyJisonCell.Shift(29),
            44 to XyJisonCell.Shift(30),
            45 to XyJisonCell.Shift(31),
            46 to XyJisonCell.Shift(32),
            47 to XyJisonCell.Shift(33),
            48 to XyJisonCell.Shift(34),
            49 to XyJisonCell.Shift(35),
            50 to XyJisonCell.Shift(36),
            51 to XyJisonCell.Shift(37),
        ),
        mapOf(
            11 to XyJisonCell.Goto(52),
            17 to XyJisonCell.Goto(51),
            24 to XyJisonCell.Shift(50),
            30 to XyJisonCell.Shift(25),
            39 to XyJisonCell.Goto(24),
            40 to XyJisonCell.Shift(26),
            41 to XyJisonCell.Goto(27),
            42 to XyJisonCell.Shift(28),
            43 to XyJisonCell.Shift(29),
            44 to XyJisonCell.Shift(30),
            45 to XyJisonCell.Shift(31),
            46 to XyJisonCell.Shift(32),
            47 to XyJisonCell.Shift(33),
            48 to XyJisonCell.Shift(34),
            49 to XyJisonCell.Shift(35),
            50 to XyJisonCell.Shift(36),
            51 to XyJisonCell.Shift(37),
        ),
        mapOf(
            20 to XyJisonCell.Shift(53),
        ),
        mapOf(
            22 to XyJisonCell.Shift(54),
        ),
    )

    private fun stateChunk1(): Array<Map<Int, XyJisonCell>> = arrayOf(
        mapOf(
            1 to XyJisonCell.Reduce(18),
            10 to XyJisonCell.Reduce(18),
            12 to XyJisonCell.Reduce(18),
            14 to XyJisonCell.Reduce(18),
            16 to XyJisonCell.Reduce(18),
            18 to XyJisonCell.Reduce(18),
            19 to XyJisonCell.Reduce(18),
            21 to XyJisonCell.Reduce(18),
            23 to XyJisonCell.Reduce(18),
            36 to XyJisonCell.Reduce(18),
            37 to XyJisonCell.Reduce(18),
            38 to XyJisonCell.Reduce(18),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(2),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(8),
            10 to XyJisonCell.Reduce(8),
            12 to XyJisonCell.Reduce(8),
            14 to XyJisonCell.Reduce(8),
            16 to XyJisonCell.Reduce(8),
            18 to XyJisonCell.Reduce(8),
            19 to XyJisonCell.Reduce(8),
            21 to XyJisonCell.Reduce(8),
            23 to XyJisonCell.Reduce(8),
            36 to XyJisonCell.Reduce(8),
            37 to XyJisonCell.Reduce(8),
            38 to XyJisonCell.Reduce(8),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(9),
            10 to XyJisonCell.Reduce(9),
            12 to XyJisonCell.Reduce(9),
            14 to XyJisonCell.Reduce(9),
            16 to XyJisonCell.Reduce(9),
            18 to XyJisonCell.Reduce(9),
            19 to XyJisonCell.Reduce(9),
            21 to XyJisonCell.Reduce(9),
            23 to XyJisonCell.Reduce(9),
            36 to XyJisonCell.Reduce(9),
            37 to XyJisonCell.Reduce(9),
            38 to XyJisonCell.Reduce(9),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(39),
            10 to XyJisonCell.Reduce(39),
            12 to XyJisonCell.Reduce(39),
            14 to XyJisonCell.Reduce(39),
            16 to XyJisonCell.Reduce(39),
            18 to XyJisonCell.Reduce(39),
            19 to XyJisonCell.Reduce(39),
            21 to XyJisonCell.Reduce(39),
            23 to XyJisonCell.Reduce(39),
            24 to XyJisonCell.Reduce(39),
            26 to XyJisonCell.Reduce(39),
            28 to XyJisonCell.Reduce(39),
            29 to XyJisonCell.Reduce(39),
            36 to XyJisonCell.Reduce(39),
            37 to XyJisonCell.Reduce(39),
            38 to XyJisonCell.Reduce(39),
            41 to XyJisonCell.Goto(55),
            42 to XyJisonCell.Shift(28),
            43 to XyJisonCell.Shift(29),
            44 to XyJisonCell.Shift(30),
            45 to XyJisonCell.Shift(31),
            46 to XyJisonCell.Shift(32),
            47 to XyJisonCell.Shift(33),
            48 to XyJisonCell.Shift(34),
            49 to XyJisonCell.Shift(35),
            50 to XyJisonCell.Shift(36),
            51 to XyJisonCell.Shift(37),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(40),
            10 to XyJisonCell.Reduce(40),
            12 to XyJisonCell.Reduce(40),
            14 to XyJisonCell.Reduce(40),
            16 to XyJisonCell.Reduce(40),
            18 to XyJisonCell.Reduce(40),
            19 to XyJisonCell.Reduce(40),
            21 to XyJisonCell.Reduce(40),
            23 to XyJisonCell.Reduce(40),
            24 to XyJisonCell.Reduce(40),
            26 to XyJisonCell.Reduce(40),
            28 to XyJisonCell.Reduce(40),
            29 to XyJisonCell.Reduce(40),
            36 to XyJisonCell.Reduce(40),
            37 to XyJisonCell.Reduce(40),
            38 to XyJisonCell.Reduce(40),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(41),
            10 to XyJisonCell.Reduce(41),
            12 to XyJisonCell.Reduce(41),
            14 to XyJisonCell.Reduce(41),
            16 to XyJisonCell.Reduce(41),
            18 to XyJisonCell.Reduce(41),
            19 to XyJisonCell.Reduce(41),
            21 to XyJisonCell.Reduce(41),
            23 to XyJisonCell.Reduce(41),
            24 to XyJisonCell.Reduce(41),
            26 to XyJisonCell.Reduce(41),
            28 to XyJisonCell.Reduce(41),
            29 to XyJisonCell.Reduce(41),
            36 to XyJisonCell.Reduce(41),
            37 to XyJisonCell.Reduce(41),
            38 to XyJisonCell.Reduce(41),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(42),
            10 to XyJisonCell.Reduce(42),
            12 to XyJisonCell.Reduce(42),
            14 to XyJisonCell.Reduce(42),
            16 to XyJisonCell.Reduce(42),
            18 to XyJisonCell.Reduce(42),
            19 to XyJisonCell.Reduce(42),
            21 to XyJisonCell.Reduce(42),
            23 to XyJisonCell.Reduce(42),
            24 to XyJisonCell.Reduce(42),
            26 to XyJisonCell.Reduce(42),
            28 to XyJisonCell.Reduce(42),
            29 to XyJisonCell.Reduce(42),
            36 to XyJisonCell.Reduce(42),
            37 to XyJisonCell.Reduce(42),
            38 to XyJisonCell.Reduce(42),
            42 to XyJisonCell.Reduce(42),
            43 to XyJisonCell.Reduce(42),
            44 to XyJisonCell.Reduce(42),
            45 to XyJisonCell.Reduce(42),
            46 to XyJisonCell.Reduce(42),
            47 to XyJisonCell.Reduce(42),
            48 to XyJisonCell.Reduce(42),
            49 to XyJisonCell.Reduce(42),
            50 to XyJisonCell.Reduce(42),
            51 to XyJisonCell.Reduce(42),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(44),
            10 to XyJisonCell.Reduce(44),
            12 to XyJisonCell.Reduce(44),
            14 to XyJisonCell.Reduce(44),
            16 to XyJisonCell.Reduce(44),
            18 to XyJisonCell.Reduce(44),
            19 to XyJisonCell.Reduce(44),
            21 to XyJisonCell.Reduce(44),
            23 to XyJisonCell.Reduce(44),
            24 to XyJisonCell.Reduce(44),
            26 to XyJisonCell.Reduce(44),
            28 to XyJisonCell.Reduce(44),
            29 to XyJisonCell.Reduce(44),
            36 to XyJisonCell.Reduce(44),
            37 to XyJisonCell.Reduce(44),
            38 to XyJisonCell.Reduce(44),
            42 to XyJisonCell.Reduce(44),
            43 to XyJisonCell.Reduce(44),
            44 to XyJisonCell.Reduce(44),
            45 to XyJisonCell.Reduce(44),
            46 to XyJisonCell.Reduce(44),
            47 to XyJisonCell.Reduce(44),
            48 to XyJisonCell.Reduce(44),
            49 to XyJisonCell.Reduce(44),
            50 to XyJisonCell.Reduce(44),
            51 to XyJisonCell.Reduce(44),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(45),
            10 to XyJisonCell.Reduce(45),
            12 to XyJisonCell.Reduce(45),
            14 to XyJisonCell.Reduce(45),
            16 to XyJisonCell.Reduce(45),
            18 to XyJisonCell.Reduce(45),
            19 to XyJisonCell.Reduce(45),
            21 to XyJisonCell.Reduce(45),
            23 to XyJisonCell.Reduce(45),
            24 to XyJisonCell.Reduce(45),
            26 to XyJisonCell.Reduce(45),
            28 to XyJisonCell.Reduce(45),
            29 to XyJisonCell.Reduce(45),
            36 to XyJisonCell.Reduce(45),
            37 to XyJisonCell.Reduce(45),
            38 to XyJisonCell.Reduce(45),
            42 to XyJisonCell.Reduce(45),
            43 to XyJisonCell.Reduce(45),
            44 to XyJisonCell.Reduce(45),
            45 to XyJisonCell.Reduce(45),
            46 to XyJisonCell.Reduce(45),
            47 to XyJisonCell.Reduce(45),
            48 to XyJisonCell.Reduce(45),
            49 to XyJisonCell.Reduce(45),
            50 to XyJisonCell.Reduce(45),
            51 to XyJisonCell.Reduce(45),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(46),
            10 to XyJisonCell.Reduce(46),
            12 to XyJisonCell.Reduce(46),
            14 to XyJisonCell.Reduce(46),
            16 to XyJisonCell.Reduce(46),
            18 to XyJisonCell.Reduce(46),
            19 to XyJisonCell.Reduce(46),
            21 to XyJisonCell.Reduce(46),
            23 to XyJisonCell.Reduce(46),
            24 to XyJisonCell.Reduce(46),
            26 to XyJisonCell.Reduce(46),
            28 to XyJisonCell.Reduce(46),
            29 to XyJisonCell.Reduce(46),
            36 to XyJisonCell.Reduce(46),
            37 to XyJisonCell.Reduce(46),
            38 to XyJisonCell.Reduce(46),
            42 to XyJisonCell.Reduce(46),
            43 to XyJisonCell.Reduce(46),
            44 to XyJisonCell.Reduce(46),
            45 to XyJisonCell.Reduce(46),
            46 to XyJisonCell.Reduce(46),
            47 to XyJisonCell.Reduce(46),
            48 to XyJisonCell.Reduce(46),
            49 to XyJisonCell.Reduce(46),
            50 to XyJisonCell.Reduce(46),
            51 to XyJisonCell.Reduce(46),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(47),
            10 to XyJisonCell.Reduce(47),
            12 to XyJisonCell.Reduce(47),
            14 to XyJisonCell.Reduce(47),
            16 to XyJisonCell.Reduce(47),
            18 to XyJisonCell.Reduce(47),
            19 to XyJisonCell.Reduce(47),
            21 to XyJisonCell.Reduce(47),
            23 to XyJisonCell.Reduce(47),
            24 to XyJisonCell.Reduce(47),
            26 to XyJisonCell.Reduce(47),
            28 to XyJisonCell.Reduce(47),
            29 to XyJisonCell.Reduce(47),
            36 to XyJisonCell.Reduce(47),
            37 to XyJisonCell.Reduce(47),
            38 to XyJisonCell.Reduce(47),
            42 to XyJisonCell.Reduce(47),
            43 to XyJisonCell.Reduce(47),
            44 to XyJisonCell.Reduce(47),
            45 to XyJisonCell.Reduce(47),
            46 to XyJisonCell.Reduce(47),
            47 to XyJisonCell.Reduce(47),
            48 to XyJisonCell.Reduce(47),
            49 to XyJisonCell.Reduce(47),
            50 to XyJisonCell.Reduce(47),
            51 to XyJisonCell.Reduce(47),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(48),
            10 to XyJisonCell.Reduce(48),
            12 to XyJisonCell.Reduce(48),
            14 to XyJisonCell.Reduce(48),
            16 to XyJisonCell.Reduce(48),
            18 to XyJisonCell.Reduce(48),
            19 to XyJisonCell.Reduce(48),
            21 to XyJisonCell.Reduce(48),
            23 to XyJisonCell.Reduce(48),
            24 to XyJisonCell.Reduce(48),
            26 to XyJisonCell.Reduce(48),
            28 to XyJisonCell.Reduce(48),
            29 to XyJisonCell.Reduce(48),
            36 to XyJisonCell.Reduce(48),
            37 to XyJisonCell.Reduce(48),
            38 to XyJisonCell.Reduce(48),
            42 to XyJisonCell.Reduce(48),
            43 to XyJisonCell.Reduce(48),
            44 to XyJisonCell.Reduce(48),
            45 to XyJisonCell.Reduce(48),
            46 to XyJisonCell.Reduce(48),
            47 to XyJisonCell.Reduce(48),
            48 to XyJisonCell.Reduce(48),
            49 to XyJisonCell.Reduce(48),
            50 to XyJisonCell.Reduce(48),
            51 to XyJisonCell.Reduce(48),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(49),
            10 to XyJisonCell.Reduce(49),
            12 to XyJisonCell.Reduce(49),
            14 to XyJisonCell.Reduce(49),
            16 to XyJisonCell.Reduce(49),
            18 to XyJisonCell.Reduce(49),
            19 to XyJisonCell.Reduce(49),
            21 to XyJisonCell.Reduce(49),
            23 to XyJisonCell.Reduce(49),
            24 to XyJisonCell.Reduce(49),
            26 to XyJisonCell.Reduce(49),
            28 to XyJisonCell.Reduce(49),
            29 to XyJisonCell.Reduce(49),
            36 to XyJisonCell.Reduce(49),
            37 to XyJisonCell.Reduce(49),
            38 to XyJisonCell.Reduce(49),
            42 to XyJisonCell.Reduce(49),
            43 to XyJisonCell.Reduce(49),
            44 to XyJisonCell.Reduce(49),
            45 to XyJisonCell.Reduce(49),
            46 to XyJisonCell.Reduce(49),
            47 to XyJisonCell.Reduce(49),
            48 to XyJisonCell.Reduce(49),
            49 to XyJisonCell.Reduce(49),
            50 to XyJisonCell.Reduce(49),
            51 to XyJisonCell.Reduce(49),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(50),
            10 to XyJisonCell.Reduce(50),
            12 to XyJisonCell.Reduce(50),
            14 to XyJisonCell.Reduce(50),
            16 to XyJisonCell.Reduce(50),
            18 to XyJisonCell.Reduce(50),
            19 to XyJisonCell.Reduce(50),
            21 to XyJisonCell.Reduce(50),
            23 to XyJisonCell.Reduce(50),
            24 to XyJisonCell.Reduce(50),
            26 to XyJisonCell.Reduce(50),
            28 to XyJisonCell.Reduce(50),
            29 to XyJisonCell.Reduce(50),
            36 to XyJisonCell.Reduce(50),
            37 to XyJisonCell.Reduce(50),
            38 to XyJisonCell.Reduce(50),
            42 to XyJisonCell.Reduce(50),
            43 to XyJisonCell.Reduce(50),
            44 to XyJisonCell.Reduce(50),
            45 to XyJisonCell.Reduce(50),
            46 to XyJisonCell.Reduce(50),
            47 to XyJisonCell.Reduce(50),
            48 to XyJisonCell.Reduce(50),
            49 to XyJisonCell.Reduce(50),
            50 to XyJisonCell.Reduce(50),
            51 to XyJisonCell.Reduce(50),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(51),
            10 to XyJisonCell.Reduce(51),
            12 to XyJisonCell.Reduce(51),
            14 to XyJisonCell.Reduce(51),
            16 to XyJisonCell.Reduce(51),
            18 to XyJisonCell.Reduce(51),
            19 to XyJisonCell.Reduce(51),
            21 to XyJisonCell.Reduce(51),
            23 to XyJisonCell.Reduce(51),
            24 to XyJisonCell.Reduce(51),
            26 to XyJisonCell.Reduce(51),
            28 to XyJisonCell.Reduce(51),
            29 to XyJisonCell.Reduce(51),
            36 to XyJisonCell.Reduce(51),
            37 to XyJisonCell.Reduce(51),
            38 to XyJisonCell.Reduce(51),
            42 to XyJisonCell.Reduce(51),
            43 to XyJisonCell.Reduce(51),
            44 to XyJisonCell.Reduce(51),
            45 to XyJisonCell.Reduce(51),
            46 to XyJisonCell.Reduce(51),
            47 to XyJisonCell.Reduce(51),
            48 to XyJisonCell.Reduce(51),
            49 to XyJisonCell.Reduce(51),
            50 to XyJisonCell.Reduce(51),
            51 to XyJisonCell.Reduce(51),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(52),
            10 to XyJisonCell.Reduce(52),
            12 to XyJisonCell.Reduce(52),
            14 to XyJisonCell.Reduce(52),
            16 to XyJisonCell.Reduce(52),
            18 to XyJisonCell.Reduce(52),
            19 to XyJisonCell.Reduce(52),
            21 to XyJisonCell.Reduce(52),
            23 to XyJisonCell.Reduce(52),
            24 to XyJisonCell.Reduce(52),
            26 to XyJisonCell.Reduce(52),
            28 to XyJisonCell.Reduce(52),
            29 to XyJisonCell.Reduce(52),
            36 to XyJisonCell.Reduce(52),
            37 to XyJisonCell.Reduce(52),
            38 to XyJisonCell.Reduce(52),
            42 to XyJisonCell.Reduce(52),
            43 to XyJisonCell.Reduce(52),
            44 to XyJisonCell.Reduce(52),
            45 to XyJisonCell.Reduce(52),
            46 to XyJisonCell.Reduce(52),
            47 to XyJisonCell.Reduce(52),
            48 to XyJisonCell.Reduce(52),
            49 to XyJisonCell.Reduce(52),
            50 to XyJisonCell.Reduce(52),
            51 to XyJisonCell.Reduce(52),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(53),
            10 to XyJisonCell.Reduce(53),
            12 to XyJisonCell.Reduce(53),
            14 to XyJisonCell.Reduce(53),
            16 to XyJisonCell.Reduce(53),
            18 to XyJisonCell.Reduce(53),
            19 to XyJisonCell.Reduce(53),
            21 to XyJisonCell.Reduce(53),
            23 to XyJisonCell.Reduce(53),
            24 to XyJisonCell.Reduce(53),
            26 to XyJisonCell.Reduce(53),
            28 to XyJisonCell.Reduce(53),
            29 to XyJisonCell.Reduce(53),
            36 to XyJisonCell.Reduce(53),
            37 to XyJisonCell.Reduce(53),
            38 to XyJisonCell.Reduce(53),
            42 to XyJisonCell.Reduce(53),
            43 to XyJisonCell.Reduce(53),
            44 to XyJisonCell.Reduce(53),
            45 to XyJisonCell.Reduce(53),
            46 to XyJisonCell.Reduce(53),
            47 to XyJisonCell.Reduce(53),
            48 to XyJisonCell.Reduce(53),
            49 to XyJisonCell.Reduce(53),
            50 to XyJisonCell.Reduce(53),
            51 to XyJisonCell.Reduce(53),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(10),
            10 to XyJisonCell.Reduce(10),
            12 to XyJisonCell.Reduce(10),
            14 to XyJisonCell.Reduce(10),
            16 to XyJisonCell.Reduce(10),
            18 to XyJisonCell.Reduce(10),
            19 to XyJisonCell.Reduce(10),
            21 to XyJisonCell.Reduce(10),
            23 to XyJisonCell.Reduce(10),
            36 to XyJisonCell.Reduce(10),
            37 to XyJisonCell.Reduce(10),
            38 to XyJisonCell.Reduce(10),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(24),
            10 to XyJisonCell.Reduce(24),
            12 to XyJisonCell.Reduce(24),
            14 to XyJisonCell.Reduce(24),
            16 to XyJisonCell.Reduce(24),
            18 to XyJisonCell.Reduce(24),
            19 to XyJisonCell.Reduce(24),
            21 to XyJisonCell.Reduce(24),
            23 to XyJisonCell.Reduce(24),
            24 to XyJisonCell.Shift(43),
            29 to XyJisonCell.Shift(42),
            31 to XyJisonCell.Goto(56),
            32 to XyJisonCell.Goto(41),
            36 to XyJisonCell.Reduce(24),
            37 to XyJisonCell.Reduce(24),
            38 to XyJisonCell.Reduce(24),
        ),
    )

    private fun stateChunk2(): Array<Map<Int, XyJisonCell>> = arrayOf(
        mapOf(
            1 to XyJisonCell.Reduce(26),
            10 to XyJisonCell.Reduce(26),
            12 to XyJisonCell.Reduce(26),
            14 to XyJisonCell.Reduce(26),
            16 to XyJisonCell.Reduce(26),
            18 to XyJisonCell.Reduce(26),
            19 to XyJisonCell.Reduce(26),
            21 to XyJisonCell.Reduce(26),
            23 to XyJisonCell.Reduce(26),
            36 to XyJisonCell.Reduce(26),
            37 to XyJisonCell.Reduce(26),
            38 to XyJisonCell.Reduce(26),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(27),
            10 to XyJisonCell.Reduce(27),
            12 to XyJisonCell.Reduce(27),
            14 to XyJisonCell.Reduce(27),
            16 to XyJisonCell.Reduce(27),
            18 to XyJisonCell.Reduce(27),
            19 to XyJisonCell.Reduce(27),
            21 to XyJisonCell.Reduce(27),
            23 to XyJisonCell.Reduce(27),
            36 to XyJisonCell.Reduce(27),
            37 to XyJisonCell.Reduce(27),
            38 to XyJisonCell.Reduce(27),
        ),
        mapOf(
            33 to XyJisonCell.Shift(57),
        ),
        mapOf(
            11 to XyJisonCell.Goto(59),
            30 to XyJisonCell.Shift(25),
            34 to XyJisonCell.Goto(58),
            39 to XyJisonCell.Goto(24),
            40 to XyJisonCell.Shift(26),
            41 to XyJisonCell.Goto(27),
            42 to XyJisonCell.Shift(28),
            43 to XyJisonCell.Shift(29),
            44 to XyJisonCell.Shift(30),
            45 to XyJisonCell.Shift(31),
            46 to XyJisonCell.Shift(32),
            47 to XyJisonCell.Shift(33),
            48 to XyJisonCell.Shift(34),
            49 to XyJisonCell.Shift(35),
            50 to XyJisonCell.Shift(36),
            51 to XyJisonCell.Shift(37),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(11),
            10 to XyJisonCell.Reduce(11),
            12 to XyJisonCell.Reduce(11),
            14 to XyJisonCell.Reduce(11),
            16 to XyJisonCell.Reduce(11),
            18 to XyJisonCell.Reduce(11),
            19 to XyJisonCell.Reduce(11),
            21 to XyJisonCell.Reduce(11),
            23 to XyJisonCell.Reduce(11),
            36 to XyJisonCell.Reduce(11),
            37 to XyJisonCell.Reduce(11),
            38 to XyJisonCell.Reduce(11),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(32),
            10 to XyJisonCell.Reduce(32),
            12 to XyJisonCell.Reduce(32),
            14 to XyJisonCell.Reduce(32),
            16 to XyJisonCell.Reduce(32),
            18 to XyJisonCell.Reduce(32),
            19 to XyJisonCell.Reduce(32),
            21 to XyJisonCell.Reduce(32),
            23 to XyJisonCell.Reduce(32),
            29 to XyJisonCell.Shift(47),
            35 to XyJisonCell.Goto(60),
            36 to XyJisonCell.Reduce(32),
            37 to XyJisonCell.Reduce(32),
            38 to XyJisonCell.Reduce(32),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(34),
            10 to XyJisonCell.Reduce(34),
            12 to XyJisonCell.Reduce(34),
            14 to XyJisonCell.Reduce(34),
            16 to XyJisonCell.Reduce(34),
            18 to XyJisonCell.Reduce(34),
            19 to XyJisonCell.Reduce(34),
            21 to XyJisonCell.Reduce(34),
            23 to XyJisonCell.Reduce(34),
            36 to XyJisonCell.Reduce(34),
            37 to XyJisonCell.Reduce(34),
            38 to XyJisonCell.Reduce(34),
        ),
        mapOf(
            33 to XyJisonCell.Shift(61),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(12),
            10 to XyJisonCell.Reduce(12),
            12 to XyJisonCell.Reduce(12),
            14 to XyJisonCell.Reduce(12),
            16 to XyJisonCell.Reduce(12),
            18 to XyJisonCell.Reduce(12),
            19 to XyJisonCell.Reduce(12),
            21 to XyJisonCell.Reduce(12),
            23 to XyJisonCell.Reduce(12),
            36 to XyJisonCell.Reduce(12),
            37 to XyJisonCell.Reduce(12),
            38 to XyJisonCell.Reduce(12),
        ),
        mapOf(
            17 to XyJisonCell.Goto(62),
            24 to XyJisonCell.Shift(50),
        ),
        mapOf(
            25 to XyJisonCell.Goto(63),
            27 to XyJisonCell.Goto(64),
            29 to XyJisonCell.Shift(65),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(14),
            10 to XyJisonCell.Reduce(14),
            12 to XyJisonCell.Reduce(14),
            14 to XyJisonCell.Reduce(14),
            16 to XyJisonCell.Reduce(14),
            18 to XyJisonCell.Reduce(14),
            19 to XyJisonCell.Reduce(14),
            21 to XyJisonCell.Reduce(14),
            23 to XyJisonCell.Reduce(14),
            36 to XyJisonCell.Reduce(14),
            37 to XyJisonCell.Reduce(14),
            38 to XyJisonCell.Reduce(14),
        ),
        mapOf(
            17 to XyJisonCell.Goto(66),
            24 to XyJisonCell.Shift(50),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(16),
            10 to XyJisonCell.Reduce(16),
            12 to XyJisonCell.Reduce(16),
            14 to XyJisonCell.Reduce(16),
            16 to XyJisonCell.Reduce(16),
            18 to XyJisonCell.Reduce(16),
            19 to XyJisonCell.Reduce(16),
            21 to XyJisonCell.Reduce(16),
            23 to XyJisonCell.Reduce(16),
            36 to XyJisonCell.Reduce(16),
            37 to XyJisonCell.Reduce(16),
            38 to XyJisonCell.Reduce(16),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(17),
            10 to XyJisonCell.Reduce(17),
            12 to XyJisonCell.Reduce(17),
            14 to XyJisonCell.Reduce(17),
            16 to XyJisonCell.Reduce(17),
            18 to XyJisonCell.Reduce(17),
            19 to XyJisonCell.Reduce(17),
            21 to XyJisonCell.Reduce(17),
            23 to XyJisonCell.Reduce(17),
            36 to XyJisonCell.Reduce(17),
            37 to XyJisonCell.Reduce(17),
            38 to XyJisonCell.Reduce(17),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(43),
            10 to XyJisonCell.Reduce(43),
            12 to XyJisonCell.Reduce(43),
            14 to XyJisonCell.Reduce(43),
            16 to XyJisonCell.Reduce(43),
            18 to XyJisonCell.Reduce(43),
            19 to XyJisonCell.Reduce(43),
            21 to XyJisonCell.Reduce(43),
            23 to XyJisonCell.Reduce(43),
            24 to XyJisonCell.Reduce(43),
            26 to XyJisonCell.Reduce(43),
            28 to XyJisonCell.Reduce(43),
            29 to XyJisonCell.Reduce(43),
            36 to XyJisonCell.Reduce(43),
            37 to XyJisonCell.Reduce(43),
            38 to XyJisonCell.Reduce(43),
            42 to XyJisonCell.Reduce(43),
            43 to XyJisonCell.Reduce(43),
            44 to XyJisonCell.Reduce(43),
            45 to XyJisonCell.Reduce(43),
            46 to XyJisonCell.Reduce(43),
            47 to XyJisonCell.Reduce(43),
            48 to XyJisonCell.Reduce(43),
            49 to XyJisonCell.Reduce(43),
            50 to XyJisonCell.Reduce(43),
            51 to XyJisonCell.Reduce(43),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(25),
            10 to XyJisonCell.Reduce(25),
            12 to XyJisonCell.Reduce(25),
            14 to XyJisonCell.Reduce(25),
            16 to XyJisonCell.Reduce(25),
            18 to XyJisonCell.Reduce(25),
            19 to XyJisonCell.Reduce(25),
            21 to XyJisonCell.Reduce(25),
            23 to XyJisonCell.Reduce(25),
            36 to XyJisonCell.Reduce(25),
            37 to XyJisonCell.Reduce(25),
            38 to XyJisonCell.Reduce(25),
        ),
        mapOf(
            29 to XyJisonCell.Shift(67),
        ),
        mapOf(
            26 to XyJisonCell.Shift(68),
        ),
        mapOf(
            26 to XyJisonCell.Reduce(31),
            28 to XyJisonCell.Shift(69),
        ),
    )

    private fun stateChunk3(): Array<Map<Int, XyJisonCell>> = arrayOf(
        mapOf(
            1 to XyJisonCell.Reduce(33),
            10 to XyJisonCell.Reduce(33),
            12 to XyJisonCell.Reduce(33),
            14 to XyJisonCell.Reduce(33),
            16 to XyJisonCell.Reduce(33),
            18 to XyJisonCell.Reduce(33),
            19 to XyJisonCell.Reduce(33),
            21 to XyJisonCell.Reduce(33),
            23 to XyJisonCell.Reduce(33),
            36 to XyJisonCell.Reduce(33),
            37 to XyJisonCell.Reduce(33),
            38 to XyJisonCell.Reduce(33),
        ),
        mapOf(
            29 to XyJisonCell.Shift(70),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(13),
            10 to XyJisonCell.Reduce(13),
            12 to XyJisonCell.Reduce(13),
            14 to XyJisonCell.Reduce(13),
            16 to XyJisonCell.Reduce(13),
            18 to XyJisonCell.Reduce(13),
            19 to XyJisonCell.Reduce(13),
            21 to XyJisonCell.Reduce(13),
            23 to XyJisonCell.Reduce(13),
            36 to XyJisonCell.Reduce(13),
            37 to XyJisonCell.Reduce(13),
            38 to XyJisonCell.Reduce(13),
        ),
        mapOf(
            26 to XyJisonCell.Shift(71),
        ),
        mapOf(
            26 to XyJisonCell.Reduce(21),
            28 to XyJisonCell.Shift(72),
        ),
        mapOf(
            26 to XyJisonCell.Reduce(23),
            28 to XyJisonCell.Reduce(23),
            30 to XyJisonCell.Shift(73),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(15),
            10 to XyJisonCell.Reduce(15),
            12 to XyJisonCell.Reduce(15),
            14 to XyJisonCell.Reduce(15),
            16 to XyJisonCell.Reduce(15),
            18 to XyJisonCell.Reduce(15),
            19 to XyJisonCell.Reduce(15),
            21 to XyJisonCell.Reduce(15),
            23 to XyJisonCell.Reduce(15),
            36 to XyJisonCell.Reduce(15),
            37 to XyJisonCell.Reduce(15),
            38 to XyJisonCell.Reduce(15),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(28),
            10 to XyJisonCell.Reduce(28),
            12 to XyJisonCell.Reduce(28),
            14 to XyJisonCell.Reduce(28),
            16 to XyJisonCell.Reduce(28),
            18 to XyJisonCell.Reduce(28),
            19 to XyJisonCell.Reduce(28),
            21 to XyJisonCell.Reduce(28),
            23 to XyJisonCell.Reduce(28),
            36 to XyJisonCell.Reduce(28),
            37 to XyJisonCell.Reduce(28),
            38 to XyJisonCell.Reduce(28),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(29),
            10 to XyJisonCell.Reduce(29),
            12 to XyJisonCell.Reduce(29),
            14 to XyJisonCell.Reduce(29),
            16 to XyJisonCell.Reduce(29),
            18 to XyJisonCell.Reduce(29),
            19 to XyJisonCell.Reduce(29),
            21 to XyJisonCell.Reduce(29),
            23 to XyJisonCell.Reduce(29),
            36 to XyJisonCell.Reduce(29),
            37 to XyJisonCell.Reduce(29),
            38 to XyJisonCell.Reduce(29),
        ),
        mapOf(
            11 to XyJisonCell.Goto(59),
            30 to XyJisonCell.Shift(25),
            34 to XyJisonCell.Goto(74),
            39 to XyJisonCell.Goto(24),
            40 to XyJisonCell.Shift(26),
            41 to XyJisonCell.Goto(27),
            42 to XyJisonCell.Shift(28),
            43 to XyJisonCell.Shift(29),
            44 to XyJisonCell.Shift(30),
            45 to XyJisonCell.Shift(31),
            46 to XyJisonCell.Shift(32),
            47 to XyJisonCell.Shift(33),
            48 to XyJisonCell.Shift(34),
            49 to XyJisonCell.Shift(35),
            50 to XyJisonCell.Shift(36),
            51 to XyJisonCell.Shift(37),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(35),
            10 to XyJisonCell.Reduce(35),
            12 to XyJisonCell.Reduce(35),
            14 to XyJisonCell.Reduce(35),
            16 to XyJisonCell.Reduce(35),
            18 to XyJisonCell.Reduce(35),
            19 to XyJisonCell.Reduce(35),
            21 to XyJisonCell.Reduce(35),
            23 to XyJisonCell.Reduce(35),
            36 to XyJisonCell.Reduce(35),
            37 to XyJisonCell.Reduce(35),
            38 to XyJisonCell.Reduce(35),
        ),
        mapOf(
            1 to XyJisonCell.Reduce(19),
            10 to XyJisonCell.Reduce(19),
            12 to XyJisonCell.Reduce(19),
            14 to XyJisonCell.Reduce(19),
            16 to XyJisonCell.Reduce(19),
            18 to XyJisonCell.Reduce(19),
            19 to XyJisonCell.Reduce(19),
            21 to XyJisonCell.Reduce(19),
            23 to XyJisonCell.Reduce(19),
            36 to XyJisonCell.Reduce(19),
            37 to XyJisonCell.Reduce(19),
            38 to XyJisonCell.Reduce(19),
        ),
        mapOf(
            25 to XyJisonCell.Goto(75),
            27 to XyJisonCell.Goto(64),
            29 to XyJisonCell.Shift(65),
        ),
        mapOf(
            26 to XyJisonCell.Reduce(22),
            28 to XyJisonCell.Reduce(22),
        ),
        mapOf(
            26 to XyJisonCell.Reduce(30),
        ),
        mapOf(
            26 to XyJisonCell.Reduce(20),
        ),
    )

    val lexerPatterns: List<XyJisonLexerPattern> = buildList {
        addAll(lexerChunk0())
        addAll(lexerChunk1())
        addAll(lexerChunk2())
    }

    private fun lexerChunk0(): List<XyJisonLexerPattern> = listOf(
        XyJisonLexerPattern(0, "^(?:%%(?!\\{)[^\\n]*)"),
        XyJisonLexerPattern(1, "^(?:[^\\}]%%[^\\n]*)"),
        XyJisonLexerPattern(2, "^(?:(\\r?\\n))"),
        XyJisonLexerPattern(3, "^(?:(\\r?\\n))"),
        XyJisonLexerPattern(4, "^(?:[\\n\\r]+)"),
        XyJisonLexerPattern(5, "^(?:%%[^\\n]*)"),
        XyJisonLexerPattern(6, "^(?:title\\b)"),
        XyJisonLexerPattern(7, "^(?:accTitle\\s*:\\s*)"),
        XyJisonLexerPattern(8, "^(?:(?!\\n||)*[^\\n]*)"),
        XyJisonLexerPattern(9, "^(?:accDescr\\s*:\\s*)"),
        XyJisonLexerPattern(10, "^(?:(?!\\n||)*[^\\n]*)"),
        XyJisonLexerPattern(11, "^(?:accDescr\\s*\\{\\s*)"),
        XyJisonLexerPattern(12, "^(?:\\})"),
        XyJisonLexerPattern(13, "^(?:[^\\}]*)"),
        XyJisonLexerPattern(14, "^(?:xychart-beta\\b)"),
        XyJisonLexerPattern(15, "^(?:xychart\\b)"),
        XyJisonLexerPattern(16, "^(?:(?:vertical|horizontal))"),
        XyJisonLexerPattern(17, "^(?:x-axis\\b)"),
        XyJisonLexerPattern(18, "^(?:y-axis\\b)"),
        XyJisonLexerPattern(19, "^(?:\\[)"),
    )

    private fun lexerChunk1(): List<XyJisonLexerPattern> = listOf(
        XyJisonLexerPattern(20, "^(?:-->)"),
        XyJisonLexerPattern(21, "^(?:line\\b)"),
        XyJisonLexerPattern(22, "^(?:bar\\b)"),
        XyJisonLexerPattern(23, "^(?:\\[)"),
        XyJisonLexerPattern(24, "^(?:[+-]?(?:\\d+(?:\\.\\d+)?|\\.\\d+))"),
        XyJisonLexerPattern(25, "^(?:\\])"),
        XyJisonLexerPattern(26, "^(?:(?:`\\)                                    \\{ this\\.pushState\\(md_string\\); \\}\\n<md_string>\\(\\?:\\(\\?!`\"\\)\\.\\)\\+                  \\{ return MD_STR; \\}\\n<md_string>\\(\\?:`))"),
        XyJisonLexerPattern(27, "^(?:[\"])"),
        XyJisonLexerPattern(28, "^(?:[\"])"),
        XyJisonLexerPattern(29, "^(?:[^\"]*)"),
        XyJisonLexerPattern(30, "^(?:\\[)"),
        XyJisonLexerPattern(31, "^(?:\\])"),
        XyJisonLexerPattern(32, "^(?:[A-Za-z]+)"),
        XyJisonLexerPattern(33, "^(?::)"),
        XyJisonLexerPattern(34, "^(?:\\+)"),
        XyJisonLexerPattern(35, "^(?:,)"),
        XyJisonLexerPattern(36, "^(?:=)"),
        XyJisonLexerPattern(37, "^(?:\\*)"),
        XyJisonLexerPattern(38, "^(?:#)"),
        XyJisonLexerPattern(39, "^(?:[\\_])"),
    )

    private fun lexerChunk2(): List<XyJisonLexerPattern> = listOf(
        XyJisonLexerPattern(40, "^(?:\\.)"),
        XyJisonLexerPattern(41, "^(?:&)"),
        XyJisonLexerPattern(42, "^(?:-)"),
        XyJisonLexerPattern(43, "^(?:[0-9]+)"),
        XyJisonLexerPattern(44, "^(?:\\s+)"),
        XyJisonLexerPattern(45, "^(?:;)"),
        XyJisonLexerPattern(46, "^(?:\$)"),
    )

    val lexerConditions: Map<String, IntArray> = mapOf(
        "data_inner" to intArrayOf(0, 1, 4, 5, 6, 7, 9, 11, 14, 15, 16, 17, 18, 21, 22, 24, 25, 26, 27, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46),
        "data" to intArrayOf(0, 1, 3, 4, 5, 6, 7, 9, 11, 14, 15, 16, 17, 18, 21, 22, 23, 26, 27, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46),
        "axis_band_data" to intArrayOf(0, 1, 4, 5, 6, 7, 9, 11, 14, 15, 16, 17, 18, 21, 22, 25, 26, 27, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46),
        "axis_data" to intArrayOf(0, 1, 2, 4, 5, 6, 7, 9, 11, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 26, 27, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46),
        "acc_descr_multiline" to intArrayOf(12, 13),
        "acc_descr" to intArrayOf(10),
        "acc_title" to intArrayOf(8),
        "title" to intArrayOf(),
        "md_string" to intArrayOf(),
        "string" to intArrayOf(28, 29),
        "INITIAL" to intArrayOf(0, 1, 4, 5, 6, 7, 9, 11, 14, 15, 16, 17, 18, 21, 22, 26, 27, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46),
    )
}
