package com.swithun.cmpmermaid.core.gantt.upstream.mermaid

/**
 * Generated from Mermaid 12.0.0 gantt.jison.
 * Upstream gantt.jison SHA-256: 14d325aa626a7fa220c341a75faecc712d0121203e0f88db6c11e68f0bc7e82f
 * Distribution chunk SHA-256: f60134c37d88d5058ba503a2dedf5eab6f280b5d6d1d19aedbb0a85a67be409d
 *
 * Do not edit manually. Run:
 *   cd tools/official-reference && npm run generate:gantt-parser
 */
internal object GanttJisonTables {
    val symbolIds: Map<String, Int> = mapOf(
        "error" to 2,
        "start" to 3,
        "gantt" to 4,
        "document" to 5,
        "EOF" to 6,
        "line" to 7,
        "SPACE" to 8,
        "statement" to 9,
        "NL" to 10,
        "weekday" to 11,
        "weekday_monday" to 12,
        "weekday_tuesday" to 13,
        "weekday_wednesday" to 14,
        "weekday_thursday" to 15,
        "weekday_friday" to 16,
        "weekday_saturday" to 17,
        "weekday_sunday" to 18,
        "weekend" to 19,
        "weekend_friday" to 20,
        "weekend_saturday" to 21,
        "dateFormat" to 22,
        "inclusiveEndDates" to 23,
        "topAxis" to 24,
        "axisFormat" to 25,
        "tickInterval" to 26,
        "excludes" to 27,
        "includes" to 28,
        "todayMarker" to 29,
        "title" to 30,
        "acc_title" to 31,
        "acc_title_value" to 32,
        "acc_descr" to 33,
        "acc_descr_value" to 34,
        "acc_descr_multiline_value" to 35,
        "section" to 36,
        "clickStatement" to 37,
        "taskTxt" to 38,
        "taskData" to 39,
        "click" to 40,
        "callbackname" to 41,
        "callbackargs" to 42,
        "href" to 43,
        "clickStatementDebug" to 44,
        "\$accept" to 0,
        "\$end" to 1,
    )

    val terminalNames: Map<Int, String> = mapOf(
        2 to "error",
        4 to "gantt",
        6 to "EOF",
        8 to "SPACE",
        10 to "NL",
        12 to "weekday_monday",
        13 to "weekday_tuesday",
        14 to "weekday_wednesday",
        15 to "weekday_thursday",
        16 to "weekday_friday",
        17 to "weekday_saturday",
        18 to "weekday_sunday",
        20 to "weekend_friday",
        21 to "weekend_saturday",
        22 to "dateFormat",
        23 to "inclusiveEndDates",
        24 to "topAxis",
        25 to "axisFormat",
        26 to "tickInterval",
        27 to "excludes",
        28 to "includes",
        29 to "todayMarker",
        30 to "title",
        31 to "acc_title",
        32 to "acc_title_value",
        33 to "acc_descr",
        34 to "acc_descr_value",
        35 to "acc_descr_multiline_value",
        36 to "section",
        38 to "taskTxt",
        39 to "taskData",
        40 to "click",
        41 to "callbackname",
        42 to "callbackargs",
        43 to "href",
    )

    val productions: Array<GanttJisonProduction> = arrayOf(
        GanttJisonProduction(symbol = 0, length = 0),
        GanttJisonProduction(symbol = 3, length = 3),
        GanttJisonProduction(symbol = 5, length = 0),
        GanttJisonProduction(symbol = 5, length = 2),
        GanttJisonProduction(symbol = 7, length = 2),
        GanttJisonProduction(symbol = 7, length = 1),
        GanttJisonProduction(symbol = 7, length = 1),
        GanttJisonProduction(symbol = 7, length = 1),
        GanttJisonProduction(symbol = 11, length = 1),
        GanttJisonProduction(symbol = 11, length = 1),
        GanttJisonProduction(symbol = 11, length = 1),
        GanttJisonProduction(symbol = 11, length = 1),
        GanttJisonProduction(symbol = 11, length = 1),
        GanttJisonProduction(symbol = 11, length = 1),
        GanttJisonProduction(symbol = 11, length = 1),
        GanttJisonProduction(symbol = 19, length = 1),
        GanttJisonProduction(symbol = 19, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 2),
        GanttJisonProduction(symbol = 9, length = 2),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 1),
        GanttJisonProduction(symbol = 9, length = 2),
        GanttJisonProduction(symbol = 37, length = 2),
        GanttJisonProduction(symbol = 37, length = 3),
        GanttJisonProduction(symbol = 37, length = 3),
        GanttJisonProduction(symbol = 37, length = 4),
        GanttJisonProduction(symbol = 37, length = 3),
        GanttJisonProduction(symbol = 37, length = 4),
        GanttJisonProduction(symbol = 37, length = 2),
        GanttJisonProduction(symbol = 44, length = 2),
        GanttJisonProduction(symbol = 44, length = 3),
        GanttJisonProduction(symbol = 44, length = 3),
        GanttJisonProduction(symbol = 44, length = 4),
        GanttJisonProduction(symbol = 44, length = 3),
        GanttJisonProduction(symbol = 44, length = 4),
        GanttJisonProduction(symbol = 44, length = 2),
    )

    val states: Array<Map<Int, GanttJisonCell>> = buildList {
        addAll(stateChunk0())
        addAll(stateChunk1())
        addAll(stateChunk2())
    }.toTypedArray()

    private fun stateChunk0(): Array<Map<Int, GanttJisonCell>> = arrayOf(
        mapOf(
            3 to GanttJisonCell.Goto(1),
            4 to GanttJisonCell.Shift(2),
        ),
        mapOf(
            1 to GanttJisonCell.Accept,
        ),
        mapOf(
            5 to GanttJisonCell.Goto(3),
            6 to GanttJisonCell.Reduce(2),
            8 to GanttJisonCell.Reduce(2),
            10 to GanttJisonCell.Reduce(2),
            12 to GanttJisonCell.Reduce(2),
            13 to GanttJisonCell.Reduce(2),
            14 to GanttJisonCell.Reduce(2),
            15 to GanttJisonCell.Reduce(2),
            16 to GanttJisonCell.Reduce(2),
            17 to GanttJisonCell.Reduce(2),
            18 to GanttJisonCell.Reduce(2),
            20 to GanttJisonCell.Reduce(2),
            21 to GanttJisonCell.Reduce(2),
            22 to GanttJisonCell.Reduce(2),
            23 to GanttJisonCell.Reduce(2),
            24 to GanttJisonCell.Reduce(2),
            25 to GanttJisonCell.Reduce(2),
            26 to GanttJisonCell.Reduce(2),
            27 to GanttJisonCell.Reduce(2),
            28 to GanttJisonCell.Reduce(2),
            29 to GanttJisonCell.Reduce(2),
            30 to GanttJisonCell.Reduce(2),
            31 to GanttJisonCell.Reduce(2),
            33 to GanttJisonCell.Reduce(2),
            35 to GanttJisonCell.Reduce(2),
            36 to GanttJisonCell.Reduce(2),
            38 to GanttJisonCell.Reduce(2),
            40 to GanttJisonCell.Reduce(2),
        ),
        mapOf(
            6 to GanttJisonCell.Shift(4),
            7 to GanttJisonCell.Goto(5),
            8 to GanttJisonCell.Shift(6),
            9 to GanttJisonCell.Goto(7),
            10 to GanttJisonCell.Shift(8),
            11 to GanttJisonCell.Goto(17),
            12 to GanttJisonCell.Shift(26),
            13 to GanttJisonCell.Shift(27),
            14 to GanttJisonCell.Shift(28),
            15 to GanttJisonCell.Shift(29),
            16 to GanttJisonCell.Shift(30),
            17 to GanttJisonCell.Shift(31),
            18 to GanttJisonCell.Shift(32),
            19 to GanttJisonCell.Goto(18),
            20 to GanttJisonCell.Shift(33),
            21 to GanttJisonCell.Shift(34),
            22 to GanttJisonCell.Shift(9),
            23 to GanttJisonCell.Shift(10),
            24 to GanttJisonCell.Shift(11),
            25 to GanttJisonCell.Shift(12),
            26 to GanttJisonCell.Shift(13),
            27 to GanttJisonCell.Shift(14),
            28 to GanttJisonCell.Shift(15),
            29 to GanttJisonCell.Shift(16),
            30 to GanttJisonCell.Shift(19),
            31 to GanttJisonCell.Shift(20),
            33 to GanttJisonCell.Shift(21),
            35 to GanttJisonCell.Shift(22),
            36 to GanttJisonCell.Shift(23),
            37 to GanttJisonCell.Goto(24),
            38 to GanttJisonCell.Shift(25),
            40 to GanttJisonCell.Shift(35),
        ),
        mapOf(
            1 to GanttJisonCell.Reduce(1),
            6 to GanttJisonCell.Reduce(7),
            8 to GanttJisonCell.Reduce(7),
            10 to GanttJisonCell.Reduce(7),
            12 to GanttJisonCell.Reduce(7),
            13 to GanttJisonCell.Reduce(7),
            14 to GanttJisonCell.Reduce(7),
            15 to GanttJisonCell.Reduce(7),
            16 to GanttJisonCell.Reduce(7),
            17 to GanttJisonCell.Reduce(7),
            18 to GanttJisonCell.Reduce(7),
            20 to GanttJisonCell.Reduce(7),
            21 to GanttJisonCell.Reduce(7),
            22 to GanttJisonCell.Reduce(7),
            23 to GanttJisonCell.Reduce(7),
            24 to GanttJisonCell.Reduce(7),
            25 to GanttJisonCell.Reduce(7),
            26 to GanttJisonCell.Reduce(7),
            27 to GanttJisonCell.Reduce(7),
            28 to GanttJisonCell.Reduce(7),
            29 to GanttJisonCell.Reduce(7),
            30 to GanttJisonCell.Reduce(7),
            31 to GanttJisonCell.Reduce(7),
            33 to GanttJisonCell.Reduce(7),
            35 to GanttJisonCell.Reduce(7),
            36 to GanttJisonCell.Reduce(7),
            38 to GanttJisonCell.Reduce(7),
            40 to GanttJisonCell.Reduce(7),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(3),
            8 to GanttJisonCell.Reduce(3),
            10 to GanttJisonCell.Reduce(3),
            12 to GanttJisonCell.Reduce(3),
            13 to GanttJisonCell.Reduce(3),
            14 to GanttJisonCell.Reduce(3),
            15 to GanttJisonCell.Reduce(3),
            16 to GanttJisonCell.Reduce(3),
            17 to GanttJisonCell.Reduce(3),
            18 to GanttJisonCell.Reduce(3),
            20 to GanttJisonCell.Reduce(3),
            21 to GanttJisonCell.Reduce(3),
            22 to GanttJisonCell.Reduce(3),
            23 to GanttJisonCell.Reduce(3),
            24 to GanttJisonCell.Reduce(3),
            25 to GanttJisonCell.Reduce(3),
            26 to GanttJisonCell.Reduce(3),
            27 to GanttJisonCell.Reduce(3),
            28 to GanttJisonCell.Reduce(3),
            29 to GanttJisonCell.Reduce(3),
            30 to GanttJisonCell.Reduce(3),
            31 to GanttJisonCell.Reduce(3),
            33 to GanttJisonCell.Reduce(3),
            35 to GanttJisonCell.Reduce(3),
            36 to GanttJisonCell.Reduce(3),
            38 to GanttJisonCell.Reduce(3),
            40 to GanttJisonCell.Reduce(3),
        ),
        mapOf(
            9 to GanttJisonCell.Goto(36),
            11 to GanttJisonCell.Goto(17),
            12 to GanttJisonCell.Shift(26),
            13 to GanttJisonCell.Shift(27),
            14 to GanttJisonCell.Shift(28),
            15 to GanttJisonCell.Shift(29),
            16 to GanttJisonCell.Shift(30),
            17 to GanttJisonCell.Shift(31),
            18 to GanttJisonCell.Shift(32),
            19 to GanttJisonCell.Goto(18),
            20 to GanttJisonCell.Shift(33),
            21 to GanttJisonCell.Shift(34),
            22 to GanttJisonCell.Shift(9),
            23 to GanttJisonCell.Shift(10),
            24 to GanttJisonCell.Shift(11),
            25 to GanttJisonCell.Shift(12),
            26 to GanttJisonCell.Shift(13),
            27 to GanttJisonCell.Shift(14),
            28 to GanttJisonCell.Shift(15),
            29 to GanttJisonCell.Shift(16),
            30 to GanttJisonCell.Shift(19),
            31 to GanttJisonCell.Shift(20),
            33 to GanttJisonCell.Shift(21),
            35 to GanttJisonCell.Shift(22),
            36 to GanttJisonCell.Shift(23),
            37 to GanttJisonCell.Goto(24),
            38 to GanttJisonCell.Shift(25),
            40 to GanttJisonCell.Shift(35),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(5),
            8 to GanttJisonCell.Reduce(5),
            10 to GanttJisonCell.Reduce(5),
            12 to GanttJisonCell.Reduce(5),
            13 to GanttJisonCell.Reduce(5),
            14 to GanttJisonCell.Reduce(5),
            15 to GanttJisonCell.Reduce(5),
            16 to GanttJisonCell.Reduce(5),
            17 to GanttJisonCell.Reduce(5),
            18 to GanttJisonCell.Reduce(5),
            20 to GanttJisonCell.Reduce(5),
            21 to GanttJisonCell.Reduce(5),
            22 to GanttJisonCell.Reduce(5),
            23 to GanttJisonCell.Reduce(5),
            24 to GanttJisonCell.Reduce(5),
            25 to GanttJisonCell.Reduce(5),
            26 to GanttJisonCell.Reduce(5),
            27 to GanttJisonCell.Reduce(5),
            28 to GanttJisonCell.Reduce(5),
            29 to GanttJisonCell.Reduce(5),
            30 to GanttJisonCell.Reduce(5),
            31 to GanttJisonCell.Reduce(5),
            33 to GanttJisonCell.Reduce(5),
            35 to GanttJisonCell.Reduce(5),
            36 to GanttJisonCell.Reduce(5),
            38 to GanttJisonCell.Reduce(5),
            40 to GanttJisonCell.Reduce(5),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(6),
            8 to GanttJisonCell.Reduce(6),
            10 to GanttJisonCell.Reduce(6),
            12 to GanttJisonCell.Reduce(6),
            13 to GanttJisonCell.Reduce(6),
            14 to GanttJisonCell.Reduce(6),
            15 to GanttJisonCell.Reduce(6),
            16 to GanttJisonCell.Reduce(6),
            17 to GanttJisonCell.Reduce(6),
            18 to GanttJisonCell.Reduce(6),
            20 to GanttJisonCell.Reduce(6),
            21 to GanttJisonCell.Reduce(6),
            22 to GanttJisonCell.Reduce(6),
            23 to GanttJisonCell.Reduce(6),
            24 to GanttJisonCell.Reduce(6),
            25 to GanttJisonCell.Reduce(6),
            26 to GanttJisonCell.Reduce(6),
            27 to GanttJisonCell.Reduce(6),
            28 to GanttJisonCell.Reduce(6),
            29 to GanttJisonCell.Reduce(6),
            30 to GanttJisonCell.Reduce(6),
            31 to GanttJisonCell.Reduce(6),
            33 to GanttJisonCell.Reduce(6),
            35 to GanttJisonCell.Reduce(6),
            36 to GanttJisonCell.Reduce(6),
            38 to GanttJisonCell.Reduce(6),
            40 to GanttJisonCell.Reduce(6),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(17),
            8 to GanttJisonCell.Reduce(17),
            10 to GanttJisonCell.Reduce(17),
            12 to GanttJisonCell.Reduce(17),
            13 to GanttJisonCell.Reduce(17),
            14 to GanttJisonCell.Reduce(17),
            15 to GanttJisonCell.Reduce(17),
            16 to GanttJisonCell.Reduce(17),
            17 to GanttJisonCell.Reduce(17),
            18 to GanttJisonCell.Reduce(17),
            20 to GanttJisonCell.Reduce(17),
            21 to GanttJisonCell.Reduce(17),
            22 to GanttJisonCell.Reduce(17),
            23 to GanttJisonCell.Reduce(17),
            24 to GanttJisonCell.Reduce(17),
            25 to GanttJisonCell.Reduce(17),
            26 to GanttJisonCell.Reduce(17),
            27 to GanttJisonCell.Reduce(17),
            28 to GanttJisonCell.Reduce(17),
            29 to GanttJisonCell.Reduce(17),
            30 to GanttJisonCell.Reduce(17),
            31 to GanttJisonCell.Reduce(17),
            33 to GanttJisonCell.Reduce(17),
            35 to GanttJisonCell.Reduce(17),
            36 to GanttJisonCell.Reduce(17),
            38 to GanttJisonCell.Reduce(17),
            40 to GanttJisonCell.Reduce(17),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(18),
            8 to GanttJisonCell.Reduce(18),
            10 to GanttJisonCell.Reduce(18),
            12 to GanttJisonCell.Reduce(18),
            13 to GanttJisonCell.Reduce(18),
            14 to GanttJisonCell.Reduce(18),
            15 to GanttJisonCell.Reduce(18),
            16 to GanttJisonCell.Reduce(18),
            17 to GanttJisonCell.Reduce(18),
            18 to GanttJisonCell.Reduce(18),
            20 to GanttJisonCell.Reduce(18),
            21 to GanttJisonCell.Reduce(18),
            22 to GanttJisonCell.Reduce(18),
            23 to GanttJisonCell.Reduce(18),
            24 to GanttJisonCell.Reduce(18),
            25 to GanttJisonCell.Reduce(18),
            26 to GanttJisonCell.Reduce(18),
            27 to GanttJisonCell.Reduce(18),
            28 to GanttJisonCell.Reduce(18),
            29 to GanttJisonCell.Reduce(18),
            30 to GanttJisonCell.Reduce(18),
            31 to GanttJisonCell.Reduce(18),
            33 to GanttJisonCell.Reduce(18),
            35 to GanttJisonCell.Reduce(18),
            36 to GanttJisonCell.Reduce(18),
            38 to GanttJisonCell.Reduce(18),
            40 to GanttJisonCell.Reduce(18),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(19),
            8 to GanttJisonCell.Reduce(19),
            10 to GanttJisonCell.Reduce(19),
            12 to GanttJisonCell.Reduce(19),
            13 to GanttJisonCell.Reduce(19),
            14 to GanttJisonCell.Reduce(19),
            15 to GanttJisonCell.Reduce(19),
            16 to GanttJisonCell.Reduce(19),
            17 to GanttJisonCell.Reduce(19),
            18 to GanttJisonCell.Reduce(19),
            20 to GanttJisonCell.Reduce(19),
            21 to GanttJisonCell.Reduce(19),
            22 to GanttJisonCell.Reduce(19),
            23 to GanttJisonCell.Reduce(19),
            24 to GanttJisonCell.Reduce(19),
            25 to GanttJisonCell.Reduce(19),
            26 to GanttJisonCell.Reduce(19),
            27 to GanttJisonCell.Reduce(19),
            28 to GanttJisonCell.Reduce(19),
            29 to GanttJisonCell.Reduce(19),
            30 to GanttJisonCell.Reduce(19),
            31 to GanttJisonCell.Reduce(19),
            33 to GanttJisonCell.Reduce(19),
            35 to GanttJisonCell.Reduce(19),
            36 to GanttJisonCell.Reduce(19),
            38 to GanttJisonCell.Reduce(19),
            40 to GanttJisonCell.Reduce(19),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(20),
            8 to GanttJisonCell.Reduce(20),
            10 to GanttJisonCell.Reduce(20),
            12 to GanttJisonCell.Reduce(20),
            13 to GanttJisonCell.Reduce(20),
            14 to GanttJisonCell.Reduce(20),
            15 to GanttJisonCell.Reduce(20),
            16 to GanttJisonCell.Reduce(20),
            17 to GanttJisonCell.Reduce(20),
            18 to GanttJisonCell.Reduce(20),
            20 to GanttJisonCell.Reduce(20),
            21 to GanttJisonCell.Reduce(20),
            22 to GanttJisonCell.Reduce(20),
            23 to GanttJisonCell.Reduce(20),
            24 to GanttJisonCell.Reduce(20),
            25 to GanttJisonCell.Reduce(20),
            26 to GanttJisonCell.Reduce(20),
            27 to GanttJisonCell.Reduce(20),
            28 to GanttJisonCell.Reduce(20),
            29 to GanttJisonCell.Reduce(20),
            30 to GanttJisonCell.Reduce(20),
            31 to GanttJisonCell.Reduce(20),
            33 to GanttJisonCell.Reduce(20),
            35 to GanttJisonCell.Reduce(20),
            36 to GanttJisonCell.Reduce(20),
            38 to GanttJisonCell.Reduce(20),
            40 to GanttJisonCell.Reduce(20),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(21),
            8 to GanttJisonCell.Reduce(21),
            10 to GanttJisonCell.Reduce(21),
            12 to GanttJisonCell.Reduce(21),
            13 to GanttJisonCell.Reduce(21),
            14 to GanttJisonCell.Reduce(21),
            15 to GanttJisonCell.Reduce(21),
            16 to GanttJisonCell.Reduce(21),
            17 to GanttJisonCell.Reduce(21),
            18 to GanttJisonCell.Reduce(21),
            20 to GanttJisonCell.Reduce(21),
            21 to GanttJisonCell.Reduce(21),
            22 to GanttJisonCell.Reduce(21),
            23 to GanttJisonCell.Reduce(21),
            24 to GanttJisonCell.Reduce(21),
            25 to GanttJisonCell.Reduce(21),
            26 to GanttJisonCell.Reduce(21),
            27 to GanttJisonCell.Reduce(21),
            28 to GanttJisonCell.Reduce(21),
            29 to GanttJisonCell.Reduce(21),
            30 to GanttJisonCell.Reduce(21),
            31 to GanttJisonCell.Reduce(21),
            33 to GanttJisonCell.Reduce(21),
            35 to GanttJisonCell.Reduce(21),
            36 to GanttJisonCell.Reduce(21),
            38 to GanttJisonCell.Reduce(21),
            40 to GanttJisonCell.Reduce(21),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(22),
            8 to GanttJisonCell.Reduce(22),
            10 to GanttJisonCell.Reduce(22),
            12 to GanttJisonCell.Reduce(22),
            13 to GanttJisonCell.Reduce(22),
            14 to GanttJisonCell.Reduce(22),
            15 to GanttJisonCell.Reduce(22),
            16 to GanttJisonCell.Reduce(22),
            17 to GanttJisonCell.Reduce(22),
            18 to GanttJisonCell.Reduce(22),
            20 to GanttJisonCell.Reduce(22),
            21 to GanttJisonCell.Reduce(22),
            22 to GanttJisonCell.Reduce(22),
            23 to GanttJisonCell.Reduce(22),
            24 to GanttJisonCell.Reduce(22),
            25 to GanttJisonCell.Reduce(22),
            26 to GanttJisonCell.Reduce(22),
            27 to GanttJisonCell.Reduce(22),
            28 to GanttJisonCell.Reduce(22),
            29 to GanttJisonCell.Reduce(22),
            30 to GanttJisonCell.Reduce(22),
            31 to GanttJisonCell.Reduce(22),
            33 to GanttJisonCell.Reduce(22),
            35 to GanttJisonCell.Reduce(22),
            36 to GanttJisonCell.Reduce(22),
            38 to GanttJisonCell.Reduce(22),
            40 to GanttJisonCell.Reduce(22),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(23),
            8 to GanttJisonCell.Reduce(23),
            10 to GanttJisonCell.Reduce(23),
            12 to GanttJisonCell.Reduce(23),
            13 to GanttJisonCell.Reduce(23),
            14 to GanttJisonCell.Reduce(23),
            15 to GanttJisonCell.Reduce(23),
            16 to GanttJisonCell.Reduce(23),
            17 to GanttJisonCell.Reduce(23),
            18 to GanttJisonCell.Reduce(23),
            20 to GanttJisonCell.Reduce(23),
            21 to GanttJisonCell.Reduce(23),
            22 to GanttJisonCell.Reduce(23),
            23 to GanttJisonCell.Reduce(23),
            24 to GanttJisonCell.Reduce(23),
            25 to GanttJisonCell.Reduce(23),
            26 to GanttJisonCell.Reduce(23),
            27 to GanttJisonCell.Reduce(23),
            28 to GanttJisonCell.Reduce(23),
            29 to GanttJisonCell.Reduce(23),
            30 to GanttJisonCell.Reduce(23),
            31 to GanttJisonCell.Reduce(23),
            33 to GanttJisonCell.Reduce(23),
            35 to GanttJisonCell.Reduce(23),
            36 to GanttJisonCell.Reduce(23),
            38 to GanttJisonCell.Reduce(23),
            40 to GanttJisonCell.Reduce(23),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(24),
            8 to GanttJisonCell.Reduce(24),
            10 to GanttJisonCell.Reduce(24),
            12 to GanttJisonCell.Reduce(24),
            13 to GanttJisonCell.Reduce(24),
            14 to GanttJisonCell.Reduce(24),
            15 to GanttJisonCell.Reduce(24),
            16 to GanttJisonCell.Reduce(24),
            17 to GanttJisonCell.Reduce(24),
            18 to GanttJisonCell.Reduce(24),
            20 to GanttJisonCell.Reduce(24),
            21 to GanttJisonCell.Reduce(24),
            22 to GanttJisonCell.Reduce(24),
            23 to GanttJisonCell.Reduce(24),
            24 to GanttJisonCell.Reduce(24),
            25 to GanttJisonCell.Reduce(24),
            26 to GanttJisonCell.Reduce(24),
            27 to GanttJisonCell.Reduce(24),
            28 to GanttJisonCell.Reduce(24),
            29 to GanttJisonCell.Reduce(24),
            30 to GanttJisonCell.Reduce(24),
            31 to GanttJisonCell.Reduce(24),
            33 to GanttJisonCell.Reduce(24),
            35 to GanttJisonCell.Reduce(24),
            36 to GanttJisonCell.Reduce(24),
            38 to GanttJisonCell.Reduce(24),
            40 to GanttJisonCell.Reduce(24),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(25),
            8 to GanttJisonCell.Reduce(25),
            10 to GanttJisonCell.Reduce(25),
            12 to GanttJisonCell.Reduce(25),
            13 to GanttJisonCell.Reduce(25),
            14 to GanttJisonCell.Reduce(25),
            15 to GanttJisonCell.Reduce(25),
            16 to GanttJisonCell.Reduce(25),
            17 to GanttJisonCell.Reduce(25),
            18 to GanttJisonCell.Reduce(25),
            20 to GanttJisonCell.Reduce(25),
            21 to GanttJisonCell.Reduce(25),
            22 to GanttJisonCell.Reduce(25),
            23 to GanttJisonCell.Reduce(25),
            24 to GanttJisonCell.Reduce(25),
            25 to GanttJisonCell.Reduce(25),
            26 to GanttJisonCell.Reduce(25),
            27 to GanttJisonCell.Reduce(25),
            28 to GanttJisonCell.Reduce(25),
            29 to GanttJisonCell.Reduce(25),
            30 to GanttJisonCell.Reduce(25),
            31 to GanttJisonCell.Reduce(25),
            33 to GanttJisonCell.Reduce(25),
            35 to GanttJisonCell.Reduce(25),
            36 to GanttJisonCell.Reduce(25),
            38 to GanttJisonCell.Reduce(25),
            40 to GanttJisonCell.Reduce(25),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(26),
            8 to GanttJisonCell.Reduce(26),
            10 to GanttJisonCell.Reduce(26),
            12 to GanttJisonCell.Reduce(26),
            13 to GanttJisonCell.Reduce(26),
            14 to GanttJisonCell.Reduce(26),
            15 to GanttJisonCell.Reduce(26),
            16 to GanttJisonCell.Reduce(26),
            17 to GanttJisonCell.Reduce(26),
            18 to GanttJisonCell.Reduce(26),
            20 to GanttJisonCell.Reduce(26),
            21 to GanttJisonCell.Reduce(26),
            22 to GanttJisonCell.Reduce(26),
            23 to GanttJisonCell.Reduce(26),
            24 to GanttJisonCell.Reduce(26),
            25 to GanttJisonCell.Reduce(26),
            26 to GanttJisonCell.Reduce(26),
            27 to GanttJisonCell.Reduce(26),
            28 to GanttJisonCell.Reduce(26),
            29 to GanttJisonCell.Reduce(26),
            30 to GanttJisonCell.Reduce(26),
            31 to GanttJisonCell.Reduce(26),
            33 to GanttJisonCell.Reduce(26),
            35 to GanttJisonCell.Reduce(26),
            36 to GanttJisonCell.Reduce(26),
            38 to GanttJisonCell.Reduce(26),
            40 to GanttJisonCell.Reduce(26),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(27),
            8 to GanttJisonCell.Reduce(27),
            10 to GanttJisonCell.Reduce(27),
            12 to GanttJisonCell.Reduce(27),
            13 to GanttJisonCell.Reduce(27),
            14 to GanttJisonCell.Reduce(27),
            15 to GanttJisonCell.Reduce(27),
            16 to GanttJisonCell.Reduce(27),
            17 to GanttJisonCell.Reduce(27),
            18 to GanttJisonCell.Reduce(27),
            20 to GanttJisonCell.Reduce(27),
            21 to GanttJisonCell.Reduce(27),
            22 to GanttJisonCell.Reduce(27),
            23 to GanttJisonCell.Reduce(27),
            24 to GanttJisonCell.Reduce(27),
            25 to GanttJisonCell.Reduce(27),
            26 to GanttJisonCell.Reduce(27),
            27 to GanttJisonCell.Reduce(27),
            28 to GanttJisonCell.Reduce(27),
            29 to GanttJisonCell.Reduce(27),
            30 to GanttJisonCell.Reduce(27),
            31 to GanttJisonCell.Reduce(27),
            33 to GanttJisonCell.Reduce(27),
            35 to GanttJisonCell.Reduce(27),
            36 to GanttJisonCell.Reduce(27),
            38 to GanttJisonCell.Reduce(27),
            40 to GanttJisonCell.Reduce(27),
        ),
    )

    private fun stateChunk1(): Array<Map<Int, GanttJisonCell>> = arrayOf(
        mapOf(
            32 to GanttJisonCell.Shift(37),
        ),
        mapOf(
            34 to GanttJisonCell.Shift(38),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(30),
            8 to GanttJisonCell.Reduce(30),
            10 to GanttJisonCell.Reduce(30),
            12 to GanttJisonCell.Reduce(30),
            13 to GanttJisonCell.Reduce(30),
            14 to GanttJisonCell.Reduce(30),
            15 to GanttJisonCell.Reduce(30),
            16 to GanttJisonCell.Reduce(30),
            17 to GanttJisonCell.Reduce(30),
            18 to GanttJisonCell.Reduce(30),
            20 to GanttJisonCell.Reduce(30),
            21 to GanttJisonCell.Reduce(30),
            22 to GanttJisonCell.Reduce(30),
            23 to GanttJisonCell.Reduce(30),
            24 to GanttJisonCell.Reduce(30),
            25 to GanttJisonCell.Reduce(30),
            26 to GanttJisonCell.Reduce(30),
            27 to GanttJisonCell.Reduce(30),
            28 to GanttJisonCell.Reduce(30),
            29 to GanttJisonCell.Reduce(30),
            30 to GanttJisonCell.Reduce(30),
            31 to GanttJisonCell.Reduce(30),
            33 to GanttJisonCell.Reduce(30),
            35 to GanttJisonCell.Reduce(30),
            36 to GanttJisonCell.Reduce(30),
            38 to GanttJisonCell.Reduce(30),
            40 to GanttJisonCell.Reduce(30),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(31),
            8 to GanttJisonCell.Reduce(31),
            10 to GanttJisonCell.Reduce(31),
            12 to GanttJisonCell.Reduce(31),
            13 to GanttJisonCell.Reduce(31),
            14 to GanttJisonCell.Reduce(31),
            15 to GanttJisonCell.Reduce(31),
            16 to GanttJisonCell.Reduce(31),
            17 to GanttJisonCell.Reduce(31),
            18 to GanttJisonCell.Reduce(31),
            20 to GanttJisonCell.Reduce(31),
            21 to GanttJisonCell.Reduce(31),
            22 to GanttJisonCell.Reduce(31),
            23 to GanttJisonCell.Reduce(31),
            24 to GanttJisonCell.Reduce(31),
            25 to GanttJisonCell.Reduce(31),
            26 to GanttJisonCell.Reduce(31),
            27 to GanttJisonCell.Reduce(31),
            28 to GanttJisonCell.Reduce(31),
            29 to GanttJisonCell.Reduce(31),
            30 to GanttJisonCell.Reduce(31),
            31 to GanttJisonCell.Reduce(31),
            33 to GanttJisonCell.Reduce(31),
            35 to GanttJisonCell.Reduce(31),
            36 to GanttJisonCell.Reduce(31),
            38 to GanttJisonCell.Reduce(31),
            40 to GanttJisonCell.Reduce(31),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(32),
            8 to GanttJisonCell.Reduce(32),
            10 to GanttJisonCell.Reduce(32),
            12 to GanttJisonCell.Reduce(32),
            13 to GanttJisonCell.Reduce(32),
            14 to GanttJisonCell.Reduce(32),
            15 to GanttJisonCell.Reduce(32),
            16 to GanttJisonCell.Reduce(32),
            17 to GanttJisonCell.Reduce(32),
            18 to GanttJisonCell.Reduce(32),
            20 to GanttJisonCell.Reduce(32),
            21 to GanttJisonCell.Reduce(32),
            22 to GanttJisonCell.Reduce(32),
            23 to GanttJisonCell.Reduce(32),
            24 to GanttJisonCell.Reduce(32),
            25 to GanttJisonCell.Reduce(32),
            26 to GanttJisonCell.Reduce(32),
            27 to GanttJisonCell.Reduce(32),
            28 to GanttJisonCell.Reduce(32),
            29 to GanttJisonCell.Reduce(32),
            30 to GanttJisonCell.Reduce(32),
            31 to GanttJisonCell.Reduce(32),
            33 to GanttJisonCell.Reduce(32),
            35 to GanttJisonCell.Reduce(32),
            36 to GanttJisonCell.Reduce(32),
            38 to GanttJisonCell.Reduce(32),
            40 to GanttJisonCell.Reduce(32),
        ),
        mapOf(
            39 to GanttJisonCell.Shift(39),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(8),
            8 to GanttJisonCell.Reduce(8),
            10 to GanttJisonCell.Reduce(8),
            12 to GanttJisonCell.Reduce(8),
            13 to GanttJisonCell.Reduce(8),
            14 to GanttJisonCell.Reduce(8),
            15 to GanttJisonCell.Reduce(8),
            16 to GanttJisonCell.Reduce(8),
            17 to GanttJisonCell.Reduce(8),
            18 to GanttJisonCell.Reduce(8),
            20 to GanttJisonCell.Reduce(8),
            21 to GanttJisonCell.Reduce(8),
            22 to GanttJisonCell.Reduce(8),
            23 to GanttJisonCell.Reduce(8),
            24 to GanttJisonCell.Reduce(8),
            25 to GanttJisonCell.Reduce(8),
            26 to GanttJisonCell.Reduce(8),
            27 to GanttJisonCell.Reduce(8),
            28 to GanttJisonCell.Reduce(8),
            29 to GanttJisonCell.Reduce(8),
            30 to GanttJisonCell.Reduce(8),
            31 to GanttJisonCell.Reduce(8),
            33 to GanttJisonCell.Reduce(8),
            35 to GanttJisonCell.Reduce(8),
            36 to GanttJisonCell.Reduce(8),
            38 to GanttJisonCell.Reduce(8),
            40 to GanttJisonCell.Reduce(8),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(9),
            8 to GanttJisonCell.Reduce(9),
            10 to GanttJisonCell.Reduce(9),
            12 to GanttJisonCell.Reduce(9),
            13 to GanttJisonCell.Reduce(9),
            14 to GanttJisonCell.Reduce(9),
            15 to GanttJisonCell.Reduce(9),
            16 to GanttJisonCell.Reduce(9),
            17 to GanttJisonCell.Reduce(9),
            18 to GanttJisonCell.Reduce(9),
            20 to GanttJisonCell.Reduce(9),
            21 to GanttJisonCell.Reduce(9),
            22 to GanttJisonCell.Reduce(9),
            23 to GanttJisonCell.Reduce(9),
            24 to GanttJisonCell.Reduce(9),
            25 to GanttJisonCell.Reduce(9),
            26 to GanttJisonCell.Reduce(9),
            27 to GanttJisonCell.Reduce(9),
            28 to GanttJisonCell.Reduce(9),
            29 to GanttJisonCell.Reduce(9),
            30 to GanttJisonCell.Reduce(9),
            31 to GanttJisonCell.Reduce(9),
            33 to GanttJisonCell.Reduce(9),
            35 to GanttJisonCell.Reduce(9),
            36 to GanttJisonCell.Reduce(9),
            38 to GanttJisonCell.Reduce(9),
            40 to GanttJisonCell.Reduce(9),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(10),
            8 to GanttJisonCell.Reduce(10),
            10 to GanttJisonCell.Reduce(10),
            12 to GanttJisonCell.Reduce(10),
            13 to GanttJisonCell.Reduce(10),
            14 to GanttJisonCell.Reduce(10),
            15 to GanttJisonCell.Reduce(10),
            16 to GanttJisonCell.Reduce(10),
            17 to GanttJisonCell.Reduce(10),
            18 to GanttJisonCell.Reduce(10),
            20 to GanttJisonCell.Reduce(10),
            21 to GanttJisonCell.Reduce(10),
            22 to GanttJisonCell.Reduce(10),
            23 to GanttJisonCell.Reduce(10),
            24 to GanttJisonCell.Reduce(10),
            25 to GanttJisonCell.Reduce(10),
            26 to GanttJisonCell.Reduce(10),
            27 to GanttJisonCell.Reduce(10),
            28 to GanttJisonCell.Reduce(10),
            29 to GanttJisonCell.Reduce(10),
            30 to GanttJisonCell.Reduce(10),
            31 to GanttJisonCell.Reduce(10),
            33 to GanttJisonCell.Reduce(10),
            35 to GanttJisonCell.Reduce(10),
            36 to GanttJisonCell.Reduce(10),
            38 to GanttJisonCell.Reduce(10),
            40 to GanttJisonCell.Reduce(10),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(11),
            8 to GanttJisonCell.Reduce(11),
            10 to GanttJisonCell.Reduce(11),
            12 to GanttJisonCell.Reduce(11),
            13 to GanttJisonCell.Reduce(11),
            14 to GanttJisonCell.Reduce(11),
            15 to GanttJisonCell.Reduce(11),
            16 to GanttJisonCell.Reduce(11),
            17 to GanttJisonCell.Reduce(11),
            18 to GanttJisonCell.Reduce(11),
            20 to GanttJisonCell.Reduce(11),
            21 to GanttJisonCell.Reduce(11),
            22 to GanttJisonCell.Reduce(11),
            23 to GanttJisonCell.Reduce(11),
            24 to GanttJisonCell.Reduce(11),
            25 to GanttJisonCell.Reduce(11),
            26 to GanttJisonCell.Reduce(11),
            27 to GanttJisonCell.Reduce(11),
            28 to GanttJisonCell.Reduce(11),
            29 to GanttJisonCell.Reduce(11),
            30 to GanttJisonCell.Reduce(11),
            31 to GanttJisonCell.Reduce(11),
            33 to GanttJisonCell.Reduce(11),
            35 to GanttJisonCell.Reduce(11),
            36 to GanttJisonCell.Reduce(11),
            38 to GanttJisonCell.Reduce(11),
            40 to GanttJisonCell.Reduce(11),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(12),
            8 to GanttJisonCell.Reduce(12),
            10 to GanttJisonCell.Reduce(12),
            12 to GanttJisonCell.Reduce(12),
            13 to GanttJisonCell.Reduce(12),
            14 to GanttJisonCell.Reduce(12),
            15 to GanttJisonCell.Reduce(12),
            16 to GanttJisonCell.Reduce(12),
            17 to GanttJisonCell.Reduce(12),
            18 to GanttJisonCell.Reduce(12),
            20 to GanttJisonCell.Reduce(12),
            21 to GanttJisonCell.Reduce(12),
            22 to GanttJisonCell.Reduce(12),
            23 to GanttJisonCell.Reduce(12),
            24 to GanttJisonCell.Reduce(12),
            25 to GanttJisonCell.Reduce(12),
            26 to GanttJisonCell.Reduce(12),
            27 to GanttJisonCell.Reduce(12),
            28 to GanttJisonCell.Reduce(12),
            29 to GanttJisonCell.Reduce(12),
            30 to GanttJisonCell.Reduce(12),
            31 to GanttJisonCell.Reduce(12),
            33 to GanttJisonCell.Reduce(12),
            35 to GanttJisonCell.Reduce(12),
            36 to GanttJisonCell.Reduce(12),
            38 to GanttJisonCell.Reduce(12),
            40 to GanttJisonCell.Reduce(12),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(13),
            8 to GanttJisonCell.Reduce(13),
            10 to GanttJisonCell.Reduce(13),
            12 to GanttJisonCell.Reduce(13),
            13 to GanttJisonCell.Reduce(13),
            14 to GanttJisonCell.Reduce(13),
            15 to GanttJisonCell.Reduce(13),
            16 to GanttJisonCell.Reduce(13),
            17 to GanttJisonCell.Reduce(13),
            18 to GanttJisonCell.Reduce(13),
            20 to GanttJisonCell.Reduce(13),
            21 to GanttJisonCell.Reduce(13),
            22 to GanttJisonCell.Reduce(13),
            23 to GanttJisonCell.Reduce(13),
            24 to GanttJisonCell.Reduce(13),
            25 to GanttJisonCell.Reduce(13),
            26 to GanttJisonCell.Reduce(13),
            27 to GanttJisonCell.Reduce(13),
            28 to GanttJisonCell.Reduce(13),
            29 to GanttJisonCell.Reduce(13),
            30 to GanttJisonCell.Reduce(13),
            31 to GanttJisonCell.Reduce(13),
            33 to GanttJisonCell.Reduce(13),
            35 to GanttJisonCell.Reduce(13),
            36 to GanttJisonCell.Reduce(13),
            38 to GanttJisonCell.Reduce(13),
            40 to GanttJisonCell.Reduce(13),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(14),
            8 to GanttJisonCell.Reduce(14),
            10 to GanttJisonCell.Reduce(14),
            12 to GanttJisonCell.Reduce(14),
            13 to GanttJisonCell.Reduce(14),
            14 to GanttJisonCell.Reduce(14),
            15 to GanttJisonCell.Reduce(14),
            16 to GanttJisonCell.Reduce(14),
            17 to GanttJisonCell.Reduce(14),
            18 to GanttJisonCell.Reduce(14),
            20 to GanttJisonCell.Reduce(14),
            21 to GanttJisonCell.Reduce(14),
            22 to GanttJisonCell.Reduce(14),
            23 to GanttJisonCell.Reduce(14),
            24 to GanttJisonCell.Reduce(14),
            25 to GanttJisonCell.Reduce(14),
            26 to GanttJisonCell.Reduce(14),
            27 to GanttJisonCell.Reduce(14),
            28 to GanttJisonCell.Reduce(14),
            29 to GanttJisonCell.Reduce(14),
            30 to GanttJisonCell.Reduce(14),
            31 to GanttJisonCell.Reduce(14),
            33 to GanttJisonCell.Reduce(14),
            35 to GanttJisonCell.Reduce(14),
            36 to GanttJisonCell.Reduce(14),
            38 to GanttJisonCell.Reduce(14),
            40 to GanttJisonCell.Reduce(14),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(15),
            8 to GanttJisonCell.Reduce(15),
            10 to GanttJisonCell.Reduce(15),
            12 to GanttJisonCell.Reduce(15),
            13 to GanttJisonCell.Reduce(15),
            14 to GanttJisonCell.Reduce(15),
            15 to GanttJisonCell.Reduce(15),
            16 to GanttJisonCell.Reduce(15),
            17 to GanttJisonCell.Reduce(15),
            18 to GanttJisonCell.Reduce(15),
            20 to GanttJisonCell.Reduce(15),
            21 to GanttJisonCell.Reduce(15),
            22 to GanttJisonCell.Reduce(15),
            23 to GanttJisonCell.Reduce(15),
            24 to GanttJisonCell.Reduce(15),
            25 to GanttJisonCell.Reduce(15),
            26 to GanttJisonCell.Reduce(15),
            27 to GanttJisonCell.Reduce(15),
            28 to GanttJisonCell.Reduce(15),
            29 to GanttJisonCell.Reduce(15),
            30 to GanttJisonCell.Reduce(15),
            31 to GanttJisonCell.Reduce(15),
            33 to GanttJisonCell.Reduce(15),
            35 to GanttJisonCell.Reduce(15),
            36 to GanttJisonCell.Reduce(15),
            38 to GanttJisonCell.Reduce(15),
            40 to GanttJisonCell.Reduce(15),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(16),
            8 to GanttJisonCell.Reduce(16),
            10 to GanttJisonCell.Reduce(16),
            12 to GanttJisonCell.Reduce(16),
            13 to GanttJisonCell.Reduce(16),
            14 to GanttJisonCell.Reduce(16),
            15 to GanttJisonCell.Reduce(16),
            16 to GanttJisonCell.Reduce(16),
            17 to GanttJisonCell.Reduce(16),
            18 to GanttJisonCell.Reduce(16),
            20 to GanttJisonCell.Reduce(16),
            21 to GanttJisonCell.Reduce(16),
            22 to GanttJisonCell.Reduce(16),
            23 to GanttJisonCell.Reduce(16),
            24 to GanttJisonCell.Reduce(16),
            25 to GanttJisonCell.Reduce(16),
            26 to GanttJisonCell.Reduce(16),
            27 to GanttJisonCell.Reduce(16),
            28 to GanttJisonCell.Reduce(16),
            29 to GanttJisonCell.Reduce(16),
            30 to GanttJisonCell.Reduce(16),
            31 to GanttJisonCell.Reduce(16),
            33 to GanttJisonCell.Reduce(16),
            35 to GanttJisonCell.Reduce(16),
            36 to GanttJisonCell.Reduce(16),
            38 to GanttJisonCell.Reduce(16),
            40 to GanttJisonCell.Reduce(16),
        ),
        mapOf(
            41 to GanttJisonCell.Shift(40),
            43 to GanttJisonCell.Shift(41),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(4),
            8 to GanttJisonCell.Reduce(4),
            10 to GanttJisonCell.Reduce(4),
            12 to GanttJisonCell.Reduce(4),
            13 to GanttJisonCell.Reduce(4),
            14 to GanttJisonCell.Reduce(4),
            15 to GanttJisonCell.Reduce(4),
            16 to GanttJisonCell.Reduce(4),
            17 to GanttJisonCell.Reduce(4),
            18 to GanttJisonCell.Reduce(4),
            20 to GanttJisonCell.Reduce(4),
            21 to GanttJisonCell.Reduce(4),
            22 to GanttJisonCell.Reduce(4),
            23 to GanttJisonCell.Reduce(4),
            24 to GanttJisonCell.Reduce(4),
            25 to GanttJisonCell.Reduce(4),
            26 to GanttJisonCell.Reduce(4),
            27 to GanttJisonCell.Reduce(4),
            28 to GanttJisonCell.Reduce(4),
            29 to GanttJisonCell.Reduce(4),
            30 to GanttJisonCell.Reduce(4),
            31 to GanttJisonCell.Reduce(4),
            33 to GanttJisonCell.Reduce(4),
            35 to GanttJisonCell.Reduce(4),
            36 to GanttJisonCell.Reduce(4),
            38 to GanttJisonCell.Reduce(4),
            40 to GanttJisonCell.Reduce(4),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(28),
            8 to GanttJisonCell.Reduce(28),
            10 to GanttJisonCell.Reduce(28),
            12 to GanttJisonCell.Reduce(28),
            13 to GanttJisonCell.Reduce(28),
            14 to GanttJisonCell.Reduce(28),
            15 to GanttJisonCell.Reduce(28),
            16 to GanttJisonCell.Reduce(28),
            17 to GanttJisonCell.Reduce(28),
            18 to GanttJisonCell.Reduce(28),
            20 to GanttJisonCell.Reduce(28),
            21 to GanttJisonCell.Reduce(28),
            22 to GanttJisonCell.Reduce(28),
            23 to GanttJisonCell.Reduce(28),
            24 to GanttJisonCell.Reduce(28),
            25 to GanttJisonCell.Reduce(28),
            26 to GanttJisonCell.Reduce(28),
            27 to GanttJisonCell.Reduce(28),
            28 to GanttJisonCell.Reduce(28),
            29 to GanttJisonCell.Reduce(28),
            30 to GanttJisonCell.Reduce(28),
            31 to GanttJisonCell.Reduce(28),
            33 to GanttJisonCell.Reduce(28),
            35 to GanttJisonCell.Reduce(28),
            36 to GanttJisonCell.Reduce(28),
            38 to GanttJisonCell.Reduce(28),
            40 to GanttJisonCell.Reduce(28),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(29),
            8 to GanttJisonCell.Reduce(29),
            10 to GanttJisonCell.Reduce(29),
            12 to GanttJisonCell.Reduce(29),
            13 to GanttJisonCell.Reduce(29),
            14 to GanttJisonCell.Reduce(29),
            15 to GanttJisonCell.Reduce(29),
            16 to GanttJisonCell.Reduce(29),
            17 to GanttJisonCell.Reduce(29),
            18 to GanttJisonCell.Reduce(29),
            20 to GanttJisonCell.Reduce(29),
            21 to GanttJisonCell.Reduce(29),
            22 to GanttJisonCell.Reduce(29),
            23 to GanttJisonCell.Reduce(29),
            24 to GanttJisonCell.Reduce(29),
            25 to GanttJisonCell.Reduce(29),
            26 to GanttJisonCell.Reduce(29),
            27 to GanttJisonCell.Reduce(29),
            28 to GanttJisonCell.Reduce(29),
            29 to GanttJisonCell.Reduce(29),
            30 to GanttJisonCell.Reduce(29),
            31 to GanttJisonCell.Reduce(29),
            33 to GanttJisonCell.Reduce(29),
            35 to GanttJisonCell.Reduce(29),
            36 to GanttJisonCell.Reduce(29),
            38 to GanttJisonCell.Reduce(29),
            40 to GanttJisonCell.Reduce(29),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(33),
            8 to GanttJisonCell.Reduce(33),
            10 to GanttJisonCell.Reduce(33),
            12 to GanttJisonCell.Reduce(33),
            13 to GanttJisonCell.Reduce(33),
            14 to GanttJisonCell.Reduce(33),
            15 to GanttJisonCell.Reduce(33),
            16 to GanttJisonCell.Reduce(33),
            17 to GanttJisonCell.Reduce(33),
            18 to GanttJisonCell.Reduce(33),
            20 to GanttJisonCell.Reduce(33),
            21 to GanttJisonCell.Reduce(33),
            22 to GanttJisonCell.Reduce(33),
            23 to GanttJisonCell.Reduce(33),
            24 to GanttJisonCell.Reduce(33),
            25 to GanttJisonCell.Reduce(33),
            26 to GanttJisonCell.Reduce(33),
            27 to GanttJisonCell.Reduce(33),
            28 to GanttJisonCell.Reduce(33),
            29 to GanttJisonCell.Reduce(33),
            30 to GanttJisonCell.Reduce(33),
            31 to GanttJisonCell.Reduce(33),
            33 to GanttJisonCell.Reduce(33),
            35 to GanttJisonCell.Reduce(33),
            36 to GanttJisonCell.Reduce(33),
            38 to GanttJisonCell.Reduce(33),
            40 to GanttJisonCell.Reduce(33),
        ),
    )

    private fun stateChunk2(): Array<Map<Int, GanttJisonCell>> = arrayOf(
        mapOf(
            6 to GanttJisonCell.Reduce(34),
            8 to GanttJisonCell.Reduce(34),
            10 to GanttJisonCell.Reduce(34),
            12 to GanttJisonCell.Reduce(34),
            13 to GanttJisonCell.Reduce(34),
            14 to GanttJisonCell.Reduce(34),
            15 to GanttJisonCell.Reduce(34),
            16 to GanttJisonCell.Reduce(34),
            17 to GanttJisonCell.Reduce(34),
            18 to GanttJisonCell.Reduce(34),
            20 to GanttJisonCell.Reduce(34),
            21 to GanttJisonCell.Reduce(34),
            22 to GanttJisonCell.Reduce(34),
            23 to GanttJisonCell.Reduce(34),
            24 to GanttJisonCell.Reduce(34),
            25 to GanttJisonCell.Reduce(34),
            26 to GanttJisonCell.Reduce(34),
            27 to GanttJisonCell.Reduce(34),
            28 to GanttJisonCell.Reduce(34),
            29 to GanttJisonCell.Reduce(34),
            30 to GanttJisonCell.Reduce(34),
            31 to GanttJisonCell.Reduce(34),
            33 to GanttJisonCell.Reduce(34),
            35 to GanttJisonCell.Reduce(34),
            36 to GanttJisonCell.Reduce(34),
            38 to GanttJisonCell.Reduce(34),
            40 to GanttJisonCell.Reduce(34),
            42 to GanttJisonCell.Shift(42),
            43 to GanttJisonCell.Shift(43),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(40),
            8 to GanttJisonCell.Reduce(40),
            10 to GanttJisonCell.Reduce(40),
            12 to GanttJisonCell.Reduce(40),
            13 to GanttJisonCell.Reduce(40),
            14 to GanttJisonCell.Reduce(40),
            15 to GanttJisonCell.Reduce(40),
            16 to GanttJisonCell.Reduce(40),
            17 to GanttJisonCell.Reduce(40),
            18 to GanttJisonCell.Reduce(40),
            20 to GanttJisonCell.Reduce(40),
            21 to GanttJisonCell.Reduce(40),
            22 to GanttJisonCell.Reduce(40),
            23 to GanttJisonCell.Reduce(40),
            24 to GanttJisonCell.Reduce(40),
            25 to GanttJisonCell.Reduce(40),
            26 to GanttJisonCell.Reduce(40),
            27 to GanttJisonCell.Reduce(40),
            28 to GanttJisonCell.Reduce(40),
            29 to GanttJisonCell.Reduce(40),
            30 to GanttJisonCell.Reduce(40),
            31 to GanttJisonCell.Reduce(40),
            33 to GanttJisonCell.Reduce(40),
            35 to GanttJisonCell.Reduce(40),
            36 to GanttJisonCell.Reduce(40),
            38 to GanttJisonCell.Reduce(40),
            40 to GanttJisonCell.Reduce(40),
            41 to GanttJisonCell.Shift(44),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(35),
            8 to GanttJisonCell.Reduce(35),
            10 to GanttJisonCell.Reduce(35),
            12 to GanttJisonCell.Reduce(35),
            13 to GanttJisonCell.Reduce(35),
            14 to GanttJisonCell.Reduce(35),
            15 to GanttJisonCell.Reduce(35),
            16 to GanttJisonCell.Reduce(35),
            17 to GanttJisonCell.Reduce(35),
            18 to GanttJisonCell.Reduce(35),
            20 to GanttJisonCell.Reduce(35),
            21 to GanttJisonCell.Reduce(35),
            22 to GanttJisonCell.Reduce(35),
            23 to GanttJisonCell.Reduce(35),
            24 to GanttJisonCell.Reduce(35),
            25 to GanttJisonCell.Reduce(35),
            26 to GanttJisonCell.Reduce(35),
            27 to GanttJisonCell.Reduce(35),
            28 to GanttJisonCell.Reduce(35),
            29 to GanttJisonCell.Reduce(35),
            30 to GanttJisonCell.Reduce(35),
            31 to GanttJisonCell.Reduce(35),
            33 to GanttJisonCell.Reduce(35),
            35 to GanttJisonCell.Reduce(35),
            36 to GanttJisonCell.Reduce(35),
            38 to GanttJisonCell.Reduce(35),
            40 to GanttJisonCell.Reduce(35),
            43 to GanttJisonCell.Shift(45),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(36),
            8 to GanttJisonCell.Reduce(36),
            10 to GanttJisonCell.Reduce(36),
            12 to GanttJisonCell.Reduce(36),
            13 to GanttJisonCell.Reduce(36),
            14 to GanttJisonCell.Reduce(36),
            15 to GanttJisonCell.Reduce(36),
            16 to GanttJisonCell.Reduce(36),
            17 to GanttJisonCell.Reduce(36),
            18 to GanttJisonCell.Reduce(36),
            20 to GanttJisonCell.Reduce(36),
            21 to GanttJisonCell.Reduce(36),
            22 to GanttJisonCell.Reduce(36),
            23 to GanttJisonCell.Reduce(36),
            24 to GanttJisonCell.Reduce(36),
            25 to GanttJisonCell.Reduce(36),
            26 to GanttJisonCell.Reduce(36),
            27 to GanttJisonCell.Reduce(36),
            28 to GanttJisonCell.Reduce(36),
            29 to GanttJisonCell.Reduce(36),
            30 to GanttJisonCell.Reduce(36),
            31 to GanttJisonCell.Reduce(36),
            33 to GanttJisonCell.Reduce(36),
            35 to GanttJisonCell.Reduce(36),
            36 to GanttJisonCell.Reduce(36),
            38 to GanttJisonCell.Reduce(36),
            40 to GanttJisonCell.Reduce(36),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(38),
            8 to GanttJisonCell.Reduce(38),
            10 to GanttJisonCell.Reduce(38),
            12 to GanttJisonCell.Reduce(38),
            13 to GanttJisonCell.Reduce(38),
            14 to GanttJisonCell.Reduce(38),
            15 to GanttJisonCell.Reduce(38),
            16 to GanttJisonCell.Reduce(38),
            17 to GanttJisonCell.Reduce(38),
            18 to GanttJisonCell.Reduce(38),
            20 to GanttJisonCell.Reduce(38),
            21 to GanttJisonCell.Reduce(38),
            22 to GanttJisonCell.Reduce(38),
            23 to GanttJisonCell.Reduce(38),
            24 to GanttJisonCell.Reduce(38),
            25 to GanttJisonCell.Reduce(38),
            26 to GanttJisonCell.Reduce(38),
            27 to GanttJisonCell.Reduce(38),
            28 to GanttJisonCell.Reduce(38),
            29 to GanttJisonCell.Reduce(38),
            30 to GanttJisonCell.Reduce(38),
            31 to GanttJisonCell.Reduce(38),
            33 to GanttJisonCell.Reduce(38),
            35 to GanttJisonCell.Reduce(38),
            36 to GanttJisonCell.Reduce(38),
            38 to GanttJisonCell.Reduce(38),
            40 to GanttJisonCell.Reduce(38),
            42 to GanttJisonCell.Shift(46),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(37),
            8 to GanttJisonCell.Reduce(37),
            10 to GanttJisonCell.Reduce(37),
            12 to GanttJisonCell.Reduce(37),
            13 to GanttJisonCell.Reduce(37),
            14 to GanttJisonCell.Reduce(37),
            15 to GanttJisonCell.Reduce(37),
            16 to GanttJisonCell.Reduce(37),
            17 to GanttJisonCell.Reduce(37),
            18 to GanttJisonCell.Reduce(37),
            20 to GanttJisonCell.Reduce(37),
            21 to GanttJisonCell.Reduce(37),
            22 to GanttJisonCell.Reduce(37),
            23 to GanttJisonCell.Reduce(37),
            24 to GanttJisonCell.Reduce(37),
            25 to GanttJisonCell.Reduce(37),
            26 to GanttJisonCell.Reduce(37),
            27 to GanttJisonCell.Reduce(37),
            28 to GanttJisonCell.Reduce(37),
            29 to GanttJisonCell.Reduce(37),
            30 to GanttJisonCell.Reduce(37),
            31 to GanttJisonCell.Reduce(37),
            33 to GanttJisonCell.Reduce(37),
            35 to GanttJisonCell.Reduce(37),
            36 to GanttJisonCell.Reduce(37),
            38 to GanttJisonCell.Reduce(37),
            40 to GanttJisonCell.Reduce(37),
        ),
        mapOf(
            6 to GanttJisonCell.Reduce(39),
            8 to GanttJisonCell.Reduce(39),
            10 to GanttJisonCell.Reduce(39),
            12 to GanttJisonCell.Reduce(39),
            13 to GanttJisonCell.Reduce(39),
            14 to GanttJisonCell.Reduce(39),
            15 to GanttJisonCell.Reduce(39),
            16 to GanttJisonCell.Reduce(39),
            17 to GanttJisonCell.Reduce(39),
            18 to GanttJisonCell.Reduce(39),
            20 to GanttJisonCell.Reduce(39),
            21 to GanttJisonCell.Reduce(39),
            22 to GanttJisonCell.Reduce(39),
            23 to GanttJisonCell.Reduce(39),
            24 to GanttJisonCell.Reduce(39),
            25 to GanttJisonCell.Reduce(39),
            26 to GanttJisonCell.Reduce(39),
            27 to GanttJisonCell.Reduce(39),
            28 to GanttJisonCell.Reduce(39),
            29 to GanttJisonCell.Reduce(39),
            30 to GanttJisonCell.Reduce(39),
            31 to GanttJisonCell.Reduce(39),
            33 to GanttJisonCell.Reduce(39),
            35 to GanttJisonCell.Reduce(39),
            36 to GanttJisonCell.Reduce(39),
            38 to GanttJisonCell.Reduce(39),
            40 to GanttJisonCell.Reduce(39),
        ),
    )

    val lexerPatterns: List<GanttJisonLexerPattern> = buildList {
        addAll(lexerChunk0())
        addAll(lexerChunk1())
        addAll(lexerChunk2())
    }

    private fun lexerChunk0(): List<GanttJisonLexerPattern> = listOf(
        GanttJisonLexerPattern(0, "^(?:%%\\{)"),
        GanttJisonLexerPattern(1, "^(?:accTitle\\s*:\\s*)"),
        GanttJisonLexerPattern(2, "^(?:(?!\\n||)*[^\\n]*)"),
        GanttJisonLexerPattern(3, "^(?:accDescr\\s*:\\s*)"),
        GanttJisonLexerPattern(4, "^(?:(?!\\n||)*[^\\n]*)"),
        GanttJisonLexerPattern(5, "^(?:accDescr\\s*\\{\\s*)"),
        GanttJisonLexerPattern(6, "^(?:[\\}])"),
        GanttJisonLexerPattern(7, "^(?:[^\\}]*)"),
        GanttJisonLexerPattern(8, "^(?:%%(?!\\{)*[^\\n]*)"),
        GanttJisonLexerPattern(9, "^(?:[^\\}]%%*[^\\n]*)"),
        GanttJisonLexerPattern(10, "^(?:%%*[^\\n]*[\\n]*)"),
        GanttJisonLexerPattern(11, "^(?:[\\n]+)"),
        GanttJisonLexerPattern(12, "^(?:\\s+)"),
        GanttJisonLexerPattern(13, "^(?:%[^\\n]*)"),
        GanttJisonLexerPattern(14, "^(?:href[\\s]+[\"])"),
        GanttJisonLexerPattern(15, "^(?:[\"])"),
        GanttJisonLexerPattern(16, "^(?:[^\"]*)"),
        GanttJisonLexerPattern(17, "^(?:call[\\s]+)"),
        GanttJisonLexerPattern(18, "^(?:\\([\\s]*\\))"),
        GanttJisonLexerPattern(19, "^(?:\\()"),
    )

    private fun lexerChunk1(): List<GanttJisonLexerPattern> = listOf(
        GanttJisonLexerPattern(20, "^(?:[^(]*)"),
        GanttJisonLexerPattern(21, "^(?:\\))"),
        GanttJisonLexerPattern(22, "^(?:[^)]*)"),
        GanttJisonLexerPattern(23, "^(?:click[\\s]+)"),
        GanttJisonLexerPattern(24, "^(?:[\\s\\n])"),
        GanttJisonLexerPattern(25, "^(?:[^\\s\\n]*)"),
        GanttJisonLexerPattern(26, "^(?:gantt\\b)"),
        GanttJisonLexerPattern(27, "^(?:dateFormat\\s[^#\\n;]+)"),
        GanttJisonLexerPattern(28, "^(?:inclusiveEndDates\\b)"),
        GanttJisonLexerPattern(29, "^(?:topAxis\\b)"),
        GanttJisonLexerPattern(30, "^(?:axisFormat\\s[^#\\n;]+)"),
        GanttJisonLexerPattern(31, "^(?:tickInterval\\s[^#\\n;]+)"),
        GanttJisonLexerPattern(32, "^(?:includes\\s[^#\\n;]+)"),
        GanttJisonLexerPattern(33, "^(?:excludes\\s[^#\\n;]+)"),
        GanttJisonLexerPattern(34, "^(?:todayMarker\\s[^\\n;]+)"),
        GanttJisonLexerPattern(35, "^(?:weekday\\s+monday\\b)"),
        GanttJisonLexerPattern(36, "^(?:weekday\\s+tuesday\\b)"),
        GanttJisonLexerPattern(37, "^(?:weekday\\s+wednesday\\b)"),
        GanttJisonLexerPattern(38, "^(?:weekday\\s+thursday\\b)"),
        GanttJisonLexerPattern(39, "^(?:weekday\\s+friday\\b)"),
    )

    private fun lexerChunk2(): List<GanttJisonLexerPattern> = listOf(
        GanttJisonLexerPattern(40, "^(?:weekday\\s+saturday\\b)"),
        GanttJisonLexerPattern(41, "^(?:weekday\\s+sunday\\b)"),
        GanttJisonLexerPattern(42, "^(?:weekend\\s+friday\\b)"),
        GanttJisonLexerPattern(43, "^(?:weekend\\s+saturday\\b)"),
        GanttJisonLexerPattern(44, "^(?:\\d\\d\\d\\d-\\d\\d-\\d\\d\\b)"),
        GanttJisonLexerPattern(45, "^(?:title\\s[^\\n]+)"),
        GanttJisonLexerPattern(46, "^(?:accDescription\\s[^#\\n;]+)"),
        GanttJisonLexerPattern(47, "^(?:section\\s[^\\n]+)"),
        GanttJisonLexerPattern(48, "^(?:[^:\\n]+)"),
        GanttJisonLexerPattern(49, "^(?::[^#\\n;]+)"),
        GanttJisonLexerPattern(50, "^(?::)"),
        GanttJisonLexerPattern(51, "^(?:\$)"),
        GanttJisonLexerPattern(52, "^(?:.)"),
    )

    val lexerConditions: Map<String, IntArray> = mapOf(
        "acc_descr_multiline" to intArrayOf(6, 7),
        "acc_descr" to intArrayOf(4),
        "acc_title" to intArrayOf(2),
        "callbackargs" to intArrayOf(21, 22),
        "callbackname" to intArrayOf(18, 19, 20),
        "href" to intArrayOf(15, 16),
        "click" to intArrayOf(24, 25),
        "INITIAL" to intArrayOf(0, 1, 3, 5, 8, 9, 10, 11, 12, 13, 14, 17, 23, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52),
    )
}
