package io.github.cmpmermaid.core.erdiagram.upstream.mermaid

/**
 * Generated from Mermaid 12.0.0 erDiagram.jison.
 * Upstream erDiagram.jison SHA-256: 4f7c96b05d15bcc9c0e753bb106a5b8a67cfa4c8b2e13faab1d7098b92f9e5be
 * Distribution chunk SHA-256: 1437bfbd601358cd7f2e54d540410bdebc9bdd38131300d16c49705811f9de49
 *
 * Do not edit manually. Run:
 *   cd tools/official-reference && npm run generate:er-parser
 */
internal object ErJisonTables {
    val symbolIds: Map<String, Int> = mapOf(
        "error" to 2,
        "start" to 3,
        "ER_DIAGRAM" to 4,
        "document" to 5,
        "EOF" to 6,
        "line" to 7,
        "statement" to 8,
        "NEWLINE" to 9,
        "entityName" to 10,
        "relSpec" to 11,
        "COLON" to 12,
        "role" to 13,
        "STYLE_SEPARATOR" to 14,
        "idList" to 15,
        "BLOCK_START" to 16,
        "attributes" to 17,
        "BLOCK_STOP" to 18,
        "SQS" to 19,
        "SQE" to 20,
        "title" to 21,
        "title_value" to 22,
        "acc_title" to 23,
        "acc_title_value" to 24,
        "acc_descr" to 25,
        "acc_descr_value" to 26,
        "acc_descr_multiline_value" to 27,
        "direction" to 28,
        "classDefStatement" to 29,
        "classStatement" to 30,
        "styleStatement" to 31,
        "subgraphHeader" to 32,
        "END" to 33,
        "SUBGRAPH" to 34,
        "separator" to 35,
        "subgraphTitle" to 36,
        "direction_tb" to 37,
        "direction_bt" to 38,
        "direction_rl" to 39,
        "direction_lr" to 40,
        "CLASSDEF" to 41,
        "stylesOpt" to 42,
        "UNICODE_TEXT" to 43,
        "STYLE_TEXT" to 44,
        "COMMA" to 45,
        "CLASS" to 46,
        "STYLE" to 47,
        "style" to 48,
        "styleComponent" to 49,
        "SEMI" to 50,
        "NUM" to 51,
        "BRKT" to 52,
        "ENTITY_NAME" to 53,
        "DECIMAL_NUM" to 54,
        "ENTITY_ONE" to 55,
        "attribute" to 56,
        "attributeType" to 57,
        "attributeName" to 58,
        "attributeKeyTypeList" to 59,
        "attributeComment" to 60,
        "ATTRIBUTE_WORD" to 61,
        "?" to 62,
        "attributeKeyType" to 63,
        "," to 64,
        "ATTRIBUTE_KEY" to 65,
        "COMMENT" to 66,
        "cardinality" to 67,
        "relType" to 68,
        "ZERO_OR_ONE" to 69,
        "ZERO_OR_MORE" to 70,
        "ONE_OR_MORE" to 71,
        "ONLY_ONE" to 72,
        "MD_PARENT" to 73,
        "NON_IDENTIFYING" to 74,
        "IDENTIFYING" to 75,
        "WORD" to 76,
        "\$accept" to 0,
        "\$end" to 1,
    )

    val terminalNames: Map<Int, String> = mapOf(
        2 to "error",
        4 to "ER_DIAGRAM",
        6 to "EOF",
        9 to "NEWLINE",
        12 to "COLON",
        14 to "STYLE_SEPARATOR",
        16 to "BLOCK_START",
        18 to "BLOCK_STOP",
        19 to "SQS",
        20 to "SQE",
        21 to "title",
        22 to "title_value",
        23 to "acc_title",
        24 to "acc_title_value",
        25 to "acc_descr",
        26 to "acc_descr_value",
        27 to "acc_descr_multiline_value",
        33 to "END",
        34 to "SUBGRAPH",
        37 to "direction_tb",
        38 to "direction_bt",
        39 to "direction_rl",
        40 to "direction_lr",
        41 to "CLASSDEF",
        43 to "UNICODE_TEXT",
        44 to "STYLE_TEXT",
        45 to "COMMA",
        46 to "CLASS",
        47 to "STYLE",
        50 to "SEMI",
        51 to "NUM",
        52 to "BRKT",
        53 to "ENTITY_NAME",
        54 to "DECIMAL_NUM",
        55 to "ENTITY_ONE",
        61 to "ATTRIBUTE_WORD",
        62 to "?",
        64 to ",",
        65 to "ATTRIBUTE_KEY",
        66 to "COMMENT",
        69 to "ZERO_OR_ONE",
        70 to "ZERO_OR_MORE",
        71 to "ONE_OR_MORE",
        72 to "ONLY_ONE",
        73 to "MD_PARENT",
        74 to "NON_IDENTIFYING",
        75 to "IDENTIFYING",
        76 to "WORD",
    )

    val productions: Array<ErJisonProduction> = arrayOf(
        ErJisonProduction(symbol = 0, length = 0),
        ErJisonProduction(symbol = 3, length = 3),
        ErJisonProduction(symbol = 5, length = 0),
        ErJisonProduction(symbol = 5, length = 2),
        ErJisonProduction(symbol = 7, length = 1),
        ErJisonProduction(symbol = 7, length = 1),
        ErJisonProduction(symbol = 7, length = 1),
        ErJisonProduction(symbol = 8, length = 5),
        ErJisonProduction(symbol = 8, length = 9),
        ErJisonProduction(symbol = 8, length = 7),
        ErJisonProduction(symbol = 8, length = 7),
        ErJisonProduction(symbol = 8, length = 4),
        ErJisonProduction(symbol = 8, length = 6),
        ErJisonProduction(symbol = 8, length = 3),
        ErJisonProduction(symbol = 8, length = 5),
        ErJisonProduction(symbol = 8, length = 1),
        ErJisonProduction(symbol = 8, length = 3),
        ErJisonProduction(symbol = 8, length = 7),
        ErJisonProduction(symbol = 8, length = 9),
        ErJisonProduction(symbol = 8, length = 6),
        ErJisonProduction(symbol = 8, length = 8),
        ErJisonProduction(symbol = 8, length = 4),
        ErJisonProduction(symbol = 8, length = 6),
        ErJisonProduction(symbol = 8, length = 2),
        ErJisonProduction(symbol = 8, length = 2),
        ErJisonProduction(symbol = 8, length = 2),
        ErJisonProduction(symbol = 8, length = 1),
        ErJisonProduction(symbol = 8, length = 1),
        ErJisonProduction(symbol = 8, length = 1),
        ErJisonProduction(symbol = 8, length = 1),
        ErJisonProduction(symbol = 8, length = 1),
        ErJisonProduction(symbol = 8, length = 3),
        ErJisonProduction(symbol = 32, length = 3),
        ErJisonProduction(symbol = 32, length = 6),
        ErJisonProduction(symbol = 36, length = 1),
        ErJisonProduction(symbol = 36, length = 2),
        ErJisonProduction(symbol = 28, length = 1),
        ErJisonProduction(symbol = 28, length = 1),
        ErJisonProduction(symbol = 28, length = 1),
        ErJisonProduction(symbol = 28, length = 1),
        ErJisonProduction(symbol = 29, length = 4),
        ErJisonProduction(symbol = 15, length = 1),
        ErJisonProduction(symbol = 15, length = 1),
        ErJisonProduction(symbol = 15, length = 3),
        ErJisonProduction(symbol = 15, length = 3),
        ErJisonProduction(symbol = 30, length = 3),
        ErJisonProduction(symbol = 31, length = 4),
        ErJisonProduction(symbol = 42, length = 1),
        ErJisonProduction(symbol = 42, length = 3),
        ErJisonProduction(symbol = 48, length = 1),
        ErJisonProduction(symbol = 48, length = 2),
        ErJisonProduction(symbol = 35, length = 1),
        ErJisonProduction(symbol = 35, length = 1),
        ErJisonProduction(symbol = 35, length = 1),
        ErJisonProduction(symbol = 49, length = 1),
        ErJisonProduction(symbol = 49, length = 1),
        ErJisonProduction(symbol = 49, length = 1),
        ErJisonProduction(symbol = 49, length = 1),
        ErJisonProduction(symbol = 10, length = 1),
        ErJisonProduction(symbol = 10, length = 1),
        ErJisonProduction(symbol = 10, length = 1),
        ErJisonProduction(symbol = 10, length = 1),
        ErJisonProduction(symbol = 10, length = 1),
        ErJisonProduction(symbol = 17, length = 1),
        ErJisonProduction(symbol = 17, length = 2),
        ErJisonProduction(symbol = 56, length = 2),
        ErJisonProduction(symbol = 56, length = 3),
        ErJisonProduction(symbol = 56, length = 3),
        ErJisonProduction(symbol = 56, length = 4),
        ErJisonProduction(symbol = 57, length = 1),
        ErJisonProduction(symbol = 57, length = 2),
        ErJisonProduction(symbol = 58, length = 1),
        ErJisonProduction(symbol = 59, length = 1),
        ErJisonProduction(symbol = 59, length = 3),
        ErJisonProduction(symbol = 63, length = 1),
        ErJisonProduction(symbol = 60, length = 1),
        ErJisonProduction(symbol = 11, length = 3),
        ErJisonProduction(symbol = 67, length = 1),
        ErJisonProduction(symbol = 67, length = 1),
        ErJisonProduction(symbol = 67, length = 1),
        ErJisonProduction(symbol = 67, length = 1),
        ErJisonProduction(symbol = 67, length = 1),
        ErJisonProduction(symbol = 68, length = 1),
        ErJisonProduction(symbol = 68, length = 1),
        ErJisonProduction(symbol = 13, length = 1),
        ErJisonProduction(symbol = 13, length = 1),
        ErJisonProduction(symbol = 13, length = 1),
    )

    val states: Array<Map<Int, ErJisonCell>> = buildList {
        addAll(stateChunk0())
        addAll(stateChunk1())
        addAll(stateChunk2())
        addAll(stateChunk3())
        addAll(stateChunk4())
        addAll(stateChunk5())
        addAll(stateChunk6())
    }.toTypedArray()

    private fun stateChunk0(): Array<Map<Int, ErJisonCell>> = arrayOf(
        mapOf(
            3 to ErJisonCell.Goto(1),
            4 to ErJisonCell.Shift(2),
        ),
        mapOf(
            1 to ErJisonCell.Accept,
        ),
        mapOf(
            5 to ErJisonCell.Goto(3),
            6 to ErJisonCell.Reduce(2),
            9 to ErJisonCell.Reduce(2),
            21 to ErJisonCell.Reduce(2),
            23 to ErJisonCell.Reduce(2),
            25 to ErJisonCell.Reduce(2),
            27 to ErJisonCell.Reduce(2),
            34 to ErJisonCell.Reduce(2),
            37 to ErJisonCell.Reduce(2),
            38 to ErJisonCell.Reduce(2),
            39 to ErJisonCell.Reduce(2),
            40 to ErJisonCell.Reduce(2),
            41 to ErJisonCell.Reduce(2),
            43 to ErJisonCell.Reduce(2),
            46 to ErJisonCell.Reduce(2),
            47 to ErJisonCell.Reduce(2),
            51 to ErJisonCell.Reduce(2),
            53 to ErJisonCell.Reduce(2),
            54 to ErJisonCell.Reduce(2),
            55 to ErJisonCell.Reduce(2),
        ),
        mapOf(
            6 to ErJisonCell.Shift(4),
            7 to ErJisonCell.Goto(5),
            8 to ErJisonCell.Goto(6),
            9 to ErJisonCell.Shift(7),
            10 to ErJisonCell.Goto(8),
            21 to ErJisonCell.Shift(9),
            23 to ErJisonCell.Shift(10),
            25 to ErJisonCell.Shift(11),
            27 to ErJisonCell.Shift(12),
            28 to ErJisonCell.Goto(13),
            29 to ErJisonCell.Goto(14),
            30 to ErJisonCell.Goto(15),
            31 to ErJisonCell.Goto(16),
            32 to ErJisonCell.Goto(17),
            34 to ErJisonCell.Shift(30),
            37 to ErJisonCell.Shift(23),
            38 to ErJisonCell.Shift(24),
            39 to ErJisonCell.Shift(25),
            40 to ErJisonCell.Shift(26),
            41 to ErJisonCell.Shift(27),
            43 to ErJisonCell.Shift(19),
            46 to ErJisonCell.Shift(28),
            47 to ErJisonCell.Shift(29),
            51 to ErJisonCell.Shift(20),
            53 to ErJisonCell.Shift(18),
            54 to ErJisonCell.Shift(21),
            55 to ErJisonCell.Shift(22),
        ),
        mapOf(
            1 to ErJisonCell.Reduce(1),
            6 to ErJisonCell.Reduce(6),
            9 to ErJisonCell.Reduce(6),
            21 to ErJisonCell.Reduce(6),
            23 to ErJisonCell.Reduce(6),
            25 to ErJisonCell.Reduce(6),
            27 to ErJisonCell.Reduce(6),
            34 to ErJisonCell.Reduce(6),
            37 to ErJisonCell.Reduce(6),
            38 to ErJisonCell.Reduce(6),
            39 to ErJisonCell.Reduce(6),
            40 to ErJisonCell.Reduce(6),
            41 to ErJisonCell.Reduce(6),
            43 to ErJisonCell.Reduce(6),
            46 to ErJisonCell.Reduce(6),
            47 to ErJisonCell.Reduce(6),
            51 to ErJisonCell.Reduce(6),
            53 to ErJisonCell.Reduce(6),
            54 to ErJisonCell.Reduce(6),
            55 to ErJisonCell.Reduce(6),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(3),
            9 to ErJisonCell.Reduce(3),
            21 to ErJisonCell.Reduce(3),
            23 to ErJisonCell.Reduce(3),
            25 to ErJisonCell.Reduce(3),
            27 to ErJisonCell.Reduce(3),
            33 to ErJisonCell.Reduce(3),
            34 to ErJisonCell.Reduce(3),
            37 to ErJisonCell.Reduce(3),
            38 to ErJisonCell.Reduce(3),
            39 to ErJisonCell.Reduce(3),
            40 to ErJisonCell.Reduce(3),
            41 to ErJisonCell.Reduce(3),
            43 to ErJisonCell.Reduce(3),
            46 to ErJisonCell.Reduce(3),
            47 to ErJisonCell.Reduce(3),
            51 to ErJisonCell.Reduce(3),
            53 to ErJisonCell.Reduce(3),
            54 to ErJisonCell.Reduce(3),
            55 to ErJisonCell.Reduce(3),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(4),
            9 to ErJisonCell.Reduce(4),
            21 to ErJisonCell.Reduce(4),
            23 to ErJisonCell.Reduce(4),
            25 to ErJisonCell.Reduce(4),
            27 to ErJisonCell.Reduce(4),
            33 to ErJisonCell.Reduce(4),
            34 to ErJisonCell.Reduce(4),
            37 to ErJisonCell.Reduce(4),
            38 to ErJisonCell.Reduce(4),
            39 to ErJisonCell.Reduce(4),
            40 to ErJisonCell.Reduce(4),
            41 to ErJisonCell.Reduce(4),
            43 to ErJisonCell.Reduce(4),
            46 to ErJisonCell.Reduce(4),
            47 to ErJisonCell.Reduce(4),
            51 to ErJisonCell.Reduce(4),
            53 to ErJisonCell.Reduce(4),
            54 to ErJisonCell.Reduce(4),
            55 to ErJisonCell.Reduce(4),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(5),
            9 to ErJisonCell.Reduce(5),
            21 to ErJisonCell.Reduce(5),
            23 to ErJisonCell.Reduce(5),
            25 to ErJisonCell.Reduce(5),
            27 to ErJisonCell.Reduce(5),
            33 to ErJisonCell.Reduce(5),
            34 to ErJisonCell.Reduce(5),
            37 to ErJisonCell.Reduce(5),
            38 to ErJisonCell.Reduce(5),
            39 to ErJisonCell.Reduce(5),
            40 to ErJisonCell.Reduce(5),
            41 to ErJisonCell.Reduce(5),
            43 to ErJisonCell.Reduce(5),
            46 to ErJisonCell.Reduce(5),
            47 to ErJisonCell.Reduce(5),
            51 to ErJisonCell.Reduce(5),
            53 to ErJisonCell.Reduce(5),
            54 to ErJisonCell.Reduce(5),
            55 to ErJisonCell.Reduce(5),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(15),
            9 to ErJisonCell.Reduce(15),
            11 to ErJisonCell.Goto(31),
            14 to ErJisonCell.Shift(32),
            16 to ErJisonCell.Shift(33),
            19 to ErJisonCell.Shift(34),
            21 to ErJisonCell.Reduce(15),
            23 to ErJisonCell.Reduce(15),
            25 to ErJisonCell.Reduce(15),
            27 to ErJisonCell.Reduce(15),
            33 to ErJisonCell.Reduce(15),
            34 to ErJisonCell.Reduce(15),
            37 to ErJisonCell.Reduce(15),
            38 to ErJisonCell.Reduce(15),
            39 to ErJisonCell.Reduce(15),
            40 to ErJisonCell.Reduce(15),
            41 to ErJisonCell.Reduce(15),
            43 to ErJisonCell.Reduce(15),
            46 to ErJisonCell.Reduce(15),
            47 to ErJisonCell.Reduce(15),
            51 to ErJisonCell.Reduce(15),
            53 to ErJisonCell.Reduce(15),
            54 to ErJisonCell.Reduce(15),
            55 to ErJisonCell.Reduce(15),
            67 to ErJisonCell.Goto(35),
            69 to ErJisonCell.Shift(36),
            70 to ErJisonCell.Shift(37),
            71 to ErJisonCell.Shift(38),
            72 to ErJisonCell.Shift(39),
            73 to ErJisonCell.Shift(40),
        ),
        mapOf(
            22 to ErJisonCell.Shift(41),
        ),
        mapOf(
            24 to ErJisonCell.Shift(42),
        ),
        mapOf(
            26 to ErJisonCell.Shift(43),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(26),
            9 to ErJisonCell.Reduce(26),
            21 to ErJisonCell.Reduce(26),
            23 to ErJisonCell.Reduce(26),
            25 to ErJisonCell.Reduce(26),
            27 to ErJisonCell.Reduce(26),
            33 to ErJisonCell.Reduce(26),
            34 to ErJisonCell.Reduce(26),
            37 to ErJisonCell.Reduce(26),
            38 to ErJisonCell.Reduce(26),
            39 to ErJisonCell.Reduce(26),
            40 to ErJisonCell.Reduce(26),
            41 to ErJisonCell.Reduce(26),
            43 to ErJisonCell.Reduce(26),
            46 to ErJisonCell.Reduce(26),
            47 to ErJisonCell.Reduce(26),
            51 to ErJisonCell.Reduce(26),
            53 to ErJisonCell.Reduce(26),
            54 to ErJisonCell.Reduce(26),
            55 to ErJisonCell.Reduce(26),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(27),
            9 to ErJisonCell.Reduce(27),
            21 to ErJisonCell.Reduce(27),
            23 to ErJisonCell.Reduce(27),
            25 to ErJisonCell.Reduce(27),
            27 to ErJisonCell.Reduce(27),
            33 to ErJisonCell.Reduce(27),
            34 to ErJisonCell.Reduce(27),
            37 to ErJisonCell.Reduce(27),
            38 to ErJisonCell.Reduce(27),
            39 to ErJisonCell.Reduce(27),
            40 to ErJisonCell.Reduce(27),
            41 to ErJisonCell.Reduce(27),
            43 to ErJisonCell.Reduce(27),
            46 to ErJisonCell.Reduce(27),
            47 to ErJisonCell.Reduce(27),
            51 to ErJisonCell.Reduce(27),
            53 to ErJisonCell.Reduce(27),
            54 to ErJisonCell.Reduce(27),
            55 to ErJisonCell.Reduce(27),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(28),
            9 to ErJisonCell.Reduce(28),
            21 to ErJisonCell.Reduce(28),
            23 to ErJisonCell.Reduce(28),
            25 to ErJisonCell.Reduce(28),
            27 to ErJisonCell.Reduce(28),
            33 to ErJisonCell.Reduce(28),
            34 to ErJisonCell.Reduce(28),
            37 to ErJisonCell.Reduce(28),
            38 to ErJisonCell.Reduce(28),
            39 to ErJisonCell.Reduce(28),
            40 to ErJisonCell.Reduce(28),
            41 to ErJisonCell.Reduce(28),
            43 to ErJisonCell.Reduce(28),
            46 to ErJisonCell.Reduce(28),
            47 to ErJisonCell.Reduce(28),
            51 to ErJisonCell.Reduce(28),
            53 to ErJisonCell.Reduce(28),
            54 to ErJisonCell.Reduce(28),
            55 to ErJisonCell.Reduce(28),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(29),
            9 to ErJisonCell.Reduce(29),
            21 to ErJisonCell.Reduce(29),
            23 to ErJisonCell.Reduce(29),
            25 to ErJisonCell.Reduce(29),
            27 to ErJisonCell.Reduce(29),
            33 to ErJisonCell.Reduce(29),
            34 to ErJisonCell.Reduce(29),
            37 to ErJisonCell.Reduce(29),
            38 to ErJisonCell.Reduce(29),
            39 to ErJisonCell.Reduce(29),
            40 to ErJisonCell.Reduce(29),
            41 to ErJisonCell.Reduce(29),
            43 to ErJisonCell.Reduce(29),
            46 to ErJisonCell.Reduce(29),
            47 to ErJisonCell.Reduce(29),
            51 to ErJisonCell.Reduce(29),
            53 to ErJisonCell.Reduce(29),
            54 to ErJisonCell.Reduce(29),
            55 to ErJisonCell.Reduce(29),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(30),
            9 to ErJisonCell.Reduce(30),
            21 to ErJisonCell.Reduce(30),
            23 to ErJisonCell.Reduce(30),
            25 to ErJisonCell.Reduce(30),
            27 to ErJisonCell.Reduce(30),
            33 to ErJisonCell.Reduce(30),
            34 to ErJisonCell.Reduce(30),
            37 to ErJisonCell.Reduce(30),
            38 to ErJisonCell.Reduce(30),
            39 to ErJisonCell.Reduce(30),
            40 to ErJisonCell.Reduce(30),
            41 to ErJisonCell.Reduce(30),
            43 to ErJisonCell.Reduce(30),
            46 to ErJisonCell.Reduce(30),
            47 to ErJisonCell.Reduce(30),
            51 to ErJisonCell.Reduce(30),
            53 to ErJisonCell.Reduce(30),
            54 to ErJisonCell.Reduce(30),
            55 to ErJisonCell.Reduce(30),
        ),
        mapOf(
            5 to ErJisonCell.Goto(44),
            6 to ErJisonCell.Reduce(2),
            9 to ErJisonCell.Reduce(2),
            21 to ErJisonCell.Reduce(2),
            23 to ErJisonCell.Reduce(2),
            25 to ErJisonCell.Reduce(2),
            27 to ErJisonCell.Reduce(2),
            33 to ErJisonCell.Reduce(2),
            34 to ErJisonCell.Reduce(2),
            37 to ErJisonCell.Reduce(2),
            38 to ErJisonCell.Reduce(2),
            39 to ErJisonCell.Reduce(2),
            40 to ErJisonCell.Reduce(2),
            41 to ErJisonCell.Reduce(2),
            43 to ErJisonCell.Reduce(2),
            46 to ErJisonCell.Reduce(2),
            47 to ErJisonCell.Reduce(2),
            51 to ErJisonCell.Reduce(2),
            53 to ErJisonCell.Reduce(2),
            54 to ErJisonCell.Reduce(2),
            55 to ErJisonCell.Reduce(2),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(58),
            9 to ErJisonCell.Reduce(58),
            12 to ErJisonCell.Reduce(58),
            14 to ErJisonCell.Reduce(58),
            16 to ErJisonCell.Reduce(58),
            19 to ErJisonCell.Reduce(58),
            20 to ErJisonCell.Reduce(58),
            21 to ErJisonCell.Reduce(58),
            23 to ErJisonCell.Reduce(58),
            25 to ErJisonCell.Reduce(58),
            27 to ErJisonCell.Reduce(58),
            33 to ErJisonCell.Reduce(58),
            34 to ErJisonCell.Reduce(58),
            37 to ErJisonCell.Reduce(58),
            38 to ErJisonCell.Reduce(58),
            39 to ErJisonCell.Reduce(58),
            40 to ErJisonCell.Reduce(58),
            41 to ErJisonCell.Reduce(58),
            43 to ErJisonCell.Reduce(58),
            46 to ErJisonCell.Reduce(58),
            47 to ErJisonCell.Reduce(58),
            50 to ErJisonCell.Reduce(58),
            51 to ErJisonCell.Reduce(58),
            53 to ErJisonCell.Reduce(58),
            54 to ErJisonCell.Reduce(58),
            55 to ErJisonCell.Reduce(58),
            69 to ErJisonCell.Reduce(58),
            70 to ErJisonCell.Reduce(58),
            71 to ErJisonCell.Reduce(58),
            72 to ErJisonCell.Reduce(58),
            73 to ErJisonCell.Reduce(58),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(59),
            9 to ErJisonCell.Reduce(59),
            12 to ErJisonCell.Reduce(59),
            14 to ErJisonCell.Reduce(59),
            16 to ErJisonCell.Reduce(59),
            19 to ErJisonCell.Reduce(59),
            20 to ErJisonCell.Reduce(59),
            21 to ErJisonCell.Reduce(59),
            23 to ErJisonCell.Reduce(59),
            25 to ErJisonCell.Reduce(59),
            27 to ErJisonCell.Reduce(59),
            33 to ErJisonCell.Reduce(59),
            34 to ErJisonCell.Reduce(59),
            37 to ErJisonCell.Reduce(59),
            38 to ErJisonCell.Reduce(59),
            39 to ErJisonCell.Reduce(59),
            40 to ErJisonCell.Reduce(59),
            41 to ErJisonCell.Reduce(59),
            43 to ErJisonCell.Reduce(59),
            46 to ErJisonCell.Reduce(59),
            47 to ErJisonCell.Reduce(59),
            50 to ErJisonCell.Reduce(59),
            51 to ErJisonCell.Reduce(59),
            53 to ErJisonCell.Reduce(59),
            54 to ErJisonCell.Reduce(59),
            55 to ErJisonCell.Reduce(59),
            69 to ErJisonCell.Reduce(59),
            70 to ErJisonCell.Reduce(59),
            71 to ErJisonCell.Reduce(59),
            72 to ErJisonCell.Reduce(59),
            73 to ErJisonCell.Reduce(59),
        ),
    )

    private fun stateChunk1(): Array<Map<Int, ErJisonCell>> = arrayOf(
        mapOf(
            6 to ErJisonCell.Reduce(60),
            9 to ErJisonCell.Reduce(60),
            12 to ErJisonCell.Reduce(60),
            14 to ErJisonCell.Reduce(60),
            16 to ErJisonCell.Reduce(60),
            19 to ErJisonCell.Reduce(60),
            20 to ErJisonCell.Reduce(60),
            21 to ErJisonCell.Reduce(60),
            23 to ErJisonCell.Reduce(60),
            25 to ErJisonCell.Reduce(60),
            27 to ErJisonCell.Reduce(60),
            33 to ErJisonCell.Reduce(60),
            34 to ErJisonCell.Reduce(60),
            37 to ErJisonCell.Reduce(60),
            38 to ErJisonCell.Reduce(60),
            39 to ErJisonCell.Reduce(60),
            40 to ErJisonCell.Reduce(60),
            41 to ErJisonCell.Reduce(60),
            43 to ErJisonCell.Reduce(60),
            46 to ErJisonCell.Reduce(60),
            47 to ErJisonCell.Reduce(60),
            50 to ErJisonCell.Reduce(60),
            51 to ErJisonCell.Reduce(60),
            53 to ErJisonCell.Reduce(60),
            54 to ErJisonCell.Reduce(60),
            55 to ErJisonCell.Reduce(60),
            69 to ErJisonCell.Reduce(60),
            70 to ErJisonCell.Reduce(60),
            71 to ErJisonCell.Reduce(60),
            72 to ErJisonCell.Reduce(60),
            73 to ErJisonCell.Reduce(60),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(61),
            9 to ErJisonCell.Reduce(61),
            12 to ErJisonCell.Reduce(61),
            14 to ErJisonCell.Reduce(61),
            16 to ErJisonCell.Reduce(61),
            19 to ErJisonCell.Reduce(61),
            20 to ErJisonCell.Reduce(61),
            21 to ErJisonCell.Reduce(61),
            23 to ErJisonCell.Reduce(61),
            25 to ErJisonCell.Reduce(61),
            27 to ErJisonCell.Reduce(61),
            33 to ErJisonCell.Reduce(61),
            34 to ErJisonCell.Reduce(61),
            37 to ErJisonCell.Reduce(61),
            38 to ErJisonCell.Reduce(61),
            39 to ErJisonCell.Reduce(61),
            40 to ErJisonCell.Reduce(61),
            41 to ErJisonCell.Reduce(61),
            43 to ErJisonCell.Reduce(61),
            46 to ErJisonCell.Reduce(61),
            47 to ErJisonCell.Reduce(61),
            50 to ErJisonCell.Reduce(61),
            51 to ErJisonCell.Reduce(61),
            53 to ErJisonCell.Reduce(61),
            54 to ErJisonCell.Reduce(61),
            55 to ErJisonCell.Reduce(61),
            69 to ErJisonCell.Reduce(61),
            70 to ErJisonCell.Reduce(61),
            71 to ErJisonCell.Reduce(61),
            72 to ErJisonCell.Reduce(61),
            73 to ErJisonCell.Reduce(61),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(62),
            9 to ErJisonCell.Reduce(62),
            12 to ErJisonCell.Reduce(62),
            14 to ErJisonCell.Reduce(62),
            16 to ErJisonCell.Reduce(62),
            19 to ErJisonCell.Reduce(62),
            20 to ErJisonCell.Reduce(62),
            21 to ErJisonCell.Reduce(62),
            23 to ErJisonCell.Reduce(62),
            25 to ErJisonCell.Reduce(62),
            27 to ErJisonCell.Reduce(62),
            33 to ErJisonCell.Reduce(62),
            34 to ErJisonCell.Reduce(62),
            37 to ErJisonCell.Reduce(62),
            38 to ErJisonCell.Reduce(62),
            39 to ErJisonCell.Reduce(62),
            40 to ErJisonCell.Reduce(62),
            41 to ErJisonCell.Reduce(62),
            43 to ErJisonCell.Reduce(62),
            46 to ErJisonCell.Reduce(62),
            47 to ErJisonCell.Reduce(62),
            50 to ErJisonCell.Reduce(62),
            51 to ErJisonCell.Reduce(62),
            53 to ErJisonCell.Reduce(62),
            54 to ErJisonCell.Reduce(62),
            55 to ErJisonCell.Reduce(62),
            69 to ErJisonCell.Reduce(62),
            70 to ErJisonCell.Reduce(62),
            71 to ErJisonCell.Reduce(62),
            72 to ErJisonCell.Reduce(62),
            73 to ErJisonCell.Reduce(62),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(36),
            9 to ErJisonCell.Reduce(36),
            21 to ErJisonCell.Reduce(36),
            23 to ErJisonCell.Reduce(36),
            25 to ErJisonCell.Reduce(36),
            27 to ErJisonCell.Reduce(36),
            33 to ErJisonCell.Reduce(36),
            34 to ErJisonCell.Reduce(36),
            37 to ErJisonCell.Reduce(36),
            38 to ErJisonCell.Reduce(36),
            39 to ErJisonCell.Reduce(36),
            40 to ErJisonCell.Reduce(36),
            41 to ErJisonCell.Reduce(36),
            43 to ErJisonCell.Reduce(36),
            46 to ErJisonCell.Reduce(36),
            47 to ErJisonCell.Reduce(36),
            51 to ErJisonCell.Reduce(36),
            53 to ErJisonCell.Reduce(36),
            54 to ErJisonCell.Reduce(36),
            55 to ErJisonCell.Reduce(36),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(37),
            9 to ErJisonCell.Reduce(37),
            21 to ErJisonCell.Reduce(37),
            23 to ErJisonCell.Reduce(37),
            25 to ErJisonCell.Reduce(37),
            27 to ErJisonCell.Reduce(37),
            33 to ErJisonCell.Reduce(37),
            34 to ErJisonCell.Reduce(37),
            37 to ErJisonCell.Reduce(37),
            38 to ErJisonCell.Reduce(37),
            39 to ErJisonCell.Reduce(37),
            40 to ErJisonCell.Reduce(37),
            41 to ErJisonCell.Reduce(37),
            43 to ErJisonCell.Reduce(37),
            46 to ErJisonCell.Reduce(37),
            47 to ErJisonCell.Reduce(37),
            51 to ErJisonCell.Reduce(37),
            53 to ErJisonCell.Reduce(37),
            54 to ErJisonCell.Reduce(37),
            55 to ErJisonCell.Reduce(37),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(38),
            9 to ErJisonCell.Reduce(38),
            21 to ErJisonCell.Reduce(38),
            23 to ErJisonCell.Reduce(38),
            25 to ErJisonCell.Reduce(38),
            27 to ErJisonCell.Reduce(38),
            33 to ErJisonCell.Reduce(38),
            34 to ErJisonCell.Reduce(38),
            37 to ErJisonCell.Reduce(38),
            38 to ErJisonCell.Reduce(38),
            39 to ErJisonCell.Reduce(38),
            40 to ErJisonCell.Reduce(38),
            41 to ErJisonCell.Reduce(38),
            43 to ErJisonCell.Reduce(38),
            46 to ErJisonCell.Reduce(38),
            47 to ErJisonCell.Reduce(38),
            51 to ErJisonCell.Reduce(38),
            53 to ErJisonCell.Reduce(38),
            54 to ErJisonCell.Reduce(38),
            55 to ErJisonCell.Reduce(38),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(39),
            9 to ErJisonCell.Reduce(39),
            21 to ErJisonCell.Reduce(39),
            23 to ErJisonCell.Reduce(39),
            25 to ErJisonCell.Reduce(39),
            27 to ErJisonCell.Reduce(39),
            33 to ErJisonCell.Reduce(39),
            34 to ErJisonCell.Reduce(39),
            37 to ErJisonCell.Reduce(39),
            38 to ErJisonCell.Reduce(39),
            39 to ErJisonCell.Reduce(39),
            40 to ErJisonCell.Reduce(39),
            41 to ErJisonCell.Reduce(39),
            43 to ErJisonCell.Reduce(39),
            46 to ErJisonCell.Reduce(39),
            47 to ErJisonCell.Reduce(39),
            51 to ErJisonCell.Reduce(39),
            53 to ErJisonCell.Reduce(39),
            54 to ErJisonCell.Reduce(39),
            55 to ErJisonCell.Reduce(39),
        ),
        mapOf(
            15 to ErJisonCell.Goto(45),
            43 to ErJisonCell.Shift(46),
            44 to ErJisonCell.Shift(47),
        ),
        mapOf(
            15 to ErJisonCell.Goto(48),
            43 to ErJisonCell.Shift(46),
            44 to ErJisonCell.Shift(47),
        ),
        mapOf(
            15 to ErJisonCell.Goto(49),
            43 to ErJisonCell.Shift(46),
            44 to ErJisonCell.Shift(47),
        ),
        mapOf(
            10 to ErJisonCell.Goto(50),
            43 to ErJisonCell.Shift(19),
            51 to ErJisonCell.Shift(20),
            53 to ErJisonCell.Shift(18),
            54 to ErJisonCell.Shift(21),
            55 to ErJisonCell.Shift(22),
        ),
        mapOf(
            10 to ErJisonCell.Goto(51),
            43 to ErJisonCell.Shift(19),
            51 to ErJisonCell.Shift(20),
            53 to ErJisonCell.Shift(18),
            54 to ErJisonCell.Shift(21),
            55 to ErJisonCell.Shift(22),
        ),
        mapOf(
            15 to ErJisonCell.Goto(52),
            43 to ErJisonCell.Shift(46),
            44 to ErJisonCell.Shift(47),
        ),
        mapOf(
            17 to ErJisonCell.Goto(53),
            18 to ErJisonCell.Shift(54),
            56 to ErJisonCell.Goto(55),
            57 to ErJisonCell.Goto(56),
            61 to ErJisonCell.Shift(57),
        ),
        mapOf(
            10 to ErJisonCell.Goto(58),
            43 to ErJisonCell.Shift(19),
            51 to ErJisonCell.Shift(20),
            53 to ErJisonCell.Shift(18),
            54 to ErJisonCell.Shift(21),
            55 to ErJisonCell.Shift(22),
        ),
        mapOf(
            68 to ErJisonCell.Goto(59),
            74 to ErJisonCell.Shift(60),
            75 to ErJisonCell.Shift(61),
        ),
        mapOf(
            43 to ErJisonCell.Reduce(77),
            51 to ErJisonCell.Reduce(77),
            53 to ErJisonCell.Reduce(77),
            54 to ErJisonCell.Reduce(77),
            55 to ErJisonCell.Reduce(77),
            74 to ErJisonCell.Reduce(77),
            75 to ErJisonCell.Reduce(77),
        ),
        mapOf(
            43 to ErJisonCell.Reduce(78),
            51 to ErJisonCell.Reduce(78),
            53 to ErJisonCell.Reduce(78),
            54 to ErJisonCell.Reduce(78),
            55 to ErJisonCell.Reduce(78),
            74 to ErJisonCell.Reduce(78),
            75 to ErJisonCell.Reduce(78),
        ),
        mapOf(
            43 to ErJisonCell.Reduce(79),
            51 to ErJisonCell.Reduce(79),
            53 to ErJisonCell.Reduce(79),
            54 to ErJisonCell.Reduce(79),
            55 to ErJisonCell.Reduce(79),
            74 to ErJisonCell.Reduce(79),
            75 to ErJisonCell.Reduce(79),
        ),
        mapOf(
            43 to ErJisonCell.Reduce(80),
            51 to ErJisonCell.Reduce(80),
            53 to ErJisonCell.Reduce(80),
            54 to ErJisonCell.Reduce(80),
            55 to ErJisonCell.Reduce(80),
            74 to ErJisonCell.Reduce(80),
            75 to ErJisonCell.Reduce(80),
        ),
    )

    private fun stateChunk2(): Array<Map<Int, ErJisonCell>> = arrayOf(
        mapOf(
            43 to ErJisonCell.Reduce(81),
            51 to ErJisonCell.Reduce(81),
            53 to ErJisonCell.Reduce(81),
            54 to ErJisonCell.Reduce(81),
            55 to ErJisonCell.Reduce(81),
            74 to ErJisonCell.Reduce(81),
            75 to ErJisonCell.Reduce(81),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(23),
            9 to ErJisonCell.Reduce(23),
            21 to ErJisonCell.Reduce(23),
            23 to ErJisonCell.Reduce(23),
            25 to ErJisonCell.Reduce(23),
            27 to ErJisonCell.Reduce(23),
            33 to ErJisonCell.Reduce(23),
            34 to ErJisonCell.Reduce(23),
            37 to ErJisonCell.Reduce(23),
            38 to ErJisonCell.Reduce(23),
            39 to ErJisonCell.Reduce(23),
            40 to ErJisonCell.Reduce(23),
            41 to ErJisonCell.Reduce(23),
            43 to ErJisonCell.Reduce(23),
            46 to ErJisonCell.Reduce(23),
            47 to ErJisonCell.Reduce(23),
            51 to ErJisonCell.Reduce(23),
            53 to ErJisonCell.Reduce(23),
            54 to ErJisonCell.Reduce(23),
            55 to ErJisonCell.Reduce(23),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(24),
            9 to ErJisonCell.Reduce(24),
            21 to ErJisonCell.Reduce(24),
            23 to ErJisonCell.Reduce(24),
            25 to ErJisonCell.Reduce(24),
            27 to ErJisonCell.Reduce(24),
            33 to ErJisonCell.Reduce(24),
            34 to ErJisonCell.Reduce(24),
            37 to ErJisonCell.Reduce(24),
            38 to ErJisonCell.Reduce(24),
            39 to ErJisonCell.Reduce(24),
            40 to ErJisonCell.Reduce(24),
            41 to ErJisonCell.Reduce(24),
            43 to ErJisonCell.Reduce(24),
            46 to ErJisonCell.Reduce(24),
            47 to ErJisonCell.Reduce(24),
            51 to ErJisonCell.Reduce(24),
            53 to ErJisonCell.Reduce(24),
            54 to ErJisonCell.Reduce(24),
            55 to ErJisonCell.Reduce(24),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(25),
            9 to ErJisonCell.Reduce(25),
            21 to ErJisonCell.Reduce(25),
            23 to ErJisonCell.Reduce(25),
            25 to ErJisonCell.Reduce(25),
            27 to ErJisonCell.Reduce(25),
            33 to ErJisonCell.Reduce(25),
            34 to ErJisonCell.Reduce(25),
            37 to ErJisonCell.Reduce(25),
            38 to ErJisonCell.Reduce(25),
            39 to ErJisonCell.Reduce(25),
            40 to ErJisonCell.Reduce(25),
            41 to ErJisonCell.Reduce(25),
            43 to ErJisonCell.Reduce(25),
            46 to ErJisonCell.Reduce(25),
            47 to ErJisonCell.Reduce(25),
            51 to ErJisonCell.Reduce(25),
            53 to ErJisonCell.Reduce(25),
            54 to ErJisonCell.Reduce(25),
            55 to ErJisonCell.Reduce(25),
        ),
        mapOf(
            6 to ErJisonCell.Shift(63),
            7 to ErJisonCell.Goto(5),
            8 to ErJisonCell.Goto(6),
            9 to ErJisonCell.Shift(7),
            10 to ErJisonCell.Goto(8),
            21 to ErJisonCell.Shift(9),
            23 to ErJisonCell.Shift(10),
            25 to ErJisonCell.Shift(11),
            27 to ErJisonCell.Shift(12),
            28 to ErJisonCell.Goto(13),
            29 to ErJisonCell.Goto(14),
            30 to ErJisonCell.Goto(15),
            31 to ErJisonCell.Goto(16),
            32 to ErJisonCell.Goto(17),
            33 to ErJisonCell.Shift(62),
            34 to ErJisonCell.Shift(30),
            37 to ErJisonCell.Shift(23),
            38 to ErJisonCell.Shift(24),
            39 to ErJisonCell.Shift(25),
            40 to ErJisonCell.Shift(26),
            41 to ErJisonCell.Shift(27),
            43 to ErJisonCell.Shift(19),
            46 to ErJisonCell.Shift(28),
            47 to ErJisonCell.Shift(29),
            51 to ErJisonCell.Shift(20),
            53 to ErJisonCell.Shift(18),
            54 to ErJisonCell.Shift(21),
            55 to ErJisonCell.Shift(22),
        ),
        mapOf(
            12 to ErJisonCell.Shift(70),
            42 to ErJisonCell.Goto(64),
            44 to ErJisonCell.Shift(68),
            45 to ErJisonCell.Shift(65),
            48 to ErJisonCell.Goto(66),
            49 to ErJisonCell.Goto(67),
            51 to ErJisonCell.Shift(69),
            52 to ErJisonCell.Shift(71),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(41),
            9 to ErJisonCell.Reduce(41),
            12 to ErJisonCell.Reduce(41),
            16 to ErJisonCell.Reduce(41),
            21 to ErJisonCell.Reduce(41),
            23 to ErJisonCell.Reduce(41),
            25 to ErJisonCell.Reduce(41),
            27 to ErJisonCell.Reduce(41),
            33 to ErJisonCell.Reduce(41),
            34 to ErJisonCell.Reduce(41),
            37 to ErJisonCell.Reduce(41),
            38 to ErJisonCell.Reduce(41),
            39 to ErJisonCell.Reduce(41),
            40 to ErJisonCell.Reduce(41),
            41 to ErJisonCell.Reduce(41),
            43 to ErJisonCell.Reduce(41),
            44 to ErJisonCell.Reduce(41),
            45 to ErJisonCell.Reduce(41),
            46 to ErJisonCell.Reduce(41),
            47 to ErJisonCell.Reduce(41),
            51 to ErJisonCell.Reduce(41),
            52 to ErJisonCell.Reduce(41),
            53 to ErJisonCell.Reduce(41),
            54 to ErJisonCell.Reduce(41),
            55 to ErJisonCell.Reduce(41),
            69 to ErJisonCell.Reduce(41),
            70 to ErJisonCell.Reduce(41),
            71 to ErJisonCell.Reduce(41),
            72 to ErJisonCell.Reduce(41),
            73 to ErJisonCell.Reduce(41),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(42),
            9 to ErJisonCell.Reduce(42),
            12 to ErJisonCell.Reduce(42),
            16 to ErJisonCell.Reduce(42),
            21 to ErJisonCell.Reduce(42),
            23 to ErJisonCell.Reduce(42),
            25 to ErJisonCell.Reduce(42),
            27 to ErJisonCell.Reduce(42),
            33 to ErJisonCell.Reduce(42),
            34 to ErJisonCell.Reduce(42),
            37 to ErJisonCell.Reduce(42),
            38 to ErJisonCell.Reduce(42),
            39 to ErJisonCell.Reduce(42),
            40 to ErJisonCell.Reduce(42),
            41 to ErJisonCell.Reduce(42),
            43 to ErJisonCell.Reduce(42),
            44 to ErJisonCell.Reduce(42),
            45 to ErJisonCell.Reduce(42),
            46 to ErJisonCell.Reduce(42),
            47 to ErJisonCell.Reduce(42),
            51 to ErJisonCell.Reduce(42),
            52 to ErJisonCell.Reduce(42),
            53 to ErJisonCell.Reduce(42),
            54 to ErJisonCell.Reduce(42),
            55 to ErJisonCell.Reduce(42),
            69 to ErJisonCell.Reduce(42),
            70 to ErJisonCell.Reduce(42),
            71 to ErJisonCell.Reduce(42),
            72 to ErJisonCell.Reduce(42),
            73 to ErJisonCell.Reduce(42),
        ),
        mapOf(
            15 to ErJisonCell.Goto(72),
            43 to ErJisonCell.Shift(46),
            44 to ErJisonCell.Shift(47),
            45 to ErJisonCell.Shift(65),
        ),
        mapOf(
            12 to ErJisonCell.Shift(70),
            42 to ErJisonCell.Goto(73),
            44 to ErJisonCell.Shift(68),
            45 to ErJisonCell.Shift(65),
            48 to ErJisonCell.Goto(66),
            49 to ErJisonCell.Goto(67),
            51 to ErJisonCell.Shift(69),
            52 to ErJisonCell.Shift(71),
        ),
        mapOf(
            6 to ErJisonCell.Shift(78),
            9 to ErJisonCell.Shift(77),
            19 to ErJisonCell.Shift(75),
            35 to ErJisonCell.Goto(74),
            50 to ErJisonCell.Shift(76),
        ),
        mapOf(
            12 to ErJisonCell.Shift(79),
            14 to ErJisonCell.Shift(80),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(16),
            9 to ErJisonCell.Reduce(16),
            11 to ErJisonCell.Goto(81),
            16 to ErJisonCell.Shift(82),
            21 to ErJisonCell.Reduce(16),
            23 to ErJisonCell.Reduce(16),
            25 to ErJisonCell.Reduce(16),
            27 to ErJisonCell.Reduce(16),
            33 to ErJisonCell.Reduce(16),
            34 to ErJisonCell.Reduce(16),
            37 to ErJisonCell.Reduce(16),
            38 to ErJisonCell.Reduce(16),
            39 to ErJisonCell.Reduce(16),
            40 to ErJisonCell.Reduce(16),
            41 to ErJisonCell.Reduce(16),
            43 to ErJisonCell.Reduce(16),
            45 to ErJisonCell.Shift(65),
            46 to ErJisonCell.Reduce(16),
            47 to ErJisonCell.Reduce(16),
            51 to ErJisonCell.Reduce(16),
            53 to ErJisonCell.Reduce(16),
            54 to ErJisonCell.Reduce(16),
            55 to ErJisonCell.Reduce(16),
            67 to ErJisonCell.Goto(35),
            69 to ErJisonCell.Shift(36),
            70 to ErJisonCell.Shift(37),
            71 to ErJisonCell.Shift(38),
            72 to ErJisonCell.Shift(39),
            73 to ErJisonCell.Shift(40),
        ),
        mapOf(
            18 to ErJisonCell.Shift(83),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(13),
            9 to ErJisonCell.Reduce(13),
            21 to ErJisonCell.Reduce(13),
            23 to ErJisonCell.Reduce(13),
            25 to ErJisonCell.Reduce(13),
            27 to ErJisonCell.Reduce(13),
            33 to ErJisonCell.Reduce(13),
            34 to ErJisonCell.Reduce(13),
            37 to ErJisonCell.Reduce(13),
            38 to ErJisonCell.Reduce(13),
            39 to ErJisonCell.Reduce(13),
            40 to ErJisonCell.Reduce(13),
            41 to ErJisonCell.Reduce(13),
            43 to ErJisonCell.Reduce(13),
            46 to ErJisonCell.Reduce(13),
            47 to ErJisonCell.Reduce(13),
            51 to ErJisonCell.Reduce(13),
            53 to ErJisonCell.Reduce(13),
            54 to ErJisonCell.Reduce(13),
            55 to ErJisonCell.Reduce(13),
        ),
        mapOf(
            17 to ErJisonCell.Goto(84),
            18 to ErJisonCell.Reduce(63),
            56 to ErJisonCell.Goto(55),
            57 to ErJisonCell.Goto(56),
            61 to ErJisonCell.Shift(57),
        ),
        mapOf(
            58 to ErJisonCell.Goto(85),
            61 to ErJisonCell.Shift(86),
        ),
        mapOf(
            61 to ErJisonCell.Reduce(69),
            62 to ErJisonCell.Shift(87),
        ),
        mapOf(
            20 to ErJisonCell.Shift(88),
        ),
        mapOf(
            67 to ErJisonCell.Goto(89),
            69 to ErJisonCell.Shift(36),
            70 to ErJisonCell.Shift(37),
            71 to ErJisonCell.Shift(38),
            72 to ErJisonCell.Shift(39),
            73 to ErJisonCell.Shift(40),
        ),
    )

    private fun stateChunk3(): Array<Map<Int, ErJisonCell>> = arrayOf(
        mapOf(
            69 to ErJisonCell.Reduce(82),
            70 to ErJisonCell.Reduce(82),
            71 to ErJisonCell.Reduce(82),
            72 to ErJisonCell.Reduce(82),
            73 to ErJisonCell.Reduce(82),
        ),
        mapOf(
            69 to ErJisonCell.Reduce(83),
            70 to ErJisonCell.Reduce(83),
            71 to ErJisonCell.Reduce(83),
            72 to ErJisonCell.Reduce(83),
            73 to ErJisonCell.Reduce(83),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(31),
            9 to ErJisonCell.Reduce(31),
            21 to ErJisonCell.Reduce(31),
            23 to ErJisonCell.Reduce(31),
            25 to ErJisonCell.Reduce(31),
            27 to ErJisonCell.Reduce(31),
            33 to ErJisonCell.Reduce(31),
            34 to ErJisonCell.Reduce(31),
            37 to ErJisonCell.Reduce(31),
            38 to ErJisonCell.Reduce(31),
            39 to ErJisonCell.Reduce(31),
            40 to ErJisonCell.Reduce(31),
            41 to ErJisonCell.Reduce(31),
            43 to ErJisonCell.Reduce(31),
            46 to ErJisonCell.Reduce(31),
            47 to ErJisonCell.Reduce(31),
            51 to ErJisonCell.Reduce(31),
            53 to ErJisonCell.Reduce(31),
            54 to ErJisonCell.Reduce(31),
            55 to ErJisonCell.Reduce(31),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(6),
            9 to ErJisonCell.Reduce(6),
            21 to ErJisonCell.Reduce(6),
            23 to ErJisonCell.Reduce(6),
            25 to ErJisonCell.Reduce(6),
            27 to ErJisonCell.Reduce(6),
            33 to ErJisonCell.Reduce(6),
            34 to ErJisonCell.Reduce(6),
            37 to ErJisonCell.Reduce(6),
            38 to ErJisonCell.Reduce(6),
            39 to ErJisonCell.Reduce(6),
            40 to ErJisonCell.Reduce(6),
            41 to ErJisonCell.Reduce(6),
            43 to ErJisonCell.Reduce(6),
            46 to ErJisonCell.Reduce(6),
            47 to ErJisonCell.Reduce(6),
            51 to ErJisonCell.Reduce(6),
            53 to ErJisonCell.Reduce(6),
            54 to ErJisonCell.Reduce(6),
            55 to ErJisonCell.Reduce(6),
        ),
        mapOf(
            6 to ErJisonCell.Shift(78),
            9 to ErJisonCell.Shift(77),
            35 to ErJisonCell.Goto(90),
            45 to ErJisonCell.Shift(91),
            50 to ErJisonCell.Shift(76),
        ),
        mapOf(
            43 to ErJisonCell.Shift(92),
            44 to ErJisonCell.Shift(93),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(47),
            9 to ErJisonCell.Reduce(47),
            12 to ErJisonCell.Shift(70),
            44 to ErJisonCell.Shift(68),
            45 to ErJisonCell.Reduce(47),
            49 to ErJisonCell.Goto(94),
            50 to ErJisonCell.Reduce(47),
            51 to ErJisonCell.Shift(69),
            52 to ErJisonCell.Shift(71),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(49),
            9 to ErJisonCell.Reduce(49),
            12 to ErJisonCell.Reduce(49),
            44 to ErJisonCell.Reduce(49),
            45 to ErJisonCell.Reduce(49),
            50 to ErJisonCell.Reduce(49),
            51 to ErJisonCell.Reduce(49),
            52 to ErJisonCell.Reduce(49),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(54),
            9 to ErJisonCell.Reduce(54),
            12 to ErJisonCell.Reduce(54),
            44 to ErJisonCell.Reduce(54),
            45 to ErJisonCell.Reduce(54),
            50 to ErJisonCell.Reduce(54),
            51 to ErJisonCell.Reduce(54),
            52 to ErJisonCell.Reduce(54),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(55),
            9 to ErJisonCell.Reduce(55),
            12 to ErJisonCell.Reduce(55),
            44 to ErJisonCell.Reduce(55),
            45 to ErJisonCell.Reduce(55),
            50 to ErJisonCell.Reduce(55),
            51 to ErJisonCell.Reduce(55),
            52 to ErJisonCell.Reduce(55),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(56),
            9 to ErJisonCell.Reduce(56),
            12 to ErJisonCell.Reduce(56),
            44 to ErJisonCell.Reduce(56),
            45 to ErJisonCell.Reduce(56),
            50 to ErJisonCell.Reduce(56),
            51 to ErJisonCell.Reduce(56),
            52 to ErJisonCell.Reduce(56),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(57),
            9 to ErJisonCell.Reduce(57),
            12 to ErJisonCell.Reduce(57),
            44 to ErJisonCell.Reduce(57),
            45 to ErJisonCell.Reduce(57),
            50 to ErJisonCell.Reduce(57),
            51 to ErJisonCell.Reduce(57),
            52 to ErJisonCell.Reduce(57),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(45),
            9 to ErJisonCell.Reduce(45),
            21 to ErJisonCell.Reduce(45),
            23 to ErJisonCell.Reduce(45),
            25 to ErJisonCell.Reduce(45),
            27 to ErJisonCell.Reduce(45),
            33 to ErJisonCell.Reduce(45),
            34 to ErJisonCell.Reduce(45),
            37 to ErJisonCell.Reduce(45),
            38 to ErJisonCell.Reduce(45),
            39 to ErJisonCell.Reduce(45),
            40 to ErJisonCell.Reduce(45),
            41 to ErJisonCell.Reduce(45),
            43 to ErJisonCell.Reduce(45),
            45 to ErJisonCell.Shift(65),
            46 to ErJisonCell.Reduce(45),
            47 to ErJisonCell.Reduce(45),
            51 to ErJisonCell.Reduce(45),
            53 to ErJisonCell.Reduce(45),
            54 to ErJisonCell.Reduce(45),
            55 to ErJisonCell.Reduce(45),
        ),
        mapOf(
            6 to ErJisonCell.Shift(78),
            9 to ErJisonCell.Shift(77),
            35 to ErJisonCell.Goto(95),
            45 to ErJisonCell.Shift(91),
            50 to ErJisonCell.Shift(76),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(32),
            9 to ErJisonCell.Reduce(32),
            21 to ErJisonCell.Reduce(32),
            23 to ErJisonCell.Reduce(32),
            25 to ErJisonCell.Reduce(32),
            27 to ErJisonCell.Reduce(32),
            33 to ErJisonCell.Reduce(32),
            34 to ErJisonCell.Reduce(32),
            37 to ErJisonCell.Reduce(32),
            38 to ErJisonCell.Reduce(32),
            39 to ErJisonCell.Reduce(32),
            40 to ErJisonCell.Reduce(32),
            41 to ErJisonCell.Reduce(32),
            43 to ErJisonCell.Reduce(32),
            46 to ErJisonCell.Reduce(32),
            47 to ErJisonCell.Reduce(32),
            51 to ErJisonCell.Reduce(32),
            53 to ErJisonCell.Reduce(32),
            54 to ErJisonCell.Reduce(32),
            55 to ErJisonCell.Reduce(32),
        ),
        mapOf(
            10 to ErJisonCell.Goto(97),
            36 to ErJisonCell.Goto(96),
            43 to ErJisonCell.Shift(19),
            51 to ErJisonCell.Shift(20),
            53 to ErJisonCell.Shift(18),
            54 to ErJisonCell.Shift(21),
            55 to ErJisonCell.Shift(22),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(51),
            9 to ErJisonCell.Reduce(51),
            21 to ErJisonCell.Reduce(51),
            23 to ErJisonCell.Reduce(51),
            25 to ErJisonCell.Reduce(51),
            27 to ErJisonCell.Reduce(51),
            33 to ErJisonCell.Reduce(51),
            34 to ErJisonCell.Reduce(51),
            37 to ErJisonCell.Reduce(51),
            38 to ErJisonCell.Reduce(51),
            39 to ErJisonCell.Reduce(51),
            40 to ErJisonCell.Reduce(51),
            41 to ErJisonCell.Reduce(51),
            43 to ErJisonCell.Reduce(51),
            46 to ErJisonCell.Reduce(51),
            47 to ErJisonCell.Reduce(51),
            51 to ErJisonCell.Reduce(51),
            53 to ErJisonCell.Reduce(51),
            54 to ErJisonCell.Reduce(51),
            55 to ErJisonCell.Reduce(51),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(52),
            9 to ErJisonCell.Reduce(52),
            21 to ErJisonCell.Reduce(52),
            23 to ErJisonCell.Reduce(52),
            25 to ErJisonCell.Reduce(52),
            27 to ErJisonCell.Reduce(52),
            33 to ErJisonCell.Reduce(52),
            34 to ErJisonCell.Reduce(52),
            37 to ErJisonCell.Reduce(52),
            38 to ErJisonCell.Reduce(52),
            39 to ErJisonCell.Reduce(52),
            40 to ErJisonCell.Reduce(52),
            41 to ErJisonCell.Reduce(52),
            43 to ErJisonCell.Reduce(52),
            46 to ErJisonCell.Reduce(52),
            47 to ErJisonCell.Reduce(52),
            51 to ErJisonCell.Reduce(52),
            53 to ErJisonCell.Reduce(52),
            54 to ErJisonCell.Reduce(52),
            55 to ErJisonCell.Reduce(52),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(53),
            9 to ErJisonCell.Reduce(53),
            21 to ErJisonCell.Reduce(53),
            23 to ErJisonCell.Reduce(53),
            25 to ErJisonCell.Reduce(53),
            27 to ErJisonCell.Reduce(53),
            33 to ErJisonCell.Reduce(53),
            34 to ErJisonCell.Reduce(53),
            37 to ErJisonCell.Reduce(53),
            38 to ErJisonCell.Reduce(53),
            39 to ErJisonCell.Reduce(53),
            40 to ErJisonCell.Reduce(53),
            41 to ErJisonCell.Reduce(53),
            43 to ErJisonCell.Reduce(53),
            46 to ErJisonCell.Reduce(53),
            47 to ErJisonCell.Reduce(53),
            51 to ErJisonCell.Reduce(53),
            53 to ErJisonCell.Reduce(53),
            54 to ErJisonCell.Reduce(53),
            55 to ErJisonCell.Reduce(53),
        ),
        mapOf(
            13 to ErJisonCell.Goto(98),
            43 to ErJisonCell.Shift(101),
            53 to ErJisonCell.Shift(100),
            76 to ErJisonCell.Shift(99),
        ),
    )

    private fun stateChunk4(): Array<Map<Int, ErJisonCell>> = arrayOf(
        mapOf(
            15 to ErJisonCell.Goto(102),
            43 to ErJisonCell.Shift(46),
            44 to ErJisonCell.Shift(47),
        ),
        mapOf(
            10 to ErJisonCell.Goto(103),
            43 to ErJisonCell.Shift(19),
            51 to ErJisonCell.Shift(20),
            53 to ErJisonCell.Shift(18),
            54 to ErJisonCell.Shift(21),
            55 to ErJisonCell.Shift(22),
        ),
        mapOf(
            17 to ErJisonCell.Goto(104),
            18 to ErJisonCell.Shift(105),
            56 to ErJisonCell.Goto(55),
            57 to ErJisonCell.Goto(56),
            61 to ErJisonCell.Shift(57),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(11),
            9 to ErJisonCell.Reduce(11),
            21 to ErJisonCell.Reduce(11),
            23 to ErJisonCell.Reduce(11),
            25 to ErJisonCell.Reduce(11),
            27 to ErJisonCell.Reduce(11),
            33 to ErJisonCell.Reduce(11),
            34 to ErJisonCell.Reduce(11),
            37 to ErJisonCell.Reduce(11),
            38 to ErJisonCell.Reduce(11),
            39 to ErJisonCell.Reduce(11),
            40 to ErJisonCell.Reduce(11),
            41 to ErJisonCell.Reduce(11),
            43 to ErJisonCell.Reduce(11),
            46 to ErJisonCell.Reduce(11),
            47 to ErJisonCell.Reduce(11),
            51 to ErJisonCell.Reduce(11),
            53 to ErJisonCell.Reduce(11),
            54 to ErJisonCell.Reduce(11),
            55 to ErJisonCell.Reduce(11),
        ),
        mapOf(
            18 to ErJisonCell.Reduce(64),
        ),
        mapOf(
            18 to ErJisonCell.Reduce(65),
            59 to ErJisonCell.Goto(106),
            60 to ErJisonCell.Goto(107),
            61 to ErJisonCell.Reduce(65),
            63 to ErJisonCell.Goto(108),
            65 to ErJisonCell.Shift(110),
            66 to ErJisonCell.Shift(109),
        ),
        mapOf(
            18 to ErJisonCell.Reduce(71),
            61 to ErJisonCell.Reduce(71),
            65 to ErJisonCell.Reduce(71),
            66 to ErJisonCell.Reduce(71),
        ),
        mapOf(
            61 to ErJisonCell.Reduce(70),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(21),
            9 to ErJisonCell.Reduce(21),
            14 to ErJisonCell.Shift(112),
            16 to ErJisonCell.Shift(111),
            21 to ErJisonCell.Reduce(21),
            23 to ErJisonCell.Reduce(21),
            25 to ErJisonCell.Reduce(21),
            27 to ErJisonCell.Reduce(21),
            33 to ErJisonCell.Reduce(21),
            34 to ErJisonCell.Reduce(21),
            37 to ErJisonCell.Reduce(21),
            38 to ErJisonCell.Reduce(21),
            39 to ErJisonCell.Reduce(21),
            40 to ErJisonCell.Reduce(21),
            41 to ErJisonCell.Reduce(21),
            43 to ErJisonCell.Reduce(21),
            46 to ErJisonCell.Reduce(21),
            47 to ErJisonCell.Reduce(21),
            51 to ErJisonCell.Reduce(21),
            53 to ErJisonCell.Reduce(21),
            54 to ErJisonCell.Reduce(21),
            55 to ErJisonCell.Reduce(21),
        ),
        mapOf(
            43 to ErJisonCell.Reduce(76),
            51 to ErJisonCell.Reduce(76),
            53 to ErJisonCell.Reduce(76),
            54 to ErJisonCell.Reduce(76),
            55 to ErJisonCell.Reduce(76),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(40),
            9 to ErJisonCell.Reduce(40),
            21 to ErJisonCell.Reduce(40),
            23 to ErJisonCell.Reduce(40),
            25 to ErJisonCell.Reduce(40),
            27 to ErJisonCell.Reduce(40),
            33 to ErJisonCell.Reduce(40),
            34 to ErJisonCell.Reduce(40),
            37 to ErJisonCell.Reduce(40),
            38 to ErJisonCell.Reduce(40),
            39 to ErJisonCell.Reduce(40),
            40 to ErJisonCell.Reduce(40),
            41 to ErJisonCell.Reduce(40),
            43 to ErJisonCell.Reduce(40),
            46 to ErJisonCell.Reduce(40),
            47 to ErJisonCell.Reduce(40),
            51 to ErJisonCell.Reduce(40),
            53 to ErJisonCell.Reduce(40),
            54 to ErJisonCell.Reduce(40),
            55 to ErJisonCell.Reduce(40),
        ),
        mapOf(
            12 to ErJisonCell.Shift(70),
            44 to ErJisonCell.Shift(68),
            48 to ErJisonCell.Goto(113),
            49 to ErJisonCell.Goto(67),
            51 to ErJisonCell.Shift(69),
            52 to ErJisonCell.Shift(71),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(43),
            9 to ErJisonCell.Reduce(43),
            12 to ErJisonCell.Reduce(43),
            16 to ErJisonCell.Reduce(43),
            21 to ErJisonCell.Reduce(43),
            23 to ErJisonCell.Reduce(43),
            25 to ErJisonCell.Reduce(43),
            27 to ErJisonCell.Reduce(43),
            33 to ErJisonCell.Reduce(43),
            34 to ErJisonCell.Reduce(43),
            37 to ErJisonCell.Reduce(43),
            38 to ErJisonCell.Reduce(43),
            39 to ErJisonCell.Reduce(43),
            40 to ErJisonCell.Reduce(43),
            41 to ErJisonCell.Reduce(43),
            43 to ErJisonCell.Reduce(43),
            44 to ErJisonCell.Reduce(43),
            45 to ErJisonCell.Reduce(43),
            46 to ErJisonCell.Reduce(43),
            47 to ErJisonCell.Reduce(43),
            51 to ErJisonCell.Reduce(43),
            52 to ErJisonCell.Reduce(43),
            53 to ErJisonCell.Reduce(43),
            54 to ErJisonCell.Reduce(43),
            55 to ErJisonCell.Reduce(43),
            69 to ErJisonCell.Reduce(43),
            70 to ErJisonCell.Reduce(43),
            71 to ErJisonCell.Reduce(43),
            72 to ErJisonCell.Reduce(43),
            73 to ErJisonCell.Reduce(43),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(44),
            9 to ErJisonCell.Reduce(44),
            12 to ErJisonCell.Reduce(44),
            16 to ErJisonCell.Reduce(44),
            21 to ErJisonCell.Reduce(44),
            23 to ErJisonCell.Reduce(44),
            25 to ErJisonCell.Reduce(44),
            27 to ErJisonCell.Reduce(44),
            33 to ErJisonCell.Reduce(44),
            34 to ErJisonCell.Reduce(44),
            37 to ErJisonCell.Reduce(44),
            38 to ErJisonCell.Reduce(44),
            39 to ErJisonCell.Reduce(44),
            40 to ErJisonCell.Reduce(44),
            41 to ErJisonCell.Reduce(44),
            43 to ErJisonCell.Reduce(44),
            44 to ErJisonCell.Reduce(44),
            45 to ErJisonCell.Reduce(44),
            46 to ErJisonCell.Reduce(44),
            47 to ErJisonCell.Reduce(44),
            51 to ErJisonCell.Reduce(44),
            52 to ErJisonCell.Reduce(44),
            53 to ErJisonCell.Reduce(44),
            54 to ErJisonCell.Reduce(44),
            55 to ErJisonCell.Reduce(44),
            69 to ErJisonCell.Reduce(44),
            70 to ErJisonCell.Reduce(44),
            71 to ErJisonCell.Reduce(44),
            72 to ErJisonCell.Reduce(44),
            73 to ErJisonCell.Reduce(44),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(50),
            9 to ErJisonCell.Reduce(50),
            12 to ErJisonCell.Reduce(50),
            44 to ErJisonCell.Reduce(50),
            45 to ErJisonCell.Reduce(50),
            50 to ErJisonCell.Reduce(50),
            51 to ErJisonCell.Reduce(50),
            52 to ErJisonCell.Reduce(50),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(46),
            9 to ErJisonCell.Reduce(46),
            21 to ErJisonCell.Reduce(46),
            23 to ErJisonCell.Reduce(46),
            25 to ErJisonCell.Reduce(46),
            27 to ErJisonCell.Reduce(46),
            33 to ErJisonCell.Reduce(46),
            34 to ErJisonCell.Reduce(46),
            37 to ErJisonCell.Reduce(46),
            38 to ErJisonCell.Reduce(46),
            39 to ErJisonCell.Reduce(46),
            40 to ErJisonCell.Reduce(46),
            41 to ErJisonCell.Reduce(46),
            43 to ErJisonCell.Reduce(46),
            46 to ErJisonCell.Reduce(46),
            47 to ErJisonCell.Reduce(46),
            51 to ErJisonCell.Reduce(46),
            53 to ErJisonCell.Reduce(46),
            54 to ErJisonCell.Reduce(46),
            55 to ErJisonCell.Reduce(46),
        ),
        mapOf(
            10 to ErJisonCell.Goto(115),
            20 to ErJisonCell.Shift(114),
            43 to ErJisonCell.Shift(19),
            51 to ErJisonCell.Shift(20),
            53 to ErJisonCell.Shift(18),
            54 to ErJisonCell.Shift(21),
            55 to ErJisonCell.Shift(22),
        ),
        mapOf(
            20 to ErJisonCell.Reduce(34),
            43 to ErJisonCell.Reduce(34),
            51 to ErJisonCell.Reduce(34),
            53 to ErJisonCell.Reduce(34),
            54 to ErJisonCell.Reduce(34),
            55 to ErJisonCell.Reduce(34),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(7),
            9 to ErJisonCell.Reduce(7),
            21 to ErJisonCell.Reduce(7),
            23 to ErJisonCell.Reduce(7),
            25 to ErJisonCell.Reduce(7),
            27 to ErJisonCell.Reduce(7),
            33 to ErJisonCell.Reduce(7),
            34 to ErJisonCell.Reduce(7),
            37 to ErJisonCell.Reduce(7),
            38 to ErJisonCell.Reduce(7),
            39 to ErJisonCell.Reduce(7),
            40 to ErJisonCell.Reduce(7),
            41 to ErJisonCell.Reduce(7),
            43 to ErJisonCell.Reduce(7),
            46 to ErJisonCell.Reduce(7),
            47 to ErJisonCell.Reduce(7),
            51 to ErJisonCell.Reduce(7),
            53 to ErJisonCell.Reduce(7),
            54 to ErJisonCell.Reduce(7),
            55 to ErJisonCell.Reduce(7),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(84),
            9 to ErJisonCell.Reduce(84),
            21 to ErJisonCell.Reduce(84),
            23 to ErJisonCell.Reduce(84),
            25 to ErJisonCell.Reduce(84),
            27 to ErJisonCell.Reduce(84),
            33 to ErJisonCell.Reduce(84),
            34 to ErJisonCell.Reduce(84),
            37 to ErJisonCell.Reduce(84),
            38 to ErJisonCell.Reduce(84),
            39 to ErJisonCell.Reduce(84),
            40 to ErJisonCell.Reduce(84),
            41 to ErJisonCell.Reduce(84),
            43 to ErJisonCell.Reduce(84),
            46 to ErJisonCell.Reduce(84),
            47 to ErJisonCell.Reduce(84),
            51 to ErJisonCell.Reduce(84),
            53 to ErJisonCell.Reduce(84),
            54 to ErJisonCell.Reduce(84),
            55 to ErJisonCell.Reduce(84),
        ),
    )

    private fun stateChunk5(): Array<Map<Int, ErJisonCell>> = arrayOf(
        mapOf(
            6 to ErJisonCell.Reduce(85),
            9 to ErJisonCell.Reduce(85),
            21 to ErJisonCell.Reduce(85),
            23 to ErJisonCell.Reduce(85),
            25 to ErJisonCell.Reduce(85),
            27 to ErJisonCell.Reduce(85),
            33 to ErJisonCell.Reduce(85),
            34 to ErJisonCell.Reduce(85),
            37 to ErJisonCell.Reduce(85),
            38 to ErJisonCell.Reduce(85),
            39 to ErJisonCell.Reduce(85),
            40 to ErJisonCell.Reduce(85),
            41 to ErJisonCell.Reduce(85),
            43 to ErJisonCell.Reduce(85),
            46 to ErJisonCell.Reduce(85),
            47 to ErJisonCell.Reduce(85),
            51 to ErJisonCell.Reduce(85),
            53 to ErJisonCell.Reduce(85),
            54 to ErJisonCell.Reduce(85),
            55 to ErJisonCell.Reduce(85),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(86),
            9 to ErJisonCell.Reduce(86),
            21 to ErJisonCell.Reduce(86),
            23 to ErJisonCell.Reduce(86),
            25 to ErJisonCell.Reduce(86),
            27 to ErJisonCell.Reduce(86),
            33 to ErJisonCell.Reduce(86),
            34 to ErJisonCell.Reduce(86),
            37 to ErJisonCell.Reduce(86),
            38 to ErJisonCell.Reduce(86),
            39 to ErJisonCell.Reduce(86),
            40 to ErJisonCell.Reduce(86),
            41 to ErJisonCell.Reduce(86),
            43 to ErJisonCell.Reduce(86),
            46 to ErJisonCell.Reduce(86),
            47 to ErJisonCell.Reduce(86),
            51 to ErJisonCell.Reduce(86),
            53 to ErJisonCell.Reduce(86),
            54 to ErJisonCell.Reduce(86),
            55 to ErJisonCell.Reduce(86),
        ),
        mapOf(
            12 to ErJisonCell.Shift(116),
            45 to ErJisonCell.Shift(65),
        ),
        mapOf(
            12 to ErJisonCell.Shift(118),
            14 to ErJisonCell.Shift(117),
        ),
        mapOf(
            18 to ErJisonCell.Shift(119),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(14),
            9 to ErJisonCell.Reduce(14),
            21 to ErJisonCell.Reduce(14),
            23 to ErJisonCell.Reduce(14),
            25 to ErJisonCell.Reduce(14),
            27 to ErJisonCell.Reduce(14),
            33 to ErJisonCell.Reduce(14),
            34 to ErJisonCell.Reduce(14),
            37 to ErJisonCell.Reduce(14),
            38 to ErJisonCell.Reduce(14),
            39 to ErJisonCell.Reduce(14),
            40 to ErJisonCell.Reduce(14),
            41 to ErJisonCell.Reduce(14),
            43 to ErJisonCell.Reduce(14),
            46 to ErJisonCell.Reduce(14),
            47 to ErJisonCell.Reduce(14),
            51 to ErJisonCell.Reduce(14),
            53 to ErJisonCell.Reduce(14),
            54 to ErJisonCell.Reduce(14),
            55 to ErJisonCell.Reduce(14),
        ),
        mapOf(
            18 to ErJisonCell.Reduce(66),
            60 to ErJisonCell.Goto(120),
            61 to ErJisonCell.Reduce(66),
            64 to ErJisonCell.Shift(121),
            66 to ErJisonCell.Shift(109),
        ),
        mapOf(
            18 to ErJisonCell.Reduce(67),
            61 to ErJisonCell.Reduce(67),
        ),
        mapOf(
            18 to ErJisonCell.Reduce(72),
            61 to ErJisonCell.Reduce(72),
            64 to ErJisonCell.Reduce(72),
            66 to ErJisonCell.Reduce(72),
        ),
        mapOf(
            18 to ErJisonCell.Reduce(75),
            61 to ErJisonCell.Reduce(75),
        ),
        mapOf(
            18 to ErJisonCell.Reduce(74),
            61 to ErJisonCell.Reduce(74),
            64 to ErJisonCell.Reduce(74),
            66 to ErJisonCell.Reduce(74),
        ),
        mapOf(
            17 to ErJisonCell.Goto(122),
            18 to ErJisonCell.Shift(123),
            56 to ErJisonCell.Goto(55),
            57 to ErJisonCell.Goto(56),
            61 to ErJisonCell.Shift(57),
        ),
        mapOf(
            15 to ErJisonCell.Goto(124),
            43 to ErJisonCell.Shift(46),
            44 to ErJisonCell.Shift(47),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(48),
            9 to ErJisonCell.Reduce(48),
            12 to ErJisonCell.Shift(70),
            44 to ErJisonCell.Shift(68),
            45 to ErJisonCell.Reduce(48),
            49 to ErJisonCell.Goto(94),
            50 to ErJisonCell.Reduce(48),
            51 to ErJisonCell.Shift(69),
            52 to ErJisonCell.Shift(71),
        ),
        mapOf(
            6 to ErJisonCell.Shift(78),
            9 to ErJisonCell.Shift(77),
            35 to ErJisonCell.Goto(125),
            50 to ErJisonCell.Shift(76),
        ),
        mapOf(
            20 to ErJisonCell.Reduce(35),
            43 to ErJisonCell.Reduce(35),
            51 to ErJisonCell.Reduce(35),
            53 to ErJisonCell.Reduce(35),
            54 to ErJisonCell.Reduce(35),
            55 to ErJisonCell.Reduce(35),
        ),
        mapOf(
            13 to ErJisonCell.Goto(126),
            43 to ErJisonCell.Shift(101),
            53 to ErJisonCell.Shift(100),
            76 to ErJisonCell.Shift(99),
        ),
        mapOf(
            15 to ErJisonCell.Goto(127),
            43 to ErJisonCell.Shift(46),
            44 to ErJisonCell.Shift(47),
        ),
        mapOf(
            13 to ErJisonCell.Goto(128),
            43 to ErJisonCell.Shift(101),
            53 to ErJisonCell.Shift(100),
            76 to ErJisonCell.Shift(99),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(12),
            9 to ErJisonCell.Reduce(12),
            21 to ErJisonCell.Reduce(12),
            23 to ErJisonCell.Reduce(12),
            25 to ErJisonCell.Reduce(12),
            27 to ErJisonCell.Reduce(12),
            33 to ErJisonCell.Reduce(12),
            34 to ErJisonCell.Reduce(12),
            37 to ErJisonCell.Reduce(12),
            38 to ErJisonCell.Reduce(12),
            39 to ErJisonCell.Reduce(12),
            40 to ErJisonCell.Reduce(12),
            41 to ErJisonCell.Reduce(12),
            43 to ErJisonCell.Reduce(12),
            46 to ErJisonCell.Reduce(12),
            47 to ErJisonCell.Reduce(12),
            51 to ErJisonCell.Reduce(12),
            53 to ErJisonCell.Reduce(12),
            54 to ErJisonCell.Reduce(12),
            55 to ErJisonCell.Reduce(12),
        ),
    )

    private fun stateChunk6(): Array<Map<Int, ErJisonCell>> = arrayOf(
        mapOf(
            18 to ErJisonCell.Reduce(68),
            61 to ErJisonCell.Reduce(68),
        ),
        mapOf(
            63 to ErJisonCell.Goto(129),
            65 to ErJisonCell.Shift(110),
        ),
        mapOf(
            18 to ErJisonCell.Shift(130),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(19),
            9 to ErJisonCell.Reduce(19),
            21 to ErJisonCell.Reduce(19),
            23 to ErJisonCell.Reduce(19),
            25 to ErJisonCell.Reduce(19),
            27 to ErJisonCell.Reduce(19),
            33 to ErJisonCell.Reduce(19),
            34 to ErJisonCell.Reduce(19),
            37 to ErJisonCell.Reduce(19),
            38 to ErJisonCell.Reduce(19),
            39 to ErJisonCell.Reduce(19),
            40 to ErJisonCell.Reduce(19),
            41 to ErJisonCell.Reduce(19),
            43 to ErJisonCell.Reduce(19),
            46 to ErJisonCell.Reduce(19),
            47 to ErJisonCell.Reduce(19),
            51 to ErJisonCell.Reduce(19),
            53 to ErJisonCell.Reduce(19),
            54 to ErJisonCell.Reduce(19),
            55 to ErJisonCell.Reduce(19),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(22),
            9 to ErJisonCell.Reduce(22),
            16 to ErJisonCell.Shift(131),
            21 to ErJisonCell.Reduce(22),
            23 to ErJisonCell.Reduce(22),
            25 to ErJisonCell.Reduce(22),
            27 to ErJisonCell.Reduce(22),
            33 to ErJisonCell.Reduce(22),
            34 to ErJisonCell.Reduce(22),
            37 to ErJisonCell.Reduce(22),
            38 to ErJisonCell.Reduce(22),
            39 to ErJisonCell.Reduce(22),
            40 to ErJisonCell.Reduce(22),
            41 to ErJisonCell.Reduce(22),
            43 to ErJisonCell.Reduce(22),
            45 to ErJisonCell.Shift(65),
            46 to ErJisonCell.Reduce(22),
            47 to ErJisonCell.Reduce(22),
            51 to ErJisonCell.Reduce(22),
            53 to ErJisonCell.Reduce(22),
            54 to ErJisonCell.Reduce(22),
            55 to ErJisonCell.Reduce(22),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(33),
            9 to ErJisonCell.Reduce(33),
            21 to ErJisonCell.Reduce(33),
            23 to ErJisonCell.Reduce(33),
            25 to ErJisonCell.Reduce(33),
            27 to ErJisonCell.Reduce(33),
            33 to ErJisonCell.Reduce(33),
            34 to ErJisonCell.Reduce(33),
            37 to ErJisonCell.Reduce(33),
            38 to ErJisonCell.Reduce(33),
            39 to ErJisonCell.Reduce(33),
            40 to ErJisonCell.Reduce(33),
            41 to ErJisonCell.Reduce(33),
            43 to ErJisonCell.Reduce(33),
            46 to ErJisonCell.Reduce(33),
            47 to ErJisonCell.Reduce(33),
            51 to ErJisonCell.Reduce(33),
            53 to ErJisonCell.Reduce(33),
            54 to ErJisonCell.Reduce(33),
            55 to ErJisonCell.Reduce(33),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(10),
            9 to ErJisonCell.Reduce(10),
            21 to ErJisonCell.Reduce(10),
            23 to ErJisonCell.Reduce(10),
            25 to ErJisonCell.Reduce(10),
            27 to ErJisonCell.Reduce(10),
            33 to ErJisonCell.Reduce(10),
            34 to ErJisonCell.Reduce(10),
            37 to ErJisonCell.Reduce(10),
            38 to ErJisonCell.Reduce(10),
            39 to ErJisonCell.Reduce(10),
            40 to ErJisonCell.Reduce(10),
            41 to ErJisonCell.Reduce(10),
            43 to ErJisonCell.Reduce(10),
            46 to ErJisonCell.Reduce(10),
            47 to ErJisonCell.Reduce(10),
            51 to ErJisonCell.Reduce(10),
            53 to ErJisonCell.Reduce(10),
            54 to ErJisonCell.Reduce(10),
            55 to ErJisonCell.Reduce(10),
        ),
        mapOf(
            12 to ErJisonCell.Shift(132),
            45 to ErJisonCell.Shift(65),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(9),
            9 to ErJisonCell.Reduce(9),
            21 to ErJisonCell.Reduce(9),
            23 to ErJisonCell.Reduce(9),
            25 to ErJisonCell.Reduce(9),
            27 to ErJisonCell.Reduce(9),
            33 to ErJisonCell.Reduce(9),
            34 to ErJisonCell.Reduce(9),
            37 to ErJisonCell.Reduce(9),
            38 to ErJisonCell.Reduce(9),
            39 to ErJisonCell.Reduce(9),
            40 to ErJisonCell.Reduce(9),
            41 to ErJisonCell.Reduce(9),
            43 to ErJisonCell.Reduce(9),
            46 to ErJisonCell.Reduce(9),
            47 to ErJisonCell.Reduce(9),
            51 to ErJisonCell.Reduce(9),
            53 to ErJisonCell.Reduce(9),
            54 to ErJisonCell.Reduce(9),
            55 to ErJisonCell.Reduce(9),
        ),
        mapOf(
            18 to ErJisonCell.Reduce(73),
            61 to ErJisonCell.Reduce(73),
            64 to ErJisonCell.Reduce(73),
            66 to ErJisonCell.Reduce(73),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(17),
            9 to ErJisonCell.Reduce(17),
            21 to ErJisonCell.Reduce(17),
            23 to ErJisonCell.Reduce(17),
            25 to ErJisonCell.Reduce(17),
            27 to ErJisonCell.Reduce(17),
            33 to ErJisonCell.Reduce(17),
            34 to ErJisonCell.Reduce(17),
            37 to ErJisonCell.Reduce(17),
            38 to ErJisonCell.Reduce(17),
            39 to ErJisonCell.Reduce(17),
            40 to ErJisonCell.Reduce(17),
            41 to ErJisonCell.Reduce(17),
            43 to ErJisonCell.Reduce(17),
            46 to ErJisonCell.Reduce(17),
            47 to ErJisonCell.Reduce(17),
            51 to ErJisonCell.Reduce(17),
            53 to ErJisonCell.Reduce(17),
            54 to ErJisonCell.Reduce(17),
            55 to ErJisonCell.Reduce(17),
        ),
        mapOf(
            17 to ErJisonCell.Goto(133),
            18 to ErJisonCell.Shift(134),
            56 to ErJisonCell.Goto(55),
            57 to ErJisonCell.Goto(56),
            61 to ErJisonCell.Shift(57),
        ),
        mapOf(
            13 to ErJisonCell.Goto(135),
            43 to ErJisonCell.Shift(101),
            53 to ErJisonCell.Shift(100),
            76 to ErJisonCell.Shift(99),
        ),
        mapOf(
            18 to ErJisonCell.Shift(136),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(20),
            9 to ErJisonCell.Reduce(20),
            21 to ErJisonCell.Reduce(20),
            23 to ErJisonCell.Reduce(20),
            25 to ErJisonCell.Reduce(20),
            27 to ErJisonCell.Reduce(20),
            33 to ErJisonCell.Reduce(20),
            34 to ErJisonCell.Reduce(20),
            37 to ErJisonCell.Reduce(20),
            38 to ErJisonCell.Reduce(20),
            39 to ErJisonCell.Reduce(20),
            40 to ErJisonCell.Reduce(20),
            41 to ErJisonCell.Reduce(20),
            43 to ErJisonCell.Reduce(20),
            46 to ErJisonCell.Reduce(20),
            47 to ErJisonCell.Reduce(20),
            51 to ErJisonCell.Reduce(20),
            53 to ErJisonCell.Reduce(20),
            54 to ErJisonCell.Reduce(20),
            55 to ErJisonCell.Reduce(20),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(8),
            9 to ErJisonCell.Reduce(8),
            21 to ErJisonCell.Reduce(8),
            23 to ErJisonCell.Reduce(8),
            25 to ErJisonCell.Reduce(8),
            27 to ErJisonCell.Reduce(8),
            33 to ErJisonCell.Reduce(8),
            34 to ErJisonCell.Reduce(8),
            37 to ErJisonCell.Reduce(8),
            38 to ErJisonCell.Reduce(8),
            39 to ErJisonCell.Reduce(8),
            40 to ErJisonCell.Reduce(8),
            41 to ErJisonCell.Reduce(8),
            43 to ErJisonCell.Reduce(8),
            46 to ErJisonCell.Reduce(8),
            47 to ErJisonCell.Reduce(8),
            51 to ErJisonCell.Reduce(8),
            53 to ErJisonCell.Reduce(8),
            54 to ErJisonCell.Reduce(8),
            55 to ErJisonCell.Reduce(8),
        ),
        mapOf(
            6 to ErJisonCell.Reduce(18),
            9 to ErJisonCell.Reduce(18),
            21 to ErJisonCell.Reduce(18),
            23 to ErJisonCell.Reduce(18),
            25 to ErJisonCell.Reduce(18),
            27 to ErJisonCell.Reduce(18),
            33 to ErJisonCell.Reduce(18),
            34 to ErJisonCell.Reduce(18),
            37 to ErJisonCell.Reduce(18),
            38 to ErJisonCell.Reduce(18),
            39 to ErJisonCell.Reduce(18),
            40 to ErJisonCell.Reduce(18),
            41 to ErJisonCell.Reduce(18),
            43 to ErJisonCell.Reduce(18),
            46 to ErJisonCell.Reduce(18),
            47 to ErJisonCell.Reduce(18),
            51 to ErJisonCell.Reduce(18),
            53 to ErJisonCell.Reduce(18),
            54 to ErJisonCell.Reduce(18),
            55 to ErJisonCell.Reduce(18),
        ),
    )

    val lexerPatterns: List<ErJisonLexerPattern> = buildList {
        addAll(lexerChunk0())
        addAll(lexerChunk1())
        addAll(lexerChunk2())
        addAll(lexerChunk3())
        addAll(lexerChunk4())
    }

    private fun lexerChunk0(): List<ErJisonLexerPattern> = listOf(
        ErJisonLexerPattern(0, "^(?:accTitle\\s*:\\s*)"),
        ErJisonLexerPattern(1, "^(?:(?!\\n||)*[^\\n]*)"),
        ErJisonLexerPattern(2, "^(?:accDescr\\s*:\\s*)"),
        ErJisonLexerPattern(3, "^(?:(?!\\n||)*[^\\n]*)"),
        ErJisonLexerPattern(4, "^(?:accDescr\\s*\\{\\s*)"),
        ErJisonLexerPattern(5, "^(?:[\\}])"),
        ErJisonLexerPattern(6, "^(?:[^\\}]*)"),
        ErJisonLexerPattern(7, "^(?:.*direction\\s+TB[^\\n]*)"),
        ErJisonLexerPattern(8, "^(?:.*direction\\s+BT[^\\n]*)"),
        ErJisonLexerPattern(9, "^(?:.*direction\\s+RL[^\\n]*)"),
        ErJisonLexerPattern(10, "^(?:.*direction\\s+LR[^\\n]*)"),
        ErJisonLexerPattern(11, "^(?:[ \\t\\r]+)"),
        ErJisonLexerPattern(12, "^(?:[\\n]+)"),
        ErJisonLexerPattern(13, "^(?:\"[^\"%\\r\\n\\v\\b\\\\]+\")"),
        ErJisonLexerPattern(14, "^(?:\"[^\"]*\")"),
        ErJisonLexerPattern(15, "^(?:erDiagram\\b)"),
        ErJisonLexerPattern(16, "^(?:\\{)"),
        ErJisonLexerPattern(17, "^(?:#)"),
        ErJisonLexerPattern(18, "^(?:#)"),
        ErJisonLexerPattern(19, "^(?:,)"),
    )

    private fun lexerChunk1(): List<ErJisonLexerPattern> = listOf(
        ErJisonLexerPattern(20, "^(?::::)"),
        ErJisonLexerPattern(21, "^(?::)"),
        ErJisonLexerPattern(22, "^(?:\\s+)"),
        ErJisonLexerPattern(23, "^(?:\\b((?:PK)|(?:FK)|(?:UK))\\b)"),
        ErJisonLexerPattern(24, "^(?:([^\\s]*)[~].*[~]([^\\s]*))"),
        ErJisonLexerPattern(25, "^(?:([\\*A-Za-z_\\u00C0-\\uFFFF][A-Za-z0-9\\-\\_\\[\\]\\(\\)\\.,\\u00C0-\\uFFFF\\*]*))"),
        ErJisonLexerPattern(26, "^(?:[`])"),
        ErJisonLexerPattern(27, "^(?:[^`]+)"),
        ErJisonLexerPattern(28, "^(?:[`])"),
        ErJisonLexerPattern(29, "^(?:\"[^\"]*\")"),
        ErJisonLexerPattern(30, "^(?:[\\n]+)"),
        ErJisonLexerPattern(31, "^(?:\\})"),
        ErJisonLexerPattern(32, "^(?:.)"),
        ErJisonLexerPattern(33, "^(?:\\[)"),
        ErJisonLexerPattern(34, "^(?:\\])"),
        ErJisonLexerPattern(35, "^(?:style\\b)"),
        ErJisonLexerPattern(36, "^(?:[\\n]+)"),
        ErJisonLexerPattern(37, "^(?:\\s+)"),
        ErJisonLexerPattern(38, "^(?::)"),
        ErJisonLexerPattern(39, "^(?:,)"),
    )

    private fun lexerChunk2(): List<ErJisonLexerPattern> = listOf(
        ErJisonLexerPattern(40, "^(?:#)"),
        ErJisonLexerPattern(41, "^(?:classDef\\b)"),
        ErJisonLexerPattern(42, "^(?:class\\b)"),
        ErJisonLexerPattern(43, "^(?:subgraph\\b)"),
        ErJisonLexerPattern(44, "^(?:end\\b\\s*)"),
        ErJisonLexerPattern(45, "^(?:one or zero\\b)"),
        ErJisonLexerPattern(46, "^(?:one or more\\b)"),
        ErJisonLexerPattern(47, "^(?:one or many\\b)"),
        ErJisonLexerPattern(48, "^(?:1\\+)"),
        ErJisonLexerPattern(49, "^(?:\\|o\\b)"),
        ErJisonLexerPattern(50, "^(?:zero or one\\b)"),
        ErJisonLexerPattern(51, "^(?:zero or more\\b)"),
        ErJisonLexerPattern(52, "^(?:zero or many\\b)"),
        ErJisonLexerPattern(53, "^(?:0\\+)"),
        ErJisonLexerPattern(54, "^(?:\\}o\\b)"),
        ErJisonLexerPattern(55, "^(?:many\\(0\\))"),
        ErJisonLexerPattern(56, "^(?:many\\(1\\))"),
        ErJisonLexerPattern(57, "^(?:many\\b)"),
        ErJisonLexerPattern(58, "^(?:\\}\\|)"),
        ErJisonLexerPattern(59, "^(?:one\\b)"),
    )

    private fun lexerChunk3(): List<ErJisonLexerPattern> = listOf(
        ErJisonLexerPattern(60, "^(?:only one\\b)"),
        ErJisonLexerPattern(61, "^(?:[0-9]+\\.[0-9]+)"),
        ErJisonLexerPattern(62, "^(?:1(?=\\s+[A-Za-z_\"']))"),
        ErJisonLexerPattern(63, "^(?:1(?=\\s+[0-9]))"),
        ErJisonLexerPattern(64, "^(?:1(?=(--|\\.\\.|\\.-|-\\.)))"),
        ErJisonLexerPattern(65, "^(?:1\\b)"),
        ErJisonLexerPattern(66, "^(?:[0-9]+)"),
        ErJisonLexerPattern(67, "^(?:\\|\\|)"),
        ErJisonLexerPattern(68, "^(?:o\\|)"),
        ErJisonLexerPattern(69, "^(?:o\\{)"),
        ErJisonLexerPattern(70, "^(?:\\|\\{)"),
        ErJisonLexerPattern(71, "^(?:u(?=[\\.\\-\\|]))"),
        ErJisonLexerPattern(72, "^(?:\\.\\.)"),
        ErJisonLexerPattern(73, "^(?:--)"),
        ErJisonLexerPattern(74, "^(?:to\\b)"),
        ErJisonLexerPattern(75, "^(?:optionally to\\b)"),
        ErJisonLexerPattern(76, "^(?:\\.-)"),
        ErJisonLexerPattern(77, "^(?:-\\.)"),
        ErJisonLexerPattern(78, "^(?:([^\\x00-\\x7F]|\\w|-|\\*)+)"),
        ErJisonLexerPattern(79, "^(?:;)"),
    )

    private fun lexerChunk4(): List<ErJisonLexerPattern> = listOf(
        ErJisonLexerPattern(80, "^(?:([^\\x00-\\x7F]|\\w|-|\\*|\\.)+)"),
        ErJisonLexerPattern(81, "^(?:.)"),
        ErJisonLexerPattern(82, "^(?:\$)"),
    )

    val lexerConditions: Map<String, IntArray> = mapOf(
        "style" to intArrayOf(36, 37, 38, 39, 40, 78, 79),
        "acc_descr_multiline" to intArrayOf(5, 6),
        "acc_descr" to intArrayOf(3),
        "acc_title" to intArrayOf(1),
        "block_bq" to intArrayOf(27, 28),
        "block" to intArrayOf(22, 23, 24, 25, 26, 29, 30, 31, 32),
        "INITIAL" to intArrayOf(0, 2, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 33, 34, 35, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 80, 81, 82),
    )
}
