package io.github.cmpmermaid.core.statediagram.upstream.mermaid

/**
 * Generated from Mermaid 12.0.0 stateDiagram.jison.
 * Upstream stateDiagram.jison SHA-256: 94d4715707c3b35192b8586fa271e843f2c084e9ff70dd8db07c510c1a23e231
 * Distribution chunk SHA-256: 33ba302a233f6a2b43efd12b2ba42cd1878d637bf79d351d5901812728c9318d
 *
 * Do not edit manually. Run:
 *   cd tools/official-reference && npm run generate:state-parser
 */
internal object StateJisonTables {
    val symbolIds: Map<String, Int> = mapOf(
        "error" to 2,
        "start" to 3,
        "SPACE" to 4,
        "NL" to 5,
        "SD" to 6,
        "document" to 7,
        "line" to 8,
        "statement" to 9,
        "classDefStatement" to 10,
        "styleStatement" to 11,
        "cssClassStatement" to 12,
        "idStatement" to 13,
        "DESCR" to 14,
        "-->" to 15,
        "HIDE_EMPTY" to 16,
        "scale" to 17,
        "WIDTH" to 18,
        "COMPOSIT_STATE" to 19,
        "STRUCT_START" to 20,
        "STRUCT_STOP" to 21,
        "STATE_DESCR" to 22,
        "AS" to 23,
        "ID" to 24,
        "FORK" to 25,
        "JOIN" to 26,
        "CHOICE" to 27,
        "CONCURRENT" to 28,
        "note" to 29,
        "notePosition" to 30,
        "NOTE_TEXT" to 31,
        "direction" to 32,
        "acc_title" to 33,
        "acc_title_value" to 34,
        "acc_descr" to 35,
        "acc_descr_value" to 36,
        "acc_descr_multiline_value" to 37,
        "CLICK" to 38,
        "STRING" to 39,
        "HREF" to 40,
        "classDef" to 41,
        "CLASSDEF_ID" to 42,
        "CLASSDEF_STYLEOPTS" to 43,
        "DEFAULT" to 44,
        "style" to 45,
        "STYLE_IDS" to 46,
        "STYLEDEF_STYLEOPTS" to 47,
        "class" to 48,
        "CLASSENTITY_IDS" to 49,
        "STYLECLASS" to 50,
        "direction_tb" to 51,
        "direction_bt" to 52,
        "direction_rl" to 53,
        "direction_lr" to 54,
        "eol" to 55,
        ";" to 56,
        "EDGE_STATE" to 57,
        "STYLE_SEPARATOR" to 58,
        "left_of" to 59,
        "right_of" to 60,
        "\$accept" to 0,
        "\$end" to 1,
    )

    val terminalNames: Map<Int, String> = mapOf(
        2 to "error",
        4 to "SPACE",
        5 to "NL",
        6 to "SD",
        14 to "DESCR",
        15 to "-->",
        16 to "HIDE_EMPTY",
        17 to "scale",
        18 to "WIDTH",
        19 to "COMPOSIT_STATE",
        20 to "STRUCT_START",
        21 to "STRUCT_STOP",
        22 to "STATE_DESCR",
        23 to "AS",
        24 to "ID",
        25 to "FORK",
        26 to "JOIN",
        27 to "CHOICE",
        28 to "CONCURRENT",
        29 to "note",
        31 to "NOTE_TEXT",
        33 to "acc_title",
        34 to "acc_title_value",
        35 to "acc_descr",
        36 to "acc_descr_value",
        37 to "acc_descr_multiline_value",
        38 to "CLICK",
        39 to "STRING",
        40 to "HREF",
        41 to "classDef",
        42 to "CLASSDEF_ID",
        43 to "CLASSDEF_STYLEOPTS",
        44 to "DEFAULT",
        45 to "style",
        46 to "STYLE_IDS",
        47 to "STYLEDEF_STYLEOPTS",
        48 to "class",
        49 to "CLASSENTITY_IDS",
        50 to "STYLECLASS",
        51 to "direction_tb",
        52 to "direction_bt",
        53 to "direction_rl",
        54 to "direction_lr",
        56 to ";",
        57 to "EDGE_STATE",
        58 to "STYLE_SEPARATOR",
        59 to "left_of",
        60 to "right_of",
    )

    val productions: Array<StateJisonProduction> = arrayOf(
        StateJisonProduction(symbol = 0, length = 0),
        StateJisonProduction(symbol = 3, length = 2),
        StateJisonProduction(symbol = 3, length = 2),
        StateJisonProduction(symbol = 3, length = 2),
        StateJisonProduction(symbol = 7, length = 0),
        StateJisonProduction(symbol = 7, length = 2),
        StateJisonProduction(symbol = 8, length = 2),
        StateJisonProduction(symbol = 8, length = 1),
        StateJisonProduction(symbol = 8, length = 1),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 2),
        StateJisonProduction(symbol = 9, length = 3),
        StateJisonProduction(symbol = 9, length = 4),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 2),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 4),
        StateJisonProduction(symbol = 9, length = 3),
        StateJisonProduction(symbol = 9, length = 6),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 4),
        StateJisonProduction(symbol = 9, length = 4),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 2),
        StateJisonProduction(symbol = 9, length = 2),
        StateJisonProduction(symbol = 9, length = 1),
        StateJisonProduction(symbol = 9, length = 5),
        StateJisonProduction(symbol = 9, length = 5),
        StateJisonProduction(symbol = 10, length = 3),
        StateJisonProduction(symbol = 10, length = 3),
        StateJisonProduction(symbol = 11, length = 3),
        StateJisonProduction(symbol = 12, length = 3),
        StateJisonProduction(symbol = 32, length = 1),
        StateJisonProduction(symbol = 32, length = 1),
        StateJisonProduction(symbol = 32, length = 1),
        StateJisonProduction(symbol = 32, length = 1),
        StateJisonProduction(symbol = 55, length = 1),
        StateJisonProduction(symbol = 55, length = 1),
        StateJisonProduction(symbol = 13, length = 1),
        StateJisonProduction(symbol = 13, length = 1),
        StateJisonProduction(symbol = 13, length = 3),
        StateJisonProduction(symbol = 13, length = 3),
        StateJisonProduction(symbol = 30, length = 1),
        StateJisonProduction(symbol = 30, length = 1),
    )

    val states: Array<Map<Int, StateJisonCell>> = buildList {
        addAll(stateChunk0())
        addAll(stateChunk1())
        addAll(stateChunk2())
        addAll(stateChunk3())
        addAll(stateChunk4())
    }.toTypedArray()

    private fun stateChunk0(): Array<Map<Int, StateJisonCell>> = arrayOf(
        mapOf(
            3 to StateJisonCell.Goto(1),
            4 to StateJisonCell.Shift(2),
            5 to StateJisonCell.Shift(3),
            6 to StateJisonCell.Shift(4),
        ),
        mapOf(
            1 to StateJisonCell.Accept,
        ),
        mapOf(
            3 to StateJisonCell.Goto(5),
            4 to StateJisonCell.Shift(2),
            5 to StateJisonCell.Shift(3),
            6 to StateJisonCell.Shift(4),
        ),
        mapOf(
            3 to StateJisonCell.Goto(6),
            4 to StateJisonCell.Shift(2),
            5 to StateJisonCell.Shift(3),
            6 to StateJisonCell.Shift(4),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(4),
            4 to StateJisonCell.Reduce(4),
            5 to StateJisonCell.Reduce(4),
            7 to StateJisonCell.Goto(7),
            16 to StateJisonCell.Reduce(4),
            17 to StateJisonCell.Reduce(4),
            19 to StateJisonCell.Reduce(4),
            22 to StateJisonCell.Reduce(4),
            24 to StateJisonCell.Reduce(4),
            25 to StateJisonCell.Reduce(4),
            26 to StateJisonCell.Reduce(4),
            27 to StateJisonCell.Reduce(4),
            28 to StateJisonCell.Reduce(4),
            29 to StateJisonCell.Reduce(4),
            33 to StateJisonCell.Reduce(4),
            35 to StateJisonCell.Reduce(4),
            37 to StateJisonCell.Reduce(4),
            38 to StateJisonCell.Reduce(4),
            41 to StateJisonCell.Reduce(4),
            45 to StateJisonCell.Reduce(4),
            48 to StateJisonCell.Reduce(4),
            51 to StateJisonCell.Reduce(4),
            52 to StateJisonCell.Reduce(4),
            53 to StateJisonCell.Reduce(4),
            54 to StateJisonCell.Reduce(4),
            57 to StateJisonCell.Reduce(4),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(1),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(2),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(3),
            4 to StateJisonCell.Shift(9),
            5 to StateJisonCell.Shift(11),
            8 to StateJisonCell.Goto(8),
            9 to StateJisonCell.Goto(10),
            10 to StateJisonCell.Goto(12),
            11 to StateJisonCell.Goto(13),
            12 to StateJisonCell.Goto(14),
            13 to StateJisonCell.Goto(15),
            16 to StateJisonCell.Shift(16),
            17 to StateJisonCell.Shift(17),
            19 to StateJisonCell.Shift(18),
            22 to StateJisonCell.Shift(19),
            24 to StateJisonCell.Shift(33),
            25 to StateJisonCell.Shift(20),
            26 to StateJisonCell.Shift(21),
            27 to StateJisonCell.Shift(22),
            28 to StateJisonCell.Shift(23),
            29 to StateJisonCell.Shift(24),
            32 to StateJisonCell.Goto(25),
            33 to StateJisonCell.Shift(26),
            35 to StateJisonCell.Shift(27),
            37 to StateJisonCell.Shift(28),
            38 to StateJisonCell.Shift(29),
            41 to StateJisonCell.Shift(30),
            45 to StateJisonCell.Shift(31),
            48 to StateJisonCell.Shift(32),
            51 to StateJisonCell.Shift(35),
            52 to StateJisonCell.Shift(36),
            53 to StateJisonCell.Shift(37),
            54 to StateJisonCell.Shift(38),
            57 to StateJisonCell.Shift(34),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(5),
            4 to StateJisonCell.Reduce(5),
            5 to StateJisonCell.Reduce(5),
            16 to StateJisonCell.Reduce(5),
            17 to StateJisonCell.Reduce(5),
            19 to StateJisonCell.Reduce(5),
            21 to StateJisonCell.Reduce(5),
            22 to StateJisonCell.Reduce(5),
            24 to StateJisonCell.Reduce(5),
            25 to StateJisonCell.Reduce(5),
            26 to StateJisonCell.Reduce(5),
            27 to StateJisonCell.Reduce(5),
            28 to StateJisonCell.Reduce(5),
            29 to StateJisonCell.Reduce(5),
            33 to StateJisonCell.Reduce(5),
            35 to StateJisonCell.Reduce(5),
            37 to StateJisonCell.Reduce(5),
            38 to StateJisonCell.Reduce(5),
            41 to StateJisonCell.Reduce(5),
            45 to StateJisonCell.Reduce(5),
            48 to StateJisonCell.Reduce(5),
            51 to StateJisonCell.Reduce(5),
            52 to StateJisonCell.Reduce(5),
            53 to StateJisonCell.Reduce(5),
            54 to StateJisonCell.Reduce(5),
            57 to StateJisonCell.Reduce(5),
        ),
        mapOf(
            9 to StateJisonCell.Goto(39),
            10 to StateJisonCell.Goto(12),
            11 to StateJisonCell.Goto(13),
            12 to StateJisonCell.Goto(14),
            13 to StateJisonCell.Goto(15),
            16 to StateJisonCell.Shift(16),
            17 to StateJisonCell.Shift(17),
            19 to StateJisonCell.Shift(18),
            22 to StateJisonCell.Shift(19),
            24 to StateJisonCell.Shift(33),
            25 to StateJisonCell.Shift(20),
            26 to StateJisonCell.Shift(21),
            27 to StateJisonCell.Shift(22),
            28 to StateJisonCell.Shift(23),
            29 to StateJisonCell.Shift(24),
            32 to StateJisonCell.Goto(25),
            33 to StateJisonCell.Shift(26),
            35 to StateJisonCell.Shift(27),
            37 to StateJisonCell.Shift(28),
            38 to StateJisonCell.Shift(29),
            41 to StateJisonCell.Shift(30),
            45 to StateJisonCell.Shift(31),
            48 to StateJisonCell.Shift(32),
            51 to StateJisonCell.Shift(35),
            52 to StateJisonCell.Shift(36),
            53 to StateJisonCell.Shift(37),
            54 to StateJisonCell.Shift(38),
            57 to StateJisonCell.Shift(34),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(7),
            4 to StateJisonCell.Reduce(7),
            5 to StateJisonCell.Reduce(7),
            16 to StateJisonCell.Reduce(7),
            17 to StateJisonCell.Reduce(7),
            19 to StateJisonCell.Reduce(7),
            21 to StateJisonCell.Reduce(7),
            22 to StateJisonCell.Reduce(7),
            24 to StateJisonCell.Reduce(7),
            25 to StateJisonCell.Reduce(7),
            26 to StateJisonCell.Reduce(7),
            27 to StateJisonCell.Reduce(7),
            28 to StateJisonCell.Reduce(7),
            29 to StateJisonCell.Reduce(7),
            33 to StateJisonCell.Reduce(7),
            35 to StateJisonCell.Reduce(7),
            37 to StateJisonCell.Reduce(7),
            38 to StateJisonCell.Reduce(7),
            41 to StateJisonCell.Reduce(7),
            45 to StateJisonCell.Reduce(7),
            48 to StateJisonCell.Reduce(7),
            51 to StateJisonCell.Reduce(7),
            52 to StateJisonCell.Reduce(7),
            53 to StateJisonCell.Reduce(7),
            54 to StateJisonCell.Reduce(7),
            57 to StateJisonCell.Reduce(7),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(8),
            4 to StateJisonCell.Reduce(8),
            5 to StateJisonCell.Reduce(8),
            16 to StateJisonCell.Reduce(8),
            17 to StateJisonCell.Reduce(8),
            19 to StateJisonCell.Reduce(8),
            21 to StateJisonCell.Reduce(8),
            22 to StateJisonCell.Reduce(8),
            24 to StateJisonCell.Reduce(8),
            25 to StateJisonCell.Reduce(8),
            26 to StateJisonCell.Reduce(8),
            27 to StateJisonCell.Reduce(8),
            28 to StateJisonCell.Reduce(8),
            29 to StateJisonCell.Reduce(8),
            33 to StateJisonCell.Reduce(8),
            35 to StateJisonCell.Reduce(8),
            37 to StateJisonCell.Reduce(8),
            38 to StateJisonCell.Reduce(8),
            41 to StateJisonCell.Reduce(8),
            45 to StateJisonCell.Reduce(8),
            48 to StateJisonCell.Reduce(8),
            51 to StateJisonCell.Reduce(8),
            52 to StateJisonCell.Reduce(8),
            53 to StateJisonCell.Reduce(8),
            54 to StateJisonCell.Reduce(8),
            57 to StateJisonCell.Reduce(8),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(9),
            4 to StateJisonCell.Reduce(9),
            5 to StateJisonCell.Reduce(9),
            16 to StateJisonCell.Reduce(9),
            17 to StateJisonCell.Reduce(9),
            19 to StateJisonCell.Reduce(9),
            21 to StateJisonCell.Reduce(9),
            22 to StateJisonCell.Reduce(9),
            24 to StateJisonCell.Reduce(9),
            25 to StateJisonCell.Reduce(9),
            26 to StateJisonCell.Reduce(9),
            27 to StateJisonCell.Reduce(9),
            28 to StateJisonCell.Reduce(9),
            29 to StateJisonCell.Reduce(9),
            33 to StateJisonCell.Reduce(9),
            35 to StateJisonCell.Reduce(9),
            37 to StateJisonCell.Reduce(9),
            38 to StateJisonCell.Reduce(9),
            41 to StateJisonCell.Reduce(9),
            45 to StateJisonCell.Reduce(9),
            48 to StateJisonCell.Reduce(9),
            51 to StateJisonCell.Reduce(9),
            52 to StateJisonCell.Reduce(9),
            53 to StateJisonCell.Reduce(9),
            54 to StateJisonCell.Reduce(9),
            57 to StateJisonCell.Reduce(9),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(10),
            4 to StateJisonCell.Reduce(10),
            5 to StateJisonCell.Reduce(10),
            16 to StateJisonCell.Reduce(10),
            17 to StateJisonCell.Reduce(10),
            19 to StateJisonCell.Reduce(10),
            21 to StateJisonCell.Reduce(10),
            22 to StateJisonCell.Reduce(10),
            24 to StateJisonCell.Reduce(10),
            25 to StateJisonCell.Reduce(10),
            26 to StateJisonCell.Reduce(10),
            27 to StateJisonCell.Reduce(10),
            28 to StateJisonCell.Reduce(10),
            29 to StateJisonCell.Reduce(10),
            33 to StateJisonCell.Reduce(10),
            35 to StateJisonCell.Reduce(10),
            37 to StateJisonCell.Reduce(10),
            38 to StateJisonCell.Reduce(10),
            41 to StateJisonCell.Reduce(10),
            45 to StateJisonCell.Reduce(10),
            48 to StateJisonCell.Reduce(10),
            51 to StateJisonCell.Reduce(10),
            52 to StateJisonCell.Reduce(10),
            53 to StateJisonCell.Reduce(10),
            54 to StateJisonCell.Reduce(10),
            57 to StateJisonCell.Reduce(10),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(11),
            4 to StateJisonCell.Reduce(11),
            5 to StateJisonCell.Reduce(11),
            16 to StateJisonCell.Reduce(11),
            17 to StateJisonCell.Reduce(11),
            19 to StateJisonCell.Reduce(11),
            21 to StateJisonCell.Reduce(11),
            22 to StateJisonCell.Reduce(11),
            24 to StateJisonCell.Reduce(11),
            25 to StateJisonCell.Reduce(11),
            26 to StateJisonCell.Reduce(11),
            27 to StateJisonCell.Reduce(11),
            28 to StateJisonCell.Reduce(11),
            29 to StateJisonCell.Reduce(11),
            33 to StateJisonCell.Reduce(11),
            35 to StateJisonCell.Reduce(11),
            37 to StateJisonCell.Reduce(11),
            38 to StateJisonCell.Reduce(11),
            41 to StateJisonCell.Reduce(11),
            45 to StateJisonCell.Reduce(11),
            48 to StateJisonCell.Reduce(11),
            51 to StateJisonCell.Reduce(11),
            52 to StateJisonCell.Reduce(11),
            53 to StateJisonCell.Reduce(11),
            54 to StateJisonCell.Reduce(11),
            57 to StateJisonCell.Reduce(11),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(12),
            4 to StateJisonCell.Reduce(12),
            5 to StateJisonCell.Reduce(12),
            14 to StateJisonCell.Shift(40),
            15 to StateJisonCell.Shift(41),
            16 to StateJisonCell.Reduce(12),
            17 to StateJisonCell.Reduce(12),
            19 to StateJisonCell.Reduce(12),
            21 to StateJisonCell.Reduce(12),
            22 to StateJisonCell.Reduce(12),
            24 to StateJisonCell.Reduce(12),
            25 to StateJisonCell.Reduce(12),
            26 to StateJisonCell.Reduce(12),
            27 to StateJisonCell.Reduce(12),
            28 to StateJisonCell.Reduce(12),
            29 to StateJisonCell.Reduce(12),
            33 to StateJisonCell.Reduce(12),
            35 to StateJisonCell.Reduce(12),
            37 to StateJisonCell.Reduce(12),
            38 to StateJisonCell.Reduce(12),
            41 to StateJisonCell.Reduce(12),
            45 to StateJisonCell.Reduce(12),
            48 to StateJisonCell.Reduce(12),
            51 to StateJisonCell.Reduce(12),
            52 to StateJisonCell.Reduce(12),
            53 to StateJisonCell.Reduce(12),
            54 to StateJisonCell.Reduce(12),
            57 to StateJisonCell.Reduce(12),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(16),
            4 to StateJisonCell.Reduce(16),
            5 to StateJisonCell.Reduce(16),
            16 to StateJisonCell.Reduce(16),
            17 to StateJisonCell.Reduce(16),
            19 to StateJisonCell.Reduce(16),
            21 to StateJisonCell.Reduce(16),
            22 to StateJisonCell.Reduce(16),
            24 to StateJisonCell.Reduce(16),
            25 to StateJisonCell.Reduce(16),
            26 to StateJisonCell.Reduce(16),
            27 to StateJisonCell.Reduce(16),
            28 to StateJisonCell.Reduce(16),
            29 to StateJisonCell.Reduce(16),
            33 to StateJisonCell.Reduce(16),
            35 to StateJisonCell.Reduce(16),
            37 to StateJisonCell.Reduce(16),
            38 to StateJisonCell.Reduce(16),
            41 to StateJisonCell.Reduce(16),
            45 to StateJisonCell.Reduce(16),
            48 to StateJisonCell.Reduce(16),
            51 to StateJisonCell.Reduce(16),
            52 to StateJisonCell.Reduce(16),
            53 to StateJisonCell.Reduce(16),
            54 to StateJisonCell.Reduce(16),
            57 to StateJisonCell.Reduce(16),
        ),
        mapOf(
            18 to StateJisonCell.Shift(42),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(18),
            4 to StateJisonCell.Reduce(18),
            5 to StateJisonCell.Reduce(18),
            16 to StateJisonCell.Reduce(18),
            17 to StateJisonCell.Reduce(18),
            19 to StateJisonCell.Reduce(18),
            20 to StateJisonCell.Shift(43),
            21 to StateJisonCell.Reduce(18),
            22 to StateJisonCell.Reduce(18),
            24 to StateJisonCell.Reduce(18),
            25 to StateJisonCell.Reduce(18),
            26 to StateJisonCell.Reduce(18),
            27 to StateJisonCell.Reduce(18),
            28 to StateJisonCell.Reduce(18),
            29 to StateJisonCell.Reduce(18),
            33 to StateJisonCell.Reduce(18),
            35 to StateJisonCell.Reduce(18),
            37 to StateJisonCell.Reduce(18),
            38 to StateJisonCell.Reduce(18),
            41 to StateJisonCell.Reduce(18),
            45 to StateJisonCell.Reduce(18),
            48 to StateJisonCell.Reduce(18),
            51 to StateJisonCell.Reduce(18),
            52 to StateJisonCell.Reduce(18),
            53 to StateJisonCell.Reduce(18),
            54 to StateJisonCell.Reduce(18),
            57 to StateJisonCell.Reduce(18),
        ),
        mapOf(
            23 to StateJisonCell.Shift(44),
        ),
    )

    private fun stateChunk1(): Array<Map<Int, StateJisonCell>> = arrayOf(
        mapOf(
            1 to StateJisonCell.Reduce(22),
            4 to StateJisonCell.Reduce(22),
            5 to StateJisonCell.Reduce(22),
            16 to StateJisonCell.Reduce(22),
            17 to StateJisonCell.Reduce(22),
            19 to StateJisonCell.Reduce(22),
            21 to StateJisonCell.Reduce(22),
            22 to StateJisonCell.Reduce(22),
            24 to StateJisonCell.Reduce(22),
            25 to StateJisonCell.Reduce(22),
            26 to StateJisonCell.Reduce(22),
            27 to StateJisonCell.Reduce(22),
            28 to StateJisonCell.Reduce(22),
            29 to StateJisonCell.Reduce(22),
            33 to StateJisonCell.Reduce(22),
            35 to StateJisonCell.Reduce(22),
            37 to StateJisonCell.Reduce(22),
            38 to StateJisonCell.Reduce(22),
            41 to StateJisonCell.Reduce(22),
            45 to StateJisonCell.Reduce(22),
            48 to StateJisonCell.Reduce(22),
            51 to StateJisonCell.Reduce(22),
            52 to StateJisonCell.Reduce(22),
            53 to StateJisonCell.Reduce(22),
            54 to StateJisonCell.Reduce(22),
            57 to StateJisonCell.Reduce(22),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(23),
            4 to StateJisonCell.Reduce(23),
            5 to StateJisonCell.Reduce(23),
            16 to StateJisonCell.Reduce(23),
            17 to StateJisonCell.Reduce(23),
            19 to StateJisonCell.Reduce(23),
            21 to StateJisonCell.Reduce(23),
            22 to StateJisonCell.Reduce(23),
            24 to StateJisonCell.Reduce(23),
            25 to StateJisonCell.Reduce(23),
            26 to StateJisonCell.Reduce(23),
            27 to StateJisonCell.Reduce(23),
            28 to StateJisonCell.Reduce(23),
            29 to StateJisonCell.Reduce(23),
            33 to StateJisonCell.Reduce(23),
            35 to StateJisonCell.Reduce(23),
            37 to StateJisonCell.Reduce(23),
            38 to StateJisonCell.Reduce(23),
            41 to StateJisonCell.Reduce(23),
            45 to StateJisonCell.Reduce(23),
            48 to StateJisonCell.Reduce(23),
            51 to StateJisonCell.Reduce(23),
            52 to StateJisonCell.Reduce(23),
            53 to StateJisonCell.Reduce(23),
            54 to StateJisonCell.Reduce(23),
            57 to StateJisonCell.Reduce(23),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(24),
            4 to StateJisonCell.Reduce(24),
            5 to StateJisonCell.Reduce(24),
            16 to StateJisonCell.Reduce(24),
            17 to StateJisonCell.Reduce(24),
            19 to StateJisonCell.Reduce(24),
            21 to StateJisonCell.Reduce(24),
            22 to StateJisonCell.Reduce(24),
            24 to StateJisonCell.Reduce(24),
            25 to StateJisonCell.Reduce(24),
            26 to StateJisonCell.Reduce(24),
            27 to StateJisonCell.Reduce(24),
            28 to StateJisonCell.Reduce(24),
            29 to StateJisonCell.Reduce(24),
            33 to StateJisonCell.Reduce(24),
            35 to StateJisonCell.Reduce(24),
            37 to StateJisonCell.Reduce(24),
            38 to StateJisonCell.Reduce(24),
            41 to StateJisonCell.Reduce(24),
            45 to StateJisonCell.Reduce(24),
            48 to StateJisonCell.Reduce(24),
            51 to StateJisonCell.Reduce(24),
            52 to StateJisonCell.Reduce(24),
            53 to StateJisonCell.Reduce(24),
            54 to StateJisonCell.Reduce(24),
            57 to StateJisonCell.Reduce(24),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(25),
            4 to StateJisonCell.Reduce(25),
            5 to StateJisonCell.Reduce(25),
            16 to StateJisonCell.Reduce(25),
            17 to StateJisonCell.Reduce(25),
            19 to StateJisonCell.Reduce(25),
            21 to StateJisonCell.Reduce(25),
            22 to StateJisonCell.Reduce(25),
            24 to StateJisonCell.Reduce(25),
            25 to StateJisonCell.Reduce(25),
            26 to StateJisonCell.Reduce(25),
            27 to StateJisonCell.Reduce(25),
            28 to StateJisonCell.Reduce(25),
            29 to StateJisonCell.Reduce(25),
            33 to StateJisonCell.Reduce(25),
            35 to StateJisonCell.Reduce(25),
            37 to StateJisonCell.Reduce(25),
            38 to StateJisonCell.Reduce(25),
            41 to StateJisonCell.Reduce(25),
            45 to StateJisonCell.Reduce(25),
            48 to StateJisonCell.Reduce(25),
            51 to StateJisonCell.Reduce(25),
            52 to StateJisonCell.Reduce(25),
            53 to StateJisonCell.Reduce(25),
            54 to StateJisonCell.Reduce(25),
            57 to StateJisonCell.Reduce(25),
        ),
        mapOf(
            30 to StateJisonCell.Goto(45),
            31 to StateJisonCell.Shift(46),
            59 to StateJisonCell.Shift(47),
            60 to StateJisonCell.Shift(48),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(28),
            4 to StateJisonCell.Reduce(28),
            5 to StateJisonCell.Reduce(28),
            16 to StateJisonCell.Reduce(28),
            17 to StateJisonCell.Reduce(28),
            19 to StateJisonCell.Reduce(28),
            21 to StateJisonCell.Reduce(28),
            22 to StateJisonCell.Reduce(28),
            24 to StateJisonCell.Reduce(28),
            25 to StateJisonCell.Reduce(28),
            26 to StateJisonCell.Reduce(28),
            27 to StateJisonCell.Reduce(28),
            28 to StateJisonCell.Reduce(28),
            29 to StateJisonCell.Reduce(28),
            33 to StateJisonCell.Reduce(28),
            35 to StateJisonCell.Reduce(28),
            37 to StateJisonCell.Reduce(28),
            38 to StateJisonCell.Reduce(28),
            41 to StateJisonCell.Reduce(28),
            45 to StateJisonCell.Reduce(28),
            48 to StateJisonCell.Reduce(28),
            51 to StateJisonCell.Reduce(28),
            52 to StateJisonCell.Reduce(28),
            53 to StateJisonCell.Reduce(28),
            54 to StateJisonCell.Reduce(28),
            57 to StateJisonCell.Reduce(28),
        ),
        mapOf(
            34 to StateJisonCell.Shift(49),
        ),
        mapOf(
            36 to StateJisonCell.Shift(50),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(31),
            4 to StateJisonCell.Reduce(31),
            5 to StateJisonCell.Reduce(31),
            16 to StateJisonCell.Reduce(31),
            17 to StateJisonCell.Reduce(31),
            19 to StateJisonCell.Reduce(31),
            21 to StateJisonCell.Reduce(31),
            22 to StateJisonCell.Reduce(31),
            24 to StateJisonCell.Reduce(31),
            25 to StateJisonCell.Reduce(31),
            26 to StateJisonCell.Reduce(31),
            27 to StateJisonCell.Reduce(31),
            28 to StateJisonCell.Reduce(31),
            29 to StateJisonCell.Reduce(31),
            33 to StateJisonCell.Reduce(31),
            35 to StateJisonCell.Reduce(31),
            37 to StateJisonCell.Reduce(31),
            38 to StateJisonCell.Reduce(31),
            41 to StateJisonCell.Reduce(31),
            45 to StateJisonCell.Reduce(31),
            48 to StateJisonCell.Reduce(31),
            51 to StateJisonCell.Reduce(31),
            52 to StateJisonCell.Reduce(31),
            53 to StateJisonCell.Reduce(31),
            54 to StateJisonCell.Reduce(31),
            57 to StateJisonCell.Reduce(31),
        ),
        mapOf(
            13 to StateJisonCell.Goto(51),
            24 to StateJisonCell.Shift(33),
            57 to StateJisonCell.Shift(34),
        ),
        mapOf(
            42 to StateJisonCell.Shift(52),
            44 to StateJisonCell.Shift(53),
        ),
        mapOf(
            46 to StateJisonCell.Shift(54),
        ),
        mapOf(
            49 to StateJisonCell.Shift(55),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(44),
            4 to StateJisonCell.Reduce(44),
            5 to StateJisonCell.Reduce(44),
            14 to StateJisonCell.Reduce(44),
            15 to StateJisonCell.Reduce(44),
            16 to StateJisonCell.Reduce(44),
            17 to StateJisonCell.Reduce(44),
            19 to StateJisonCell.Reduce(44),
            21 to StateJisonCell.Reduce(44),
            22 to StateJisonCell.Reduce(44),
            24 to StateJisonCell.Reduce(44),
            25 to StateJisonCell.Reduce(44),
            26 to StateJisonCell.Reduce(44),
            27 to StateJisonCell.Reduce(44),
            28 to StateJisonCell.Reduce(44),
            29 to StateJisonCell.Reduce(44),
            33 to StateJisonCell.Reduce(44),
            35 to StateJisonCell.Reduce(44),
            37 to StateJisonCell.Reduce(44),
            38 to StateJisonCell.Reduce(44),
            39 to StateJisonCell.Reduce(44),
            40 to StateJisonCell.Reduce(44),
            41 to StateJisonCell.Reduce(44),
            45 to StateJisonCell.Reduce(44),
            48 to StateJisonCell.Reduce(44),
            51 to StateJisonCell.Reduce(44),
            52 to StateJisonCell.Reduce(44),
            53 to StateJisonCell.Reduce(44),
            54 to StateJisonCell.Reduce(44),
            57 to StateJisonCell.Reduce(44),
            58 to StateJisonCell.Shift(56),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(45),
            4 to StateJisonCell.Reduce(45),
            5 to StateJisonCell.Reduce(45),
            14 to StateJisonCell.Reduce(45),
            15 to StateJisonCell.Reduce(45),
            16 to StateJisonCell.Reduce(45),
            17 to StateJisonCell.Reduce(45),
            19 to StateJisonCell.Reduce(45),
            21 to StateJisonCell.Reduce(45),
            22 to StateJisonCell.Reduce(45),
            24 to StateJisonCell.Reduce(45),
            25 to StateJisonCell.Reduce(45),
            26 to StateJisonCell.Reduce(45),
            27 to StateJisonCell.Reduce(45),
            28 to StateJisonCell.Reduce(45),
            29 to StateJisonCell.Reduce(45),
            33 to StateJisonCell.Reduce(45),
            35 to StateJisonCell.Reduce(45),
            37 to StateJisonCell.Reduce(45),
            38 to StateJisonCell.Reduce(45),
            39 to StateJisonCell.Reduce(45),
            40 to StateJisonCell.Reduce(45),
            41 to StateJisonCell.Reduce(45),
            45 to StateJisonCell.Reduce(45),
            48 to StateJisonCell.Reduce(45),
            51 to StateJisonCell.Reduce(45),
            52 to StateJisonCell.Reduce(45),
            53 to StateJisonCell.Reduce(45),
            54 to StateJisonCell.Reduce(45),
            57 to StateJisonCell.Reduce(45),
            58 to StateJisonCell.Shift(57),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(38),
            4 to StateJisonCell.Reduce(38),
            5 to StateJisonCell.Reduce(38),
            16 to StateJisonCell.Reduce(38),
            17 to StateJisonCell.Reduce(38),
            19 to StateJisonCell.Reduce(38),
            21 to StateJisonCell.Reduce(38),
            22 to StateJisonCell.Reduce(38),
            24 to StateJisonCell.Reduce(38),
            25 to StateJisonCell.Reduce(38),
            26 to StateJisonCell.Reduce(38),
            27 to StateJisonCell.Reduce(38),
            28 to StateJisonCell.Reduce(38),
            29 to StateJisonCell.Reduce(38),
            33 to StateJisonCell.Reduce(38),
            35 to StateJisonCell.Reduce(38),
            37 to StateJisonCell.Reduce(38),
            38 to StateJisonCell.Reduce(38),
            41 to StateJisonCell.Reduce(38),
            45 to StateJisonCell.Reduce(38),
            48 to StateJisonCell.Reduce(38),
            51 to StateJisonCell.Reduce(38),
            52 to StateJisonCell.Reduce(38),
            53 to StateJisonCell.Reduce(38),
            54 to StateJisonCell.Reduce(38),
            57 to StateJisonCell.Reduce(38),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(39),
            4 to StateJisonCell.Reduce(39),
            5 to StateJisonCell.Reduce(39),
            16 to StateJisonCell.Reduce(39),
            17 to StateJisonCell.Reduce(39),
            19 to StateJisonCell.Reduce(39),
            21 to StateJisonCell.Reduce(39),
            22 to StateJisonCell.Reduce(39),
            24 to StateJisonCell.Reduce(39),
            25 to StateJisonCell.Reduce(39),
            26 to StateJisonCell.Reduce(39),
            27 to StateJisonCell.Reduce(39),
            28 to StateJisonCell.Reduce(39),
            29 to StateJisonCell.Reduce(39),
            33 to StateJisonCell.Reduce(39),
            35 to StateJisonCell.Reduce(39),
            37 to StateJisonCell.Reduce(39),
            38 to StateJisonCell.Reduce(39),
            41 to StateJisonCell.Reduce(39),
            45 to StateJisonCell.Reduce(39),
            48 to StateJisonCell.Reduce(39),
            51 to StateJisonCell.Reduce(39),
            52 to StateJisonCell.Reduce(39),
            53 to StateJisonCell.Reduce(39),
            54 to StateJisonCell.Reduce(39),
            57 to StateJisonCell.Reduce(39),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(40),
            4 to StateJisonCell.Reduce(40),
            5 to StateJisonCell.Reduce(40),
            16 to StateJisonCell.Reduce(40),
            17 to StateJisonCell.Reduce(40),
            19 to StateJisonCell.Reduce(40),
            21 to StateJisonCell.Reduce(40),
            22 to StateJisonCell.Reduce(40),
            24 to StateJisonCell.Reduce(40),
            25 to StateJisonCell.Reduce(40),
            26 to StateJisonCell.Reduce(40),
            27 to StateJisonCell.Reduce(40),
            28 to StateJisonCell.Reduce(40),
            29 to StateJisonCell.Reduce(40),
            33 to StateJisonCell.Reduce(40),
            35 to StateJisonCell.Reduce(40),
            37 to StateJisonCell.Reduce(40),
            38 to StateJisonCell.Reduce(40),
            41 to StateJisonCell.Reduce(40),
            45 to StateJisonCell.Reduce(40),
            48 to StateJisonCell.Reduce(40),
            51 to StateJisonCell.Reduce(40),
            52 to StateJisonCell.Reduce(40),
            53 to StateJisonCell.Reduce(40),
            54 to StateJisonCell.Reduce(40),
            57 to StateJisonCell.Reduce(40),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(41),
            4 to StateJisonCell.Reduce(41),
            5 to StateJisonCell.Reduce(41),
            16 to StateJisonCell.Reduce(41),
            17 to StateJisonCell.Reduce(41),
            19 to StateJisonCell.Reduce(41),
            21 to StateJisonCell.Reduce(41),
            22 to StateJisonCell.Reduce(41),
            24 to StateJisonCell.Reduce(41),
            25 to StateJisonCell.Reduce(41),
            26 to StateJisonCell.Reduce(41),
            27 to StateJisonCell.Reduce(41),
            28 to StateJisonCell.Reduce(41),
            29 to StateJisonCell.Reduce(41),
            33 to StateJisonCell.Reduce(41),
            35 to StateJisonCell.Reduce(41),
            37 to StateJisonCell.Reduce(41),
            38 to StateJisonCell.Reduce(41),
            41 to StateJisonCell.Reduce(41),
            45 to StateJisonCell.Reduce(41),
            48 to StateJisonCell.Reduce(41),
            51 to StateJisonCell.Reduce(41),
            52 to StateJisonCell.Reduce(41),
            53 to StateJisonCell.Reduce(41),
            54 to StateJisonCell.Reduce(41),
            57 to StateJisonCell.Reduce(41),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(6),
            4 to StateJisonCell.Reduce(6),
            5 to StateJisonCell.Reduce(6),
            16 to StateJisonCell.Reduce(6),
            17 to StateJisonCell.Reduce(6),
            19 to StateJisonCell.Reduce(6),
            21 to StateJisonCell.Reduce(6),
            22 to StateJisonCell.Reduce(6),
            24 to StateJisonCell.Reduce(6),
            25 to StateJisonCell.Reduce(6),
            26 to StateJisonCell.Reduce(6),
            27 to StateJisonCell.Reduce(6),
            28 to StateJisonCell.Reduce(6),
            29 to StateJisonCell.Reduce(6),
            33 to StateJisonCell.Reduce(6),
            35 to StateJisonCell.Reduce(6),
            37 to StateJisonCell.Reduce(6),
            38 to StateJisonCell.Reduce(6),
            41 to StateJisonCell.Reduce(6),
            45 to StateJisonCell.Reduce(6),
            48 to StateJisonCell.Reduce(6),
            51 to StateJisonCell.Reduce(6),
            52 to StateJisonCell.Reduce(6),
            53 to StateJisonCell.Reduce(6),
            54 to StateJisonCell.Reduce(6),
            57 to StateJisonCell.Reduce(6),
        ),
    )

    private fun stateChunk2(): Array<Map<Int, StateJisonCell>> = arrayOf(
        mapOf(
            1 to StateJisonCell.Reduce(13),
            4 to StateJisonCell.Reduce(13),
            5 to StateJisonCell.Reduce(13),
            16 to StateJisonCell.Reduce(13),
            17 to StateJisonCell.Reduce(13),
            19 to StateJisonCell.Reduce(13),
            21 to StateJisonCell.Reduce(13),
            22 to StateJisonCell.Reduce(13),
            24 to StateJisonCell.Reduce(13),
            25 to StateJisonCell.Reduce(13),
            26 to StateJisonCell.Reduce(13),
            27 to StateJisonCell.Reduce(13),
            28 to StateJisonCell.Reduce(13),
            29 to StateJisonCell.Reduce(13),
            33 to StateJisonCell.Reduce(13),
            35 to StateJisonCell.Reduce(13),
            37 to StateJisonCell.Reduce(13),
            38 to StateJisonCell.Reduce(13),
            41 to StateJisonCell.Reduce(13),
            45 to StateJisonCell.Reduce(13),
            48 to StateJisonCell.Reduce(13),
            51 to StateJisonCell.Reduce(13),
            52 to StateJisonCell.Reduce(13),
            53 to StateJisonCell.Reduce(13),
            54 to StateJisonCell.Reduce(13),
            57 to StateJisonCell.Reduce(13),
        ),
        mapOf(
            13 to StateJisonCell.Goto(58),
            24 to StateJisonCell.Shift(33),
            57 to StateJisonCell.Shift(34),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(17),
            4 to StateJisonCell.Reduce(17),
            5 to StateJisonCell.Reduce(17),
            16 to StateJisonCell.Reduce(17),
            17 to StateJisonCell.Reduce(17),
            19 to StateJisonCell.Reduce(17),
            21 to StateJisonCell.Reduce(17),
            22 to StateJisonCell.Reduce(17),
            24 to StateJisonCell.Reduce(17),
            25 to StateJisonCell.Reduce(17),
            26 to StateJisonCell.Reduce(17),
            27 to StateJisonCell.Reduce(17),
            28 to StateJisonCell.Reduce(17),
            29 to StateJisonCell.Reduce(17),
            33 to StateJisonCell.Reduce(17),
            35 to StateJisonCell.Reduce(17),
            37 to StateJisonCell.Reduce(17),
            38 to StateJisonCell.Reduce(17),
            41 to StateJisonCell.Reduce(17),
            45 to StateJisonCell.Reduce(17),
            48 to StateJisonCell.Reduce(17),
            51 to StateJisonCell.Reduce(17),
            52 to StateJisonCell.Reduce(17),
            53 to StateJisonCell.Reduce(17),
            54 to StateJisonCell.Reduce(17),
            57 to StateJisonCell.Reduce(17),
        ),
        mapOf(
            4 to StateJisonCell.Reduce(4),
            5 to StateJisonCell.Reduce(4),
            7 to StateJisonCell.Goto(59),
            16 to StateJisonCell.Reduce(4),
            17 to StateJisonCell.Reduce(4),
            19 to StateJisonCell.Reduce(4),
            21 to StateJisonCell.Reduce(4),
            22 to StateJisonCell.Reduce(4),
            24 to StateJisonCell.Reduce(4),
            25 to StateJisonCell.Reduce(4),
            26 to StateJisonCell.Reduce(4),
            27 to StateJisonCell.Reduce(4),
            28 to StateJisonCell.Reduce(4),
            29 to StateJisonCell.Reduce(4),
            33 to StateJisonCell.Reduce(4),
            35 to StateJisonCell.Reduce(4),
            37 to StateJisonCell.Reduce(4),
            38 to StateJisonCell.Reduce(4),
            41 to StateJisonCell.Reduce(4),
            45 to StateJisonCell.Reduce(4),
            48 to StateJisonCell.Reduce(4),
            51 to StateJisonCell.Reduce(4),
            52 to StateJisonCell.Reduce(4),
            53 to StateJisonCell.Reduce(4),
            54 to StateJisonCell.Reduce(4),
            57 to StateJisonCell.Reduce(4),
        ),
        mapOf(
            24 to StateJisonCell.Shift(60),
        ),
        mapOf(
            24 to StateJisonCell.Shift(61),
        ),
        mapOf(
            23 to StateJisonCell.Shift(62),
        ),
        mapOf(
            24 to StateJisonCell.Reduce(48),
        ),
        mapOf(
            24 to StateJisonCell.Reduce(49),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(29),
            4 to StateJisonCell.Reduce(29),
            5 to StateJisonCell.Reduce(29),
            16 to StateJisonCell.Reduce(29),
            17 to StateJisonCell.Reduce(29),
            19 to StateJisonCell.Reduce(29),
            21 to StateJisonCell.Reduce(29),
            22 to StateJisonCell.Reduce(29),
            24 to StateJisonCell.Reduce(29),
            25 to StateJisonCell.Reduce(29),
            26 to StateJisonCell.Reduce(29),
            27 to StateJisonCell.Reduce(29),
            28 to StateJisonCell.Reduce(29),
            29 to StateJisonCell.Reduce(29),
            33 to StateJisonCell.Reduce(29),
            35 to StateJisonCell.Reduce(29),
            37 to StateJisonCell.Reduce(29),
            38 to StateJisonCell.Reduce(29),
            41 to StateJisonCell.Reduce(29),
            45 to StateJisonCell.Reduce(29),
            48 to StateJisonCell.Reduce(29),
            51 to StateJisonCell.Reduce(29),
            52 to StateJisonCell.Reduce(29),
            53 to StateJisonCell.Reduce(29),
            54 to StateJisonCell.Reduce(29),
            57 to StateJisonCell.Reduce(29),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(30),
            4 to StateJisonCell.Reduce(30),
            5 to StateJisonCell.Reduce(30),
            16 to StateJisonCell.Reduce(30),
            17 to StateJisonCell.Reduce(30),
            19 to StateJisonCell.Reduce(30),
            21 to StateJisonCell.Reduce(30),
            22 to StateJisonCell.Reduce(30),
            24 to StateJisonCell.Reduce(30),
            25 to StateJisonCell.Reduce(30),
            26 to StateJisonCell.Reduce(30),
            27 to StateJisonCell.Reduce(30),
            28 to StateJisonCell.Reduce(30),
            29 to StateJisonCell.Reduce(30),
            33 to StateJisonCell.Reduce(30),
            35 to StateJisonCell.Reduce(30),
            37 to StateJisonCell.Reduce(30),
            38 to StateJisonCell.Reduce(30),
            41 to StateJisonCell.Reduce(30),
            45 to StateJisonCell.Reduce(30),
            48 to StateJisonCell.Reduce(30),
            51 to StateJisonCell.Reduce(30),
            52 to StateJisonCell.Reduce(30),
            53 to StateJisonCell.Reduce(30),
            54 to StateJisonCell.Reduce(30),
            57 to StateJisonCell.Reduce(30),
        ),
        mapOf(
            39 to StateJisonCell.Shift(63),
            40 to StateJisonCell.Shift(64),
        ),
        mapOf(
            43 to StateJisonCell.Shift(65),
        ),
        mapOf(
            43 to StateJisonCell.Shift(66),
        ),
        mapOf(
            47 to StateJisonCell.Shift(67),
        ),
        mapOf(
            50 to StateJisonCell.Shift(68),
        ),
        mapOf(
            24 to StateJisonCell.Shift(69),
        ),
        mapOf(
            24 to StateJisonCell.Shift(70),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(14),
            4 to StateJisonCell.Reduce(14),
            5 to StateJisonCell.Reduce(14),
            14 to StateJisonCell.Shift(71),
            16 to StateJisonCell.Reduce(14),
            17 to StateJisonCell.Reduce(14),
            19 to StateJisonCell.Reduce(14),
            21 to StateJisonCell.Reduce(14),
            22 to StateJisonCell.Reduce(14),
            24 to StateJisonCell.Reduce(14),
            25 to StateJisonCell.Reduce(14),
            26 to StateJisonCell.Reduce(14),
            27 to StateJisonCell.Reduce(14),
            28 to StateJisonCell.Reduce(14),
            29 to StateJisonCell.Reduce(14),
            33 to StateJisonCell.Reduce(14),
            35 to StateJisonCell.Reduce(14),
            37 to StateJisonCell.Reduce(14),
            38 to StateJisonCell.Reduce(14),
            41 to StateJisonCell.Reduce(14),
            45 to StateJisonCell.Reduce(14),
            48 to StateJisonCell.Reduce(14),
            51 to StateJisonCell.Reduce(14),
            52 to StateJisonCell.Reduce(14),
            53 to StateJisonCell.Reduce(14),
            54 to StateJisonCell.Reduce(14),
            57 to StateJisonCell.Reduce(14),
        ),
        mapOf(
            4 to StateJisonCell.Shift(9),
            5 to StateJisonCell.Shift(11),
            8 to StateJisonCell.Goto(8),
            9 to StateJisonCell.Goto(10),
            10 to StateJisonCell.Goto(12),
            11 to StateJisonCell.Goto(13),
            12 to StateJisonCell.Goto(14),
            13 to StateJisonCell.Goto(15),
            16 to StateJisonCell.Shift(16),
            17 to StateJisonCell.Shift(17),
            19 to StateJisonCell.Shift(18),
            21 to StateJisonCell.Shift(72),
            22 to StateJisonCell.Shift(19),
            24 to StateJisonCell.Shift(33),
            25 to StateJisonCell.Shift(20),
            26 to StateJisonCell.Shift(21),
            27 to StateJisonCell.Shift(22),
            28 to StateJisonCell.Shift(23),
            29 to StateJisonCell.Shift(24),
            32 to StateJisonCell.Goto(25),
            33 to StateJisonCell.Shift(26),
            35 to StateJisonCell.Shift(27),
            37 to StateJisonCell.Shift(28),
            38 to StateJisonCell.Shift(29),
            41 to StateJisonCell.Shift(30),
            45 to StateJisonCell.Shift(31),
            48 to StateJisonCell.Shift(32),
            51 to StateJisonCell.Shift(35),
            52 to StateJisonCell.Shift(36),
            53 to StateJisonCell.Shift(37),
            54 to StateJisonCell.Shift(38),
            57 to StateJisonCell.Shift(34),
        ),
    )

    private fun stateChunk3(): Array<Map<Int, StateJisonCell>> = arrayOf(
        mapOf(
            1 to StateJisonCell.Reduce(20),
            4 to StateJisonCell.Reduce(20),
            5 to StateJisonCell.Reduce(20),
            16 to StateJisonCell.Reduce(20),
            17 to StateJisonCell.Reduce(20),
            19 to StateJisonCell.Reduce(20),
            20 to StateJisonCell.Shift(73),
            21 to StateJisonCell.Reduce(20),
            22 to StateJisonCell.Reduce(20),
            24 to StateJisonCell.Reduce(20),
            25 to StateJisonCell.Reduce(20),
            26 to StateJisonCell.Reduce(20),
            27 to StateJisonCell.Reduce(20),
            28 to StateJisonCell.Reduce(20),
            29 to StateJisonCell.Reduce(20),
            33 to StateJisonCell.Reduce(20),
            35 to StateJisonCell.Reduce(20),
            37 to StateJisonCell.Reduce(20),
            38 to StateJisonCell.Reduce(20),
            41 to StateJisonCell.Reduce(20),
            45 to StateJisonCell.Reduce(20),
            48 to StateJisonCell.Reduce(20),
            51 to StateJisonCell.Reduce(20),
            52 to StateJisonCell.Reduce(20),
            53 to StateJisonCell.Reduce(20),
            54 to StateJisonCell.Reduce(20),
            57 to StateJisonCell.Reduce(20),
        ),
        mapOf(
            31 to StateJisonCell.Shift(74),
        ),
        mapOf(
            24 to StateJisonCell.Shift(75),
        ),
        mapOf(
            39 to StateJisonCell.Shift(76),
        ),
        mapOf(
            39 to StateJisonCell.Shift(77),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(34),
            4 to StateJisonCell.Reduce(34),
            5 to StateJisonCell.Reduce(34),
            16 to StateJisonCell.Reduce(34),
            17 to StateJisonCell.Reduce(34),
            19 to StateJisonCell.Reduce(34),
            21 to StateJisonCell.Reduce(34),
            22 to StateJisonCell.Reduce(34),
            24 to StateJisonCell.Reduce(34),
            25 to StateJisonCell.Reduce(34),
            26 to StateJisonCell.Reduce(34),
            27 to StateJisonCell.Reduce(34),
            28 to StateJisonCell.Reduce(34),
            29 to StateJisonCell.Reduce(34),
            33 to StateJisonCell.Reduce(34),
            35 to StateJisonCell.Reduce(34),
            37 to StateJisonCell.Reduce(34),
            38 to StateJisonCell.Reduce(34),
            41 to StateJisonCell.Reduce(34),
            45 to StateJisonCell.Reduce(34),
            48 to StateJisonCell.Reduce(34),
            51 to StateJisonCell.Reduce(34),
            52 to StateJisonCell.Reduce(34),
            53 to StateJisonCell.Reduce(34),
            54 to StateJisonCell.Reduce(34),
            57 to StateJisonCell.Reduce(34),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(35),
            4 to StateJisonCell.Reduce(35),
            5 to StateJisonCell.Reduce(35),
            16 to StateJisonCell.Reduce(35),
            17 to StateJisonCell.Reduce(35),
            19 to StateJisonCell.Reduce(35),
            21 to StateJisonCell.Reduce(35),
            22 to StateJisonCell.Reduce(35),
            24 to StateJisonCell.Reduce(35),
            25 to StateJisonCell.Reduce(35),
            26 to StateJisonCell.Reduce(35),
            27 to StateJisonCell.Reduce(35),
            28 to StateJisonCell.Reduce(35),
            29 to StateJisonCell.Reduce(35),
            33 to StateJisonCell.Reduce(35),
            35 to StateJisonCell.Reduce(35),
            37 to StateJisonCell.Reduce(35),
            38 to StateJisonCell.Reduce(35),
            41 to StateJisonCell.Reduce(35),
            45 to StateJisonCell.Reduce(35),
            48 to StateJisonCell.Reduce(35),
            51 to StateJisonCell.Reduce(35),
            52 to StateJisonCell.Reduce(35),
            53 to StateJisonCell.Reduce(35),
            54 to StateJisonCell.Reduce(35),
            57 to StateJisonCell.Reduce(35),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(36),
            4 to StateJisonCell.Reduce(36),
            5 to StateJisonCell.Reduce(36),
            16 to StateJisonCell.Reduce(36),
            17 to StateJisonCell.Reduce(36),
            19 to StateJisonCell.Reduce(36),
            21 to StateJisonCell.Reduce(36),
            22 to StateJisonCell.Reduce(36),
            24 to StateJisonCell.Reduce(36),
            25 to StateJisonCell.Reduce(36),
            26 to StateJisonCell.Reduce(36),
            27 to StateJisonCell.Reduce(36),
            28 to StateJisonCell.Reduce(36),
            29 to StateJisonCell.Reduce(36),
            33 to StateJisonCell.Reduce(36),
            35 to StateJisonCell.Reduce(36),
            37 to StateJisonCell.Reduce(36),
            38 to StateJisonCell.Reduce(36),
            41 to StateJisonCell.Reduce(36),
            45 to StateJisonCell.Reduce(36),
            48 to StateJisonCell.Reduce(36),
            51 to StateJisonCell.Reduce(36),
            52 to StateJisonCell.Reduce(36),
            53 to StateJisonCell.Reduce(36),
            54 to StateJisonCell.Reduce(36),
            57 to StateJisonCell.Reduce(36),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(37),
            4 to StateJisonCell.Reduce(37),
            5 to StateJisonCell.Reduce(37),
            16 to StateJisonCell.Reduce(37),
            17 to StateJisonCell.Reduce(37),
            19 to StateJisonCell.Reduce(37),
            21 to StateJisonCell.Reduce(37),
            22 to StateJisonCell.Reduce(37),
            24 to StateJisonCell.Reduce(37),
            25 to StateJisonCell.Reduce(37),
            26 to StateJisonCell.Reduce(37),
            27 to StateJisonCell.Reduce(37),
            28 to StateJisonCell.Reduce(37),
            29 to StateJisonCell.Reduce(37),
            33 to StateJisonCell.Reduce(37),
            35 to StateJisonCell.Reduce(37),
            37 to StateJisonCell.Reduce(37),
            38 to StateJisonCell.Reduce(37),
            41 to StateJisonCell.Reduce(37),
            45 to StateJisonCell.Reduce(37),
            48 to StateJisonCell.Reduce(37),
            51 to StateJisonCell.Reduce(37),
            52 to StateJisonCell.Reduce(37),
            53 to StateJisonCell.Reduce(37),
            54 to StateJisonCell.Reduce(37),
            57 to StateJisonCell.Reduce(37),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(46),
            4 to StateJisonCell.Reduce(46),
            5 to StateJisonCell.Reduce(46),
            14 to StateJisonCell.Reduce(46),
            15 to StateJisonCell.Reduce(46),
            16 to StateJisonCell.Reduce(46),
            17 to StateJisonCell.Reduce(46),
            19 to StateJisonCell.Reduce(46),
            21 to StateJisonCell.Reduce(46),
            22 to StateJisonCell.Reduce(46),
            24 to StateJisonCell.Reduce(46),
            25 to StateJisonCell.Reduce(46),
            26 to StateJisonCell.Reduce(46),
            27 to StateJisonCell.Reduce(46),
            28 to StateJisonCell.Reduce(46),
            29 to StateJisonCell.Reduce(46),
            33 to StateJisonCell.Reduce(46),
            35 to StateJisonCell.Reduce(46),
            37 to StateJisonCell.Reduce(46),
            38 to StateJisonCell.Reduce(46),
            39 to StateJisonCell.Reduce(46),
            40 to StateJisonCell.Reduce(46),
            41 to StateJisonCell.Reduce(46),
            45 to StateJisonCell.Reduce(46),
            48 to StateJisonCell.Reduce(46),
            51 to StateJisonCell.Reduce(46),
            52 to StateJisonCell.Reduce(46),
            53 to StateJisonCell.Reduce(46),
            54 to StateJisonCell.Reduce(46),
            57 to StateJisonCell.Reduce(46),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(47),
            4 to StateJisonCell.Reduce(47),
            5 to StateJisonCell.Reduce(47),
            14 to StateJisonCell.Reduce(47),
            15 to StateJisonCell.Reduce(47),
            16 to StateJisonCell.Reduce(47),
            17 to StateJisonCell.Reduce(47),
            19 to StateJisonCell.Reduce(47),
            21 to StateJisonCell.Reduce(47),
            22 to StateJisonCell.Reduce(47),
            24 to StateJisonCell.Reduce(47),
            25 to StateJisonCell.Reduce(47),
            26 to StateJisonCell.Reduce(47),
            27 to StateJisonCell.Reduce(47),
            28 to StateJisonCell.Reduce(47),
            29 to StateJisonCell.Reduce(47),
            33 to StateJisonCell.Reduce(47),
            35 to StateJisonCell.Reduce(47),
            37 to StateJisonCell.Reduce(47),
            38 to StateJisonCell.Reduce(47),
            39 to StateJisonCell.Reduce(47),
            40 to StateJisonCell.Reduce(47),
            41 to StateJisonCell.Reduce(47),
            45 to StateJisonCell.Reduce(47),
            48 to StateJisonCell.Reduce(47),
            51 to StateJisonCell.Reduce(47),
            52 to StateJisonCell.Reduce(47),
            53 to StateJisonCell.Reduce(47),
            54 to StateJisonCell.Reduce(47),
            57 to StateJisonCell.Reduce(47),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(15),
            4 to StateJisonCell.Reduce(15),
            5 to StateJisonCell.Reduce(15),
            16 to StateJisonCell.Reduce(15),
            17 to StateJisonCell.Reduce(15),
            19 to StateJisonCell.Reduce(15),
            21 to StateJisonCell.Reduce(15),
            22 to StateJisonCell.Reduce(15),
            24 to StateJisonCell.Reduce(15),
            25 to StateJisonCell.Reduce(15),
            26 to StateJisonCell.Reduce(15),
            27 to StateJisonCell.Reduce(15),
            28 to StateJisonCell.Reduce(15),
            29 to StateJisonCell.Reduce(15),
            33 to StateJisonCell.Reduce(15),
            35 to StateJisonCell.Reduce(15),
            37 to StateJisonCell.Reduce(15),
            38 to StateJisonCell.Reduce(15),
            41 to StateJisonCell.Reduce(15),
            45 to StateJisonCell.Reduce(15),
            48 to StateJisonCell.Reduce(15),
            51 to StateJisonCell.Reduce(15),
            52 to StateJisonCell.Reduce(15),
            53 to StateJisonCell.Reduce(15),
            54 to StateJisonCell.Reduce(15),
            57 to StateJisonCell.Reduce(15),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(19),
            4 to StateJisonCell.Reduce(19),
            5 to StateJisonCell.Reduce(19),
            16 to StateJisonCell.Reduce(19),
            17 to StateJisonCell.Reduce(19),
            19 to StateJisonCell.Reduce(19),
            21 to StateJisonCell.Reduce(19),
            22 to StateJisonCell.Reduce(19),
            24 to StateJisonCell.Reduce(19),
            25 to StateJisonCell.Reduce(19),
            26 to StateJisonCell.Reduce(19),
            27 to StateJisonCell.Reduce(19),
            28 to StateJisonCell.Reduce(19),
            29 to StateJisonCell.Reduce(19),
            33 to StateJisonCell.Reduce(19),
            35 to StateJisonCell.Reduce(19),
            37 to StateJisonCell.Reduce(19),
            38 to StateJisonCell.Reduce(19),
            41 to StateJisonCell.Reduce(19),
            45 to StateJisonCell.Reduce(19),
            48 to StateJisonCell.Reduce(19),
            51 to StateJisonCell.Reduce(19),
            52 to StateJisonCell.Reduce(19),
            53 to StateJisonCell.Reduce(19),
            54 to StateJisonCell.Reduce(19),
            57 to StateJisonCell.Reduce(19),
        ),
        mapOf(
            4 to StateJisonCell.Reduce(4),
            5 to StateJisonCell.Reduce(4),
            7 to StateJisonCell.Goto(78),
            16 to StateJisonCell.Reduce(4),
            17 to StateJisonCell.Reduce(4),
            19 to StateJisonCell.Reduce(4),
            21 to StateJisonCell.Reduce(4),
            22 to StateJisonCell.Reduce(4),
            24 to StateJisonCell.Reduce(4),
            25 to StateJisonCell.Reduce(4),
            26 to StateJisonCell.Reduce(4),
            27 to StateJisonCell.Reduce(4),
            28 to StateJisonCell.Reduce(4),
            29 to StateJisonCell.Reduce(4),
            33 to StateJisonCell.Reduce(4),
            35 to StateJisonCell.Reduce(4),
            37 to StateJisonCell.Reduce(4),
            38 to StateJisonCell.Reduce(4),
            41 to StateJisonCell.Reduce(4),
            45 to StateJisonCell.Reduce(4),
            48 to StateJisonCell.Reduce(4),
            51 to StateJisonCell.Reduce(4),
            52 to StateJisonCell.Reduce(4),
            53 to StateJisonCell.Reduce(4),
            54 to StateJisonCell.Reduce(4),
            57 to StateJisonCell.Reduce(4),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(26),
            4 to StateJisonCell.Reduce(26),
            5 to StateJisonCell.Reduce(26),
            16 to StateJisonCell.Reduce(26),
            17 to StateJisonCell.Reduce(26),
            19 to StateJisonCell.Reduce(26),
            21 to StateJisonCell.Reduce(26),
            22 to StateJisonCell.Reduce(26),
            24 to StateJisonCell.Reduce(26),
            25 to StateJisonCell.Reduce(26),
            26 to StateJisonCell.Reduce(26),
            27 to StateJisonCell.Reduce(26),
            28 to StateJisonCell.Reduce(26),
            29 to StateJisonCell.Reduce(26),
            33 to StateJisonCell.Reduce(26),
            35 to StateJisonCell.Reduce(26),
            37 to StateJisonCell.Reduce(26),
            38 to StateJisonCell.Reduce(26),
            41 to StateJisonCell.Reduce(26),
            45 to StateJisonCell.Reduce(26),
            48 to StateJisonCell.Reduce(26),
            51 to StateJisonCell.Reduce(26),
            52 to StateJisonCell.Reduce(26),
            53 to StateJisonCell.Reduce(26),
            54 to StateJisonCell.Reduce(26),
            57 to StateJisonCell.Reduce(26),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(27),
            4 to StateJisonCell.Reduce(27),
            5 to StateJisonCell.Reduce(27),
            16 to StateJisonCell.Reduce(27),
            17 to StateJisonCell.Reduce(27),
            19 to StateJisonCell.Reduce(27),
            21 to StateJisonCell.Reduce(27),
            22 to StateJisonCell.Reduce(27),
            24 to StateJisonCell.Reduce(27),
            25 to StateJisonCell.Reduce(27),
            26 to StateJisonCell.Reduce(27),
            27 to StateJisonCell.Reduce(27),
            28 to StateJisonCell.Reduce(27),
            29 to StateJisonCell.Reduce(27),
            33 to StateJisonCell.Reduce(27),
            35 to StateJisonCell.Reduce(27),
            37 to StateJisonCell.Reduce(27),
            38 to StateJisonCell.Reduce(27),
            41 to StateJisonCell.Reduce(27),
            45 to StateJisonCell.Reduce(27),
            48 to StateJisonCell.Reduce(27),
            51 to StateJisonCell.Reduce(27),
            52 to StateJisonCell.Reduce(27),
            53 to StateJisonCell.Reduce(27),
            54 to StateJisonCell.Reduce(27),
            57 to StateJisonCell.Reduce(27),
        ),
        mapOf(
            5 to StateJisonCell.Shift(79),
        ),
        mapOf(
            5 to StateJisonCell.Shift(80),
        ),
        mapOf(
            4 to StateJisonCell.Shift(9),
            5 to StateJisonCell.Shift(11),
            8 to StateJisonCell.Goto(8),
            9 to StateJisonCell.Goto(10),
            10 to StateJisonCell.Goto(12),
            11 to StateJisonCell.Goto(13),
            12 to StateJisonCell.Goto(14),
            13 to StateJisonCell.Goto(15),
            16 to StateJisonCell.Shift(16),
            17 to StateJisonCell.Shift(17),
            19 to StateJisonCell.Shift(18),
            21 to StateJisonCell.Shift(81),
            22 to StateJisonCell.Shift(19),
            24 to StateJisonCell.Shift(33),
            25 to StateJisonCell.Shift(20),
            26 to StateJisonCell.Shift(21),
            27 to StateJisonCell.Shift(22),
            28 to StateJisonCell.Shift(23),
            29 to StateJisonCell.Shift(24),
            32 to StateJisonCell.Goto(25),
            33 to StateJisonCell.Shift(26),
            35 to StateJisonCell.Shift(27),
            37 to StateJisonCell.Shift(28),
            38 to StateJisonCell.Shift(29),
            41 to StateJisonCell.Shift(30),
            45 to StateJisonCell.Shift(31),
            48 to StateJisonCell.Shift(32),
            51 to StateJisonCell.Shift(35),
            52 to StateJisonCell.Shift(36),
            53 to StateJisonCell.Shift(37),
            54 to StateJisonCell.Shift(38),
            57 to StateJisonCell.Shift(34),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(32),
            4 to StateJisonCell.Reduce(32),
            5 to StateJisonCell.Reduce(32),
            16 to StateJisonCell.Reduce(32),
            17 to StateJisonCell.Reduce(32),
            19 to StateJisonCell.Reduce(32),
            21 to StateJisonCell.Reduce(32),
            22 to StateJisonCell.Reduce(32),
            24 to StateJisonCell.Reduce(32),
            25 to StateJisonCell.Reduce(32),
            26 to StateJisonCell.Reduce(32),
            27 to StateJisonCell.Reduce(32),
            28 to StateJisonCell.Reduce(32),
            29 to StateJisonCell.Reduce(32),
            33 to StateJisonCell.Reduce(32),
            35 to StateJisonCell.Reduce(32),
            37 to StateJisonCell.Reduce(32),
            38 to StateJisonCell.Reduce(32),
            41 to StateJisonCell.Reduce(32),
            45 to StateJisonCell.Reduce(32),
            48 to StateJisonCell.Reduce(32),
            51 to StateJisonCell.Reduce(32),
            52 to StateJisonCell.Reduce(32),
            53 to StateJisonCell.Reduce(32),
            54 to StateJisonCell.Reduce(32),
            57 to StateJisonCell.Reduce(32),
        ),
    )

    private fun stateChunk4(): Array<Map<Int, StateJisonCell>> = arrayOf(
        mapOf(
            1 to StateJisonCell.Reduce(33),
            4 to StateJisonCell.Reduce(33),
            5 to StateJisonCell.Reduce(33),
            16 to StateJisonCell.Reduce(33),
            17 to StateJisonCell.Reduce(33),
            19 to StateJisonCell.Reduce(33),
            21 to StateJisonCell.Reduce(33),
            22 to StateJisonCell.Reduce(33),
            24 to StateJisonCell.Reduce(33),
            25 to StateJisonCell.Reduce(33),
            26 to StateJisonCell.Reduce(33),
            27 to StateJisonCell.Reduce(33),
            28 to StateJisonCell.Reduce(33),
            29 to StateJisonCell.Reduce(33),
            33 to StateJisonCell.Reduce(33),
            35 to StateJisonCell.Reduce(33),
            37 to StateJisonCell.Reduce(33),
            38 to StateJisonCell.Reduce(33),
            41 to StateJisonCell.Reduce(33),
            45 to StateJisonCell.Reduce(33),
            48 to StateJisonCell.Reduce(33),
            51 to StateJisonCell.Reduce(33),
            52 to StateJisonCell.Reduce(33),
            53 to StateJisonCell.Reduce(33),
            54 to StateJisonCell.Reduce(33),
            57 to StateJisonCell.Reduce(33),
        ),
        mapOf(
            1 to StateJisonCell.Reduce(21),
            4 to StateJisonCell.Reduce(21),
            5 to StateJisonCell.Reduce(21),
            16 to StateJisonCell.Reduce(21),
            17 to StateJisonCell.Reduce(21),
            19 to StateJisonCell.Reduce(21),
            21 to StateJisonCell.Reduce(21),
            22 to StateJisonCell.Reduce(21),
            24 to StateJisonCell.Reduce(21),
            25 to StateJisonCell.Reduce(21),
            26 to StateJisonCell.Reduce(21),
            27 to StateJisonCell.Reduce(21),
            28 to StateJisonCell.Reduce(21),
            29 to StateJisonCell.Reduce(21),
            33 to StateJisonCell.Reduce(21),
            35 to StateJisonCell.Reduce(21),
            37 to StateJisonCell.Reduce(21),
            38 to StateJisonCell.Reduce(21),
            41 to StateJisonCell.Reduce(21),
            45 to StateJisonCell.Reduce(21),
            48 to StateJisonCell.Reduce(21),
            51 to StateJisonCell.Reduce(21),
            52 to StateJisonCell.Reduce(21),
            53 to StateJisonCell.Reduce(21),
            54 to StateJisonCell.Reduce(21),
            57 to StateJisonCell.Reduce(21),
        ),
    )

    val lexerPatterns: List<StateJisonLexerPattern> = buildList {
        addAll(lexerChunk0())
        addAll(lexerChunk1())
        addAll(lexerChunk2())
        addAll(lexerChunk3())
    }

    private fun lexerChunk0(): List<StateJisonLexerPattern> = listOf(
        StateJisonLexerPattern(0, "^(?:click\\b)"),
        StateJisonLexerPattern(1, "^(?:href\\b)"),
        StateJisonLexerPattern(2, "^(?:\"[^\"]*\")"),
        StateJisonLexerPattern(3, "^(?:default\\b)"),
        StateJisonLexerPattern(4, "^(?:.*direction\\s+TB[^\\n]*)"),
        StateJisonLexerPattern(5, "^(?:.*direction\\s+BT[^\\n]*)"),
        StateJisonLexerPattern(6, "^(?:.*direction\\s+RL[^\\n]*)"),
        StateJisonLexerPattern(7, "^(?:.*direction\\s+LR[^\\n]*)"),
        StateJisonLexerPattern(8, "^(?:[\\n]+)"),
        StateJisonLexerPattern(9, "^(?:[\\s]+)"),
        StateJisonLexerPattern(10, "^(?:((?!\\n)\\s)+)"),
        StateJisonLexerPattern(11, "^(?:#[^\\n]*)"),
        StateJisonLexerPattern(12, "^(?:%%(?!\\{)[^\\n]*)"),
        StateJisonLexerPattern(13, "^(?:scale\\s+)"),
        StateJisonLexerPattern(14, "^(?:\\d+)"),
        StateJisonLexerPattern(15, "^(?:\\s+width\\b)"),
        StateJisonLexerPattern(16, "^(?:accTitle\\s*:\\s*)"),
        StateJisonLexerPattern(17, "^(?:(?!\\n||)*[^\\n]*)"),
        StateJisonLexerPattern(18, "^(?:accDescr\\s*:\\s*)"),
        StateJisonLexerPattern(19, "^(?:(?!\\n||)*[^\\n]*)"),
    )

    private fun lexerChunk1(): List<StateJisonLexerPattern> = listOf(
        StateJisonLexerPattern(20, "^(?:accDescr\\s*\\{\\s*)"),
        StateJisonLexerPattern(21, "^(?:[\\}])"),
        StateJisonLexerPattern(22, "^(?:[^\\}]*)"),
        StateJisonLexerPattern(23, "^(?:classDef\\s+)"),
        StateJisonLexerPattern(24, "^(?:DEFAULT\\s+)"),
        StateJisonLexerPattern(25, "^(?:\\w+\\s+)"),
        StateJisonLexerPattern(26, "^(?:[^\\n]*)"),
        StateJisonLexerPattern(27, "^(?:class\\s+)"),
        StateJisonLexerPattern(28, "^(?:(\\w+)+((,\\s*\\w+)*))"),
        StateJisonLexerPattern(29, "^(?:[^\\n]*)"),
        StateJisonLexerPattern(30, "^(?:style\\s+)"),
        StateJisonLexerPattern(31, "^(?:[\\w,]+\\s+)"),
        StateJisonLexerPattern(32, "^(?:[^\\n]*)"),
        StateJisonLexerPattern(33, "^(?:scale\\s+)"),
        StateJisonLexerPattern(34, "^(?:\\d+)"),
        StateJisonLexerPattern(35, "^(?:\\s+width\\b)"),
        StateJisonLexerPattern(36, "^(?:state\\s+)"),
        StateJisonLexerPattern(37, "^(?:.*<<fork>>)"),
        StateJisonLexerPattern(38, "^(?:.*<<join>>)"),
        StateJisonLexerPattern(39, "^(?:.*<<choice>>)"),
    )

    private fun lexerChunk2(): List<StateJisonLexerPattern> = listOf(
        StateJisonLexerPattern(40, "^(?:.*\\[\\[fork\\]\\])"),
        StateJisonLexerPattern(41, "^(?:.*\\[\\[join\\]\\])"),
        StateJisonLexerPattern(42, "^(?:.*\\[\\[choice\\]\\])"),
        StateJisonLexerPattern(43, "^(?:.*direction\\s+TB[^\\n]*)"),
        StateJisonLexerPattern(44, "^(?:.*direction\\s+BT[^\\n]*)"),
        StateJisonLexerPattern(45, "^(?:.*direction\\s+RL[^\\n]*)"),
        StateJisonLexerPattern(46, "^(?:.*direction\\s+LR[^\\n]*)"),
        StateJisonLexerPattern(47, "^(?:[\"])"),
        StateJisonLexerPattern(48, "^(?:\\s*as\\s+)"),
        StateJisonLexerPattern(49, "^(?:[^\\n\\{]*)"),
        StateJisonLexerPattern(50, "^(?:[\"])"),
        StateJisonLexerPattern(51, "^(?:[^\"]*)"),
        StateJisonLexerPattern(52, "^(?:\\w+\\s+\\w+.*?\\{)"),
        StateJisonLexerPattern(53, "^(?:[^\\n\\s\\{]+)"),
        StateJisonLexerPattern(54, "^(?:\\n)"),
        StateJisonLexerPattern(55, "^(?:\\{)"),
        StateJisonLexerPattern(56, "^(?:\\})"),
        StateJisonLexerPattern(57, "^(?:[\\n])"),
        StateJisonLexerPattern(58, "^(?:note\\s+)"),
        StateJisonLexerPattern(59, "^(?:left of\\b)"),
    )

    private fun lexerChunk3(): List<StateJisonLexerPattern> = listOf(
        StateJisonLexerPattern(60, "^(?:right of\\b)"),
        StateJisonLexerPattern(61, "^(?:\")"),
        StateJisonLexerPattern(62, "^(?:\\s*as\\s*)"),
        StateJisonLexerPattern(63, "^(?:[\"])"),
        StateJisonLexerPattern(64, "^(?:[^\"]*)"),
        StateJisonLexerPattern(65, "^(?:[^\\n]*)"),
        StateJisonLexerPattern(66, "^(?:\\s*[^:\\n\\s\\-]+)"),
        StateJisonLexerPattern(67, "^(?:\\s*:[^:\\n;]+)"),
        StateJisonLexerPattern(68, "^(?:[\\s\\S]*?\\n\\s*end note\\b)"),
        StateJisonLexerPattern(69, "^(?:stateDiagram\\s+)"),
        StateJisonLexerPattern(70, "^(?:stateDiagram-v2\\s+)"),
        StateJisonLexerPattern(71, "^(?:hide empty description\\b)"),
        StateJisonLexerPattern(72, "^(?:\\[\\*\\])"),
        StateJisonLexerPattern(73, "^(?:[^:\\n\\s\\-\\{]+)"),
        StateJisonLexerPattern(74, "^(?:\\s*:(?:[^:\\n;]|:[^:\\n;])+)"),
        StateJisonLexerPattern(75, "^(?:-->)"),
        StateJisonLexerPattern(76, "^(?:--)"),
        StateJisonLexerPattern(77, "^(?::::)"),
        StateJisonLexerPattern(78, "^(?:\$)"),
        StateJisonLexerPattern(79, "^(?:.)"),
    )

    val lexerConditions: Map<String, IntArray> = mapOf(
        "LINE" to intArrayOf(10, 11, 12),
        "struct" to intArrayOf(10, 11, 12, 23, 27, 30, 36, 43, 44, 45, 46, 56, 57, 58, 72, 73, 74, 75, 76, 77),
        "FLOATING_NOTE_ID" to intArrayOf(65),
        "FLOATING_NOTE" to intArrayOf(62, 63, 64),
        "NOTE_TEXT" to intArrayOf(67, 68),
        "NOTE_ID" to intArrayOf(66),
        "NOTE" to intArrayOf(59, 60, 61),
        "STYLEDEF_STYLEOPTS" to intArrayOf(),
        "STYLEDEF_STYLES" to intArrayOf(32),
        "STYLE_IDS" to intArrayOf(),
        "STYLE" to intArrayOf(31),
        "CLASS_STYLE" to intArrayOf(29),
        "CLASS" to intArrayOf(28),
        "CLASSDEFID" to intArrayOf(26),
        "CLASSDEF" to intArrayOf(24, 25),
        "acc_descr_multiline" to intArrayOf(21, 22),
        "acc_descr" to intArrayOf(19),
        "acc_title" to intArrayOf(17),
        "SCALE" to intArrayOf(14, 15, 34, 35),
        "ALIAS" to intArrayOf(),
        "STATE_ID" to intArrayOf(49),
        "STATE_STRING" to intArrayOf(50, 51),
        "FORK_STATE" to intArrayOf(),
        "STATE" to intArrayOf(10, 11, 12, 37, 38, 39, 40, 41, 42, 47, 48, 52, 53, 54, 55),
        "ID" to intArrayOf(10, 11, 12),
        "INITIAL" to intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 16, 18, 20, 23, 27, 30, 33, 36, 55, 58, 69, 70, 71, 72, 73, 74, 75, 77, 78, 79),
    )
}
