package com.swithun.cmpmermaid.core.block.upstream.mermaid

/**
 * Generated from Mermaid 12.0.0 block.jison.
 * Upstream block.jison SHA-256: 323acca843736b66334fa088b97519ef96c22aa5a1a1eed4f468379ebecf09f2
 * Distribution chunk SHA-256: f066a97c89f294242141de2fb3c09fbc9960ae7f60cacf1c67e2b58e39b99a82
 *
 * Do not edit manually. Run:
 *   cd tools/official-reference && npm run generate:block-parser
 */
internal object BlockJisonTables {
    val symbolIds: Map<String, Int> = mapOf(
        "error" to 2,
        "spaceLines" to 3,
        "SPACELINE" to 4,
        "NL" to 5,
        "separator" to 6,
        "SPACE" to 7,
        "EOF" to 8,
        "start" to 9,
        "BLOCK_DIAGRAM_KEY" to 10,
        "document" to 11,
        "stop" to 12,
        "statement" to 13,
        "link" to 14,
        "LINK" to 15,
        "START_LINK" to 16,
        "LINK_LABEL" to 17,
        "STR" to 18,
        "nodeStatement" to 19,
        "columnsStatement" to 20,
        "SPACE_BLOCK" to 21,
        "blockStatement" to 22,
        "classDefStatement" to 23,
        "cssClassStatement" to 24,
        "styleStatement" to 25,
        "node" to 26,
        "SIZE" to 27,
        "COLUMNS" to 28,
        "id-block" to 29,
        "end" to 30,
        "NODE_ID" to 31,
        "nodeShapeNLabel" to 32,
        "dirList" to 33,
        "DIR" to 34,
        "NODE_DSTART" to 35,
        "NODE_DEND" to 36,
        "BLOCK_ARROW_START" to 37,
        "BLOCK_ARROW_END" to 38,
        "classDef" to 39,
        "CLASSDEF_ID" to 40,
        "CLASSDEF_STYLEOPTS" to 41,
        "DEFAULT" to 42,
        "class" to 43,
        "CLASSENTITY_IDS" to 44,
        "STYLECLASS" to 45,
        "style" to 46,
        "STYLE_ENTITY_IDS" to 47,
        "STYLE_DEFINITION_DATA" to 48,
        "\$accept" to 0,
        "\$end" to 1,
    )

    val terminalNames: Map<Int, String> = mapOf(
        2 to "error",
        4 to "SPACELINE",
        5 to "NL",
        7 to "SPACE",
        8 to "EOF",
        10 to "BLOCK_DIAGRAM_KEY",
        15 to "LINK",
        16 to "START_LINK",
        17 to "LINK_LABEL",
        18 to "STR",
        21 to "SPACE_BLOCK",
        27 to "SIZE",
        28 to "COLUMNS",
        29 to "id-block",
        30 to "end",
        31 to "NODE_ID",
        34 to "DIR",
        35 to "NODE_DSTART",
        36 to "NODE_DEND",
        37 to "BLOCK_ARROW_START",
        38 to "BLOCK_ARROW_END",
        39 to "classDef",
        40 to "CLASSDEF_ID",
        41 to "CLASSDEF_STYLEOPTS",
        42 to "DEFAULT",
        43 to "class",
        44 to "CLASSENTITY_IDS",
        45 to "STYLECLASS",
        46 to "style",
        47 to "STYLE_ENTITY_IDS",
        48 to "STYLE_DEFINITION_DATA",
    )

    val productions: Array<BlockJisonProduction> = arrayOf(
        BlockJisonProduction(symbol = 0, length = 0),
        BlockJisonProduction(symbol = 3, length = 1),
        BlockJisonProduction(symbol = 3, length = 2),
        BlockJisonProduction(symbol = 3, length = 2),
        BlockJisonProduction(symbol = 6, length = 1),
        BlockJisonProduction(symbol = 6, length = 1),
        BlockJisonProduction(symbol = 6, length = 1),
        BlockJisonProduction(symbol = 9, length = 3),
        BlockJisonProduction(symbol = 12, length = 1),
        BlockJisonProduction(symbol = 12, length = 1),
        BlockJisonProduction(symbol = 12, length = 2),
        BlockJisonProduction(symbol = 12, length = 2),
        BlockJisonProduction(symbol = 11, length = 1),
        BlockJisonProduction(symbol = 11, length = 2),
        BlockJisonProduction(symbol = 14, length = 1),
        BlockJisonProduction(symbol = 14, length = 4),
        BlockJisonProduction(symbol = 13, length = 1),
        BlockJisonProduction(symbol = 13, length = 1),
        BlockJisonProduction(symbol = 13, length = 1),
        BlockJisonProduction(symbol = 13, length = 1),
        BlockJisonProduction(symbol = 13, length = 1),
        BlockJisonProduction(symbol = 13, length = 1),
        BlockJisonProduction(symbol = 13, length = 1),
        BlockJisonProduction(symbol = 19, length = 3),
        BlockJisonProduction(symbol = 19, length = 2),
        BlockJisonProduction(symbol = 19, length = 1),
        BlockJisonProduction(symbol = 20, length = 1),
        BlockJisonProduction(symbol = 22, length = 4),
        BlockJisonProduction(symbol = 22, length = 3),
        BlockJisonProduction(symbol = 26, length = 1),
        BlockJisonProduction(symbol = 26, length = 2),
        BlockJisonProduction(symbol = 33, length = 1),
        BlockJisonProduction(symbol = 33, length = 2),
        BlockJisonProduction(symbol = 32, length = 3),
        BlockJisonProduction(symbol = 32, length = 4),
        BlockJisonProduction(symbol = 23, length = 3),
        BlockJisonProduction(symbol = 23, length = 3),
        BlockJisonProduction(symbol = 24, length = 3),
        BlockJisonProduction(symbol = 25, length = 3),
    )

    val states: Array<Map<Int, BlockJisonCell>> = buildList {
        addAll(stateChunk0())
        addAll(stateChunk1())
        addAll(stateChunk2())
    }.toTypedArray()

    private fun stateChunk0(): Array<Map<Int, BlockJisonCell>> = arrayOf(
        mapOf(
            9 to BlockJisonCell.Goto(1),
            10 to BlockJisonCell.Shift(2),
        ),
        mapOf(
            1 to BlockJisonCell.Accept,
        ),
        mapOf(
            10 to BlockJisonCell.Shift(15),
            11 to BlockJisonCell.Goto(3),
            13 to BlockJisonCell.Goto(4),
            19 to BlockJisonCell.Goto(5),
            20 to BlockJisonCell.Goto(6),
            21 to BlockJisonCell.Shift(7),
            22 to BlockJisonCell.Goto(8),
            23 to BlockJisonCell.Goto(9),
            24 to BlockJisonCell.Goto(10),
            25 to BlockJisonCell.Goto(11),
            26 to BlockJisonCell.Goto(12),
            28 to BlockJisonCell.Shift(13),
            29 to BlockJisonCell.Shift(14),
            31 to BlockJisonCell.Shift(19),
            39 to BlockJisonCell.Shift(16),
            43 to BlockJisonCell.Shift(17),
            46 to BlockJisonCell.Shift(18),
        ),
        mapOf(
            8 to BlockJisonCell.Shift(20),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(12),
            10 to BlockJisonCell.Shift(15),
            11 to BlockJisonCell.Goto(21),
            13 to BlockJisonCell.Goto(4),
            19 to BlockJisonCell.Goto(5),
            20 to BlockJisonCell.Goto(6),
            21 to BlockJisonCell.Shift(7),
            22 to BlockJisonCell.Goto(8),
            23 to BlockJisonCell.Goto(9),
            24 to BlockJisonCell.Goto(10),
            25 to BlockJisonCell.Goto(11),
            26 to BlockJisonCell.Goto(12),
            28 to BlockJisonCell.Shift(13),
            29 to BlockJisonCell.Shift(14),
            30 to BlockJisonCell.Reduce(12),
            31 to BlockJisonCell.Shift(19),
            39 to BlockJisonCell.Shift(16),
            43 to BlockJisonCell.Shift(17),
            46 to BlockJisonCell.Shift(18),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(16),
            10 to BlockJisonCell.Reduce(16),
            14 to BlockJisonCell.Goto(22),
            15 to BlockJisonCell.Shift(23),
            16 to BlockJisonCell.Shift(24),
            21 to BlockJisonCell.Reduce(16),
            28 to BlockJisonCell.Reduce(16),
            29 to BlockJisonCell.Reduce(16),
            30 to BlockJisonCell.Reduce(16),
            31 to BlockJisonCell.Reduce(16),
            39 to BlockJisonCell.Reduce(16),
            43 to BlockJisonCell.Reduce(16),
            46 to BlockJisonCell.Reduce(16),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(17),
            10 to BlockJisonCell.Reduce(17),
            21 to BlockJisonCell.Reduce(17),
            28 to BlockJisonCell.Reduce(17),
            29 to BlockJisonCell.Reduce(17),
            30 to BlockJisonCell.Reduce(17),
            31 to BlockJisonCell.Reduce(17),
            39 to BlockJisonCell.Reduce(17),
            43 to BlockJisonCell.Reduce(17),
            46 to BlockJisonCell.Reduce(17),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(18),
            10 to BlockJisonCell.Reduce(18),
            21 to BlockJisonCell.Reduce(18),
            28 to BlockJisonCell.Reduce(18),
            29 to BlockJisonCell.Reduce(18),
            30 to BlockJisonCell.Reduce(18),
            31 to BlockJisonCell.Reduce(18),
            39 to BlockJisonCell.Reduce(18),
            43 to BlockJisonCell.Reduce(18),
            46 to BlockJisonCell.Reduce(18),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(19),
            10 to BlockJisonCell.Reduce(19),
            21 to BlockJisonCell.Reduce(19),
            28 to BlockJisonCell.Reduce(19),
            29 to BlockJisonCell.Reduce(19),
            30 to BlockJisonCell.Reduce(19),
            31 to BlockJisonCell.Reduce(19),
            39 to BlockJisonCell.Reduce(19),
            43 to BlockJisonCell.Reduce(19),
            46 to BlockJisonCell.Reduce(19),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(20),
            10 to BlockJisonCell.Reduce(20),
            21 to BlockJisonCell.Reduce(20),
            28 to BlockJisonCell.Reduce(20),
            29 to BlockJisonCell.Reduce(20),
            30 to BlockJisonCell.Reduce(20),
            31 to BlockJisonCell.Reduce(20),
            39 to BlockJisonCell.Reduce(20),
            43 to BlockJisonCell.Reduce(20),
            46 to BlockJisonCell.Reduce(20),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(21),
            10 to BlockJisonCell.Reduce(21),
            21 to BlockJisonCell.Reduce(21),
            28 to BlockJisonCell.Reduce(21),
            29 to BlockJisonCell.Reduce(21),
            30 to BlockJisonCell.Reduce(21),
            31 to BlockJisonCell.Reduce(21),
            39 to BlockJisonCell.Reduce(21),
            43 to BlockJisonCell.Reduce(21),
            46 to BlockJisonCell.Reduce(21),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(22),
            10 to BlockJisonCell.Reduce(22),
            21 to BlockJisonCell.Reduce(22),
            28 to BlockJisonCell.Reduce(22),
            29 to BlockJisonCell.Reduce(22),
            30 to BlockJisonCell.Reduce(22),
            31 to BlockJisonCell.Reduce(22),
            39 to BlockJisonCell.Reduce(22),
            43 to BlockJisonCell.Reduce(22),
            46 to BlockJisonCell.Reduce(22),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(25),
            10 to BlockJisonCell.Reduce(25),
            15 to BlockJisonCell.Reduce(25),
            16 to BlockJisonCell.Reduce(25),
            21 to BlockJisonCell.Reduce(25),
            27 to BlockJisonCell.Shift(25),
            28 to BlockJisonCell.Reduce(25),
            29 to BlockJisonCell.Reduce(25),
            30 to BlockJisonCell.Reduce(25),
            31 to BlockJisonCell.Reduce(25),
            39 to BlockJisonCell.Reduce(25),
            43 to BlockJisonCell.Reduce(25),
            46 to BlockJisonCell.Reduce(25),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(26),
            10 to BlockJisonCell.Reduce(26),
            21 to BlockJisonCell.Reduce(26),
            28 to BlockJisonCell.Reduce(26),
            29 to BlockJisonCell.Reduce(26),
            30 to BlockJisonCell.Reduce(26),
            31 to BlockJisonCell.Reduce(26),
            39 to BlockJisonCell.Reduce(26),
            43 to BlockJisonCell.Reduce(26),
            46 to BlockJisonCell.Reduce(26),
        ),
        mapOf(
            19 to BlockJisonCell.Goto(26),
            26 to BlockJisonCell.Goto(12),
            31 to BlockJisonCell.Shift(19),
        ),
        mapOf(
            10 to BlockJisonCell.Shift(15),
            11 to BlockJisonCell.Goto(27),
            13 to BlockJisonCell.Goto(4),
            19 to BlockJisonCell.Goto(5),
            20 to BlockJisonCell.Goto(6),
            21 to BlockJisonCell.Shift(7),
            22 to BlockJisonCell.Goto(8),
            23 to BlockJisonCell.Goto(9),
            24 to BlockJisonCell.Goto(10),
            25 to BlockJisonCell.Goto(11),
            26 to BlockJisonCell.Goto(12),
            28 to BlockJisonCell.Shift(13),
            29 to BlockJisonCell.Shift(14),
            31 to BlockJisonCell.Shift(19),
            39 to BlockJisonCell.Shift(16),
            43 to BlockJisonCell.Shift(17),
            46 to BlockJisonCell.Shift(18),
        ),
        mapOf(
            40 to BlockJisonCell.Shift(28),
            42 to BlockJisonCell.Shift(29),
        ),
        mapOf(
            44 to BlockJisonCell.Shift(30),
        ),
        mapOf(
            47 to BlockJisonCell.Shift(31),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(29),
            10 to BlockJisonCell.Reduce(29),
            15 to BlockJisonCell.Reduce(29),
            16 to BlockJisonCell.Reduce(29),
            21 to BlockJisonCell.Reduce(29),
            27 to BlockJisonCell.Reduce(29),
            28 to BlockJisonCell.Reduce(29),
            29 to BlockJisonCell.Reduce(29),
            30 to BlockJisonCell.Reduce(29),
            31 to BlockJisonCell.Reduce(29),
            32 to BlockJisonCell.Goto(32),
            35 to BlockJisonCell.Shift(33),
            37 to BlockJisonCell.Shift(34),
            39 to BlockJisonCell.Reduce(29),
            43 to BlockJisonCell.Reduce(29),
            46 to BlockJisonCell.Reduce(29),
        ),
    )

    private fun stateChunk1(): Array<Map<Int, BlockJisonCell>> = arrayOf(
        mapOf(
            1 to BlockJisonCell.Reduce(7),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(13),
            30 to BlockJisonCell.Reduce(13),
        ),
        mapOf(
            26 to BlockJisonCell.Goto(35),
            31 to BlockJisonCell.Shift(19),
        ),
        mapOf(
            31 to BlockJisonCell.Reduce(14),
        ),
        mapOf(
            17 to BlockJisonCell.Shift(36),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(24),
            10 to BlockJisonCell.Reduce(24),
            15 to BlockJisonCell.Reduce(24),
            16 to BlockJisonCell.Reduce(24),
            21 to BlockJisonCell.Reduce(24),
            28 to BlockJisonCell.Reduce(24),
            29 to BlockJisonCell.Reduce(24),
            30 to BlockJisonCell.Reduce(24),
            31 to BlockJisonCell.Reduce(24),
            39 to BlockJisonCell.Reduce(24),
            43 to BlockJisonCell.Reduce(24),
            46 to BlockJisonCell.Reduce(24),
        ),
        mapOf(
            10 to BlockJisonCell.Shift(15),
            11 to BlockJisonCell.Goto(37),
            13 to BlockJisonCell.Goto(4),
            14 to BlockJisonCell.Goto(22),
            15 to BlockJisonCell.Shift(23),
            16 to BlockJisonCell.Shift(24),
            19 to BlockJisonCell.Goto(5),
            20 to BlockJisonCell.Goto(6),
            21 to BlockJisonCell.Shift(7),
            22 to BlockJisonCell.Goto(8),
            23 to BlockJisonCell.Goto(9),
            24 to BlockJisonCell.Goto(10),
            25 to BlockJisonCell.Goto(11),
            26 to BlockJisonCell.Goto(12),
            28 to BlockJisonCell.Shift(13),
            29 to BlockJisonCell.Shift(14),
            31 to BlockJisonCell.Shift(19),
            39 to BlockJisonCell.Shift(16),
            43 to BlockJisonCell.Shift(17),
            46 to BlockJisonCell.Shift(18),
        ),
        mapOf(
            30 to BlockJisonCell.Shift(38),
        ),
        mapOf(
            41 to BlockJisonCell.Shift(39),
        ),
        mapOf(
            41 to BlockJisonCell.Shift(40),
        ),
        mapOf(
            45 to BlockJisonCell.Shift(41),
        ),
        mapOf(
            48 to BlockJisonCell.Shift(42),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(30),
            10 to BlockJisonCell.Reduce(30),
            15 to BlockJisonCell.Reduce(30),
            16 to BlockJisonCell.Reduce(30),
            21 to BlockJisonCell.Reduce(30),
            27 to BlockJisonCell.Reduce(30),
            28 to BlockJisonCell.Reduce(30),
            29 to BlockJisonCell.Reduce(30),
            30 to BlockJisonCell.Reduce(30),
            31 to BlockJisonCell.Reduce(30),
            39 to BlockJisonCell.Reduce(30),
            43 to BlockJisonCell.Reduce(30),
            46 to BlockJisonCell.Reduce(30),
        ),
        mapOf(
            18 to BlockJisonCell.Shift(43),
        ),
        mapOf(
            18 to BlockJisonCell.Shift(44),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(23),
            10 to BlockJisonCell.Reduce(23),
            15 to BlockJisonCell.Reduce(23),
            16 to BlockJisonCell.Reduce(23),
            21 to BlockJisonCell.Reduce(23),
            28 to BlockJisonCell.Reduce(23),
            29 to BlockJisonCell.Reduce(23),
            30 to BlockJisonCell.Reduce(23),
            31 to BlockJisonCell.Reduce(23),
            39 to BlockJisonCell.Reduce(23),
            43 to BlockJisonCell.Reduce(23),
            46 to BlockJisonCell.Reduce(23),
        ),
        mapOf(
            18 to BlockJisonCell.Shift(45),
        ),
        mapOf(
            30 to BlockJisonCell.Shift(46),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(28),
            10 to BlockJisonCell.Reduce(28),
            21 to BlockJisonCell.Reduce(28),
            28 to BlockJisonCell.Reduce(28),
            29 to BlockJisonCell.Reduce(28),
            30 to BlockJisonCell.Reduce(28),
            31 to BlockJisonCell.Reduce(28),
            39 to BlockJisonCell.Reduce(28),
            43 to BlockJisonCell.Reduce(28),
            46 to BlockJisonCell.Reduce(28),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(35),
            10 to BlockJisonCell.Reduce(35),
            21 to BlockJisonCell.Reduce(35),
            28 to BlockJisonCell.Reduce(35),
            29 to BlockJisonCell.Reduce(35),
            30 to BlockJisonCell.Reduce(35),
            31 to BlockJisonCell.Reduce(35),
            39 to BlockJisonCell.Reduce(35),
            43 to BlockJisonCell.Reduce(35),
            46 to BlockJisonCell.Reduce(35),
        ),
    )

    private fun stateChunk2(): Array<Map<Int, BlockJisonCell>> = arrayOf(
        mapOf(
            8 to BlockJisonCell.Reduce(36),
            10 to BlockJisonCell.Reduce(36),
            21 to BlockJisonCell.Reduce(36),
            28 to BlockJisonCell.Reduce(36),
            29 to BlockJisonCell.Reduce(36),
            30 to BlockJisonCell.Reduce(36),
            31 to BlockJisonCell.Reduce(36),
            39 to BlockJisonCell.Reduce(36),
            43 to BlockJisonCell.Reduce(36),
            46 to BlockJisonCell.Reduce(36),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(37),
            10 to BlockJisonCell.Reduce(37),
            21 to BlockJisonCell.Reduce(37),
            28 to BlockJisonCell.Reduce(37),
            29 to BlockJisonCell.Reduce(37),
            30 to BlockJisonCell.Reduce(37),
            31 to BlockJisonCell.Reduce(37),
            39 to BlockJisonCell.Reduce(37),
            43 to BlockJisonCell.Reduce(37),
            46 to BlockJisonCell.Reduce(37),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(38),
            10 to BlockJisonCell.Reduce(38),
            21 to BlockJisonCell.Reduce(38),
            28 to BlockJisonCell.Reduce(38),
            29 to BlockJisonCell.Reduce(38),
            30 to BlockJisonCell.Reduce(38),
            31 to BlockJisonCell.Reduce(38),
            39 to BlockJisonCell.Reduce(38),
            43 to BlockJisonCell.Reduce(38),
            46 to BlockJisonCell.Reduce(38),
        ),
        mapOf(
            36 to BlockJisonCell.Shift(47),
        ),
        mapOf(
            33 to BlockJisonCell.Goto(48),
            34 to BlockJisonCell.Shift(49),
        ),
        mapOf(
            15 to BlockJisonCell.Shift(50),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(27),
            10 to BlockJisonCell.Reduce(27),
            21 to BlockJisonCell.Reduce(27),
            28 to BlockJisonCell.Reduce(27),
            29 to BlockJisonCell.Reduce(27),
            30 to BlockJisonCell.Reduce(27),
            31 to BlockJisonCell.Reduce(27),
            39 to BlockJisonCell.Reduce(27),
            43 to BlockJisonCell.Reduce(27),
            46 to BlockJisonCell.Reduce(27),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(33),
            10 to BlockJisonCell.Reduce(33),
            15 to BlockJisonCell.Reduce(33),
            16 to BlockJisonCell.Reduce(33),
            21 to BlockJisonCell.Reduce(33),
            27 to BlockJisonCell.Reduce(33),
            28 to BlockJisonCell.Reduce(33),
            29 to BlockJisonCell.Reduce(33),
            30 to BlockJisonCell.Reduce(33),
            31 to BlockJisonCell.Reduce(33),
            39 to BlockJisonCell.Reduce(33),
            43 to BlockJisonCell.Reduce(33),
            46 to BlockJisonCell.Reduce(33),
        ),
        mapOf(
            38 to BlockJisonCell.Shift(51),
        ),
        mapOf(
            33 to BlockJisonCell.Goto(52),
            34 to BlockJisonCell.Shift(49),
            38 to BlockJisonCell.Reduce(31),
        ),
        mapOf(
            31 to BlockJisonCell.Reduce(15),
        ),
        mapOf(
            8 to BlockJisonCell.Reduce(34),
            10 to BlockJisonCell.Reduce(34),
            15 to BlockJisonCell.Reduce(34),
            16 to BlockJisonCell.Reduce(34),
            21 to BlockJisonCell.Reduce(34),
            27 to BlockJisonCell.Reduce(34),
            28 to BlockJisonCell.Reduce(34),
            29 to BlockJisonCell.Reduce(34),
            30 to BlockJisonCell.Reduce(34),
            31 to BlockJisonCell.Reduce(34),
            39 to BlockJisonCell.Reduce(34),
            43 to BlockJisonCell.Reduce(34),
            46 to BlockJisonCell.Reduce(34),
        ),
        mapOf(
            38 to BlockJisonCell.Reduce(32),
        ),
    )

    val defaultActions: Map<Int, BlockJisonCell> = mapOf(
        20 to BlockJisonCell.Reduce(7),
        23 to BlockJisonCell.Reduce(14),
        50 to BlockJisonCell.Reduce(15),
        52 to BlockJisonCell.Reduce(32),
    )

    val lexerPatterns: List<BlockJisonLexerPattern> = buildList {
        addAll(lexerChunk0())
        addAll(lexerChunk1())
        addAll(lexerChunk2())
        addAll(lexerChunk3())
        addAll(lexerChunk4())
        addAll(lexerChunk5())
    }

    private fun lexerChunk0(): List<BlockJisonLexerPattern> = listOf(
        BlockJisonLexerPattern(0, "^(?:block-beta\\b)"),
        BlockJisonLexerPattern(1, "^(?:block:)"),
        BlockJisonLexerPattern(2, "^(?:block\\b)"),
        BlockJisonLexerPattern(3, "^(?:[\\s]+)"),
        BlockJisonLexerPattern(4, "^(?:[\\n]+)"),
        BlockJisonLexerPattern(5, "^(?:((\\u000D\\u000A)|(\\u000A)))"),
        BlockJisonLexerPattern(6, "^(?:columns\\s+auto\\b)"),
        BlockJisonLexerPattern(7, "^(?:columns\\s+[\\d]+)"),
        BlockJisonLexerPattern(8, "^(?:[\"][`])"),
        BlockJisonLexerPattern(9, "^(?:[^`\"]+)"),
        BlockJisonLexerPattern(10, "^(?:[`][\"])"),
        BlockJisonLexerPattern(11, "^(?:[\"])"),
        BlockJisonLexerPattern(12, "^(?:[\"])"),
        BlockJisonLexerPattern(13, "^(?:[^\"]*)"),
        BlockJisonLexerPattern(14, "^(?:space[:]\\d+)"),
        BlockJisonLexerPattern(15, "^(?:space\\b)"),
        BlockJisonLexerPattern(16, "^(?:default\\b)"),
        BlockJisonLexerPattern(17, "^(?:linkStyle\\b)"),
        BlockJisonLexerPattern(18, "^(?:interpolate\\b)"),
        BlockJisonLexerPattern(19, "^(?:classDef\\s+)"),
    )

    private fun lexerChunk1(): List<BlockJisonLexerPattern> = listOf(
        BlockJisonLexerPattern(20, "^(?:DEFAULT\\s+)"),
        BlockJisonLexerPattern(21, "^(?:\\w+\\s+)"),
        BlockJisonLexerPattern(22, "^(?:[^\\n]*)"),
        BlockJisonLexerPattern(23, "^(?:class\\s+)"),
        BlockJisonLexerPattern(24, "^(?:(\\w+)+((,\\s*\\w+)*))"),
        BlockJisonLexerPattern(25, "^(?:[^\\n]*)"),
        BlockJisonLexerPattern(26, "^(?:style\\s+)"),
        BlockJisonLexerPattern(27, "^(?:(\\w+)+((,\\s*\\w+)*))"),
        BlockJisonLexerPattern(28, "^(?:[^\\n]*)"),
        BlockJisonLexerPattern(29, "^(?:accTitle\\s*:\\s*)"),
        BlockJisonLexerPattern(30, "^(?:(?!\\n||)*[^\\n]*)"),
        BlockJisonLexerPattern(31, "^(?:accDescr\\s*:\\s*)"),
        BlockJisonLexerPattern(32, "^(?:(?!\\n||)*[^\\n]*)"),
        BlockJisonLexerPattern(33, "^(?:accDescr\\s*\\{\\s*)"),
        BlockJisonLexerPattern(34, "^(?:[\\}])"),
        BlockJisonLexerPattern(35, "^(?:[^\\}]*)"),
        BlockJisonLexerPattern(36, "^(?:end\\b\\s*)"),
        BlockJisonLexerPattern(37, "^(?:\\(\\(\\()"),
        BlockJisonLexerPattern(38, "^(?:\\)\\)\\))"),
        BlockJisonLexerPattern(39, "^(?:[\\)]\\))"),
    )

    private fun lexerChunk2(): List<BlockJisonLexerPattern> = listOf(
        BlockJisonLexerPattern(40, "^(?:\\}\\})"),
        BlockJisonLexerPattern(41, "^(?:\\})"),
        BlockJisonLexerPattern(42, "^(?:\\(-)"),
        BlockJisonLexerPattern(43, "^(?:-\\))"),
        BlockJisonLexerPattern(44, "^(?:\\(\\()"),
        BlockJisonLexerPattern(45, "^(?:\\]\\])"),
        BlockJisonLexerPattern(46, "^(?:\\()"),
        BlockJisonLexerPattern(47, "^(?:\\]\\))"),
        BlockJisonLexerPattern(48, "^(?:\\\\\\])"),
        BlockJisonLexerPattern(49, "^(?:\\/\\])"),
        BlockJisonLexerPattern(50, "^(?:\\)\\])"),
        BlockJisonLexerPattern(51, "^(?:[\\)])"),
        BlockJisonLexerPattern(52, "^(?:\\]>)"),
        BlockJisonLexerPattern(53, "^(?:[\\]])"),
        BlockJisonLexerPattern(54, "^(?:-\\))"),
        BlockJisonLexerPattern(55, "^(?:\\(-)"),
        BlockJisonLexerPattern(56, "^(?:\\)\\))"),
        BlockJisonLexerPattern(57, "^(?:\\))"),
        BlockJisonLexerPattern(58, "^(?:\\(\\(\\()"),
        BlockJisonLexerPattern(59, "^(?:\\(\\()"),
    )

    private fun lexerChunk3(): List<BlockJisonLexerPattern> = listOf(
        BlockJisonLexerPattern(60, "^(?:\\{\\{)"),
        BlockJisonLexerPattern(61, "^(?:\\{)"),
        BlockJisonLexerPattern(62, "^(?:>)"),
        BlockJisonLexerPattern(63, "^(?:\\(\\[)"),
        BlockJisonLexerPattern(64, "^(?:\\()"),
        BlockJisonLexerPattern(65, "^(?:\\[\\[)"),
        BlockJisonLexerPattern(66, "^(?:\\[\\|)"),
        BlockJisonLexerPattern(67, "^(?:\\[\\()"),
        BlockJisonLexerPattern(68, "^(?:\\)\\)\\))"),
        BlockJisonLexerPattern(69, "^(?:\\[\\\\)"),
        BlockJisonLexerPattern(70, "^(?:\\[\\/)"),
        BlockJisonLexerPattern(71, "^(?:\\[\\\\)"),
        BlockJisonLexerPattern(72, "^(?:\\[)"),
        BlockJisonLexerPattern(73, "^(?:<\\[)"),
        BlockJisonLexerPattern(74, "^(?:[^\\(\\[\\n\\-\\)\\{\\}\\s\\<\\>:=]+)"),
        BlockJisonLexerPattern(75, "^(?:\$)"),
        BlockJisonLexerPattern(76, "^(?:[\"][`])"),
        BlockJisonLexerPattern(77, "^(?:[\"][`])"),
        BlockJisonLexerPattern(78, "^(?:[^`\"]+)"),
        BlockJisonLexerPattern(79, "^(?:[`][\"])"),
    )

    private fun lexerChunk4(): List<BlockJisonLexerPattern> = listOf(
        BlockJisonLexerPattern(80, "^(?:[\"])"),
        BlockJisonLexerPattern(81, "^(?:[\"])"),
        BlockJisonLexerPattern(82, "^(?:[^\"]+)"),
        BlockJisonLexerPattern(83, "^(?:[\"])"),
        BlockJisonLexerPattern(84, "^(?:\\]>\\s*\\()"),
        BlockJisonLexerPattern(85, "^(?:,?\\s*right\\s*)"),
        BlockJisonLexerPattern(86, "^(?:,?\\s*left\\s*)"),
        BlockJisonLexerPattern(87, "^(?:,?\\s*x\\s*)"),
        BlockJisonLexerPattern(88, "^(?:,?\\s*y\\s*)"),
        BlockJisonLexerPattern(89, "^(?:,?\\s*up\\s*)"),
        BlockJisonLexerPattern(90, "^(?:,?\\s*down\\s*)"),
        BlockJisonLexerPattern(91, "^(?:\\)\\s*)"),
        BlockJisonLexerPattern(92, "^(?:\\s*[xo<]?--+[-xo>]\\s*)"),
        BlockJisonLexerPattern(93, "^(?:\\s*[xo<]?==+[=xo>]\\s*)"),
        BlockJisonLexerPattern(94, "^(?:\\s*[xo<]?-?\\.+-[xo>]?\\s*)"),
        BlockJisonLexerPattern(95, "^(?:\\s*~~[\\~]+\\s*)"),
        BlockJisonLexerPattern(96, "^(?:\\s*[xo<]?--\\s*)"),
        BlockJisonLexerPattern(97, "^(?:\\s*[xo<]?==\\s*)"),
        BlockJisonLexerPattern(98, "^(?:\\s*[xo<]?-\\.\\s*)"),
        BlockJisonLexerPattern(99, "^(?:[\"][`])"),
    )

    private fun lexerChunk5(): List<BlockJisonLexerPattern> = listOf(
        BlockJisonLexerPattern(100, "^(?:[\"])"),
        BlockJisonLexerPattern(101, "^(?:\\s*[xo<]?--+[-xo>]\\s*)"),
        BlockJisonLexerPattern(102, "^(?:\\s*[xo<]?==+[=xo>]\\s*)"),
        BlockJisonLexerPattern(103, "^(?:\\s*[xo<]?-?\\.+-[xo>]?\\s*)"),
        BlockJisonLexerPattern(104, "^(?::\\d+)"),
    )

    val lexerConditions: Map<String, IntArray> = mapOf(
        "STYLE_DEFINITION" to intArrayOf(28),
        "STYLE_STMNT" to intArrayOf(27),
        "CLASSDEFID" to intArrayOf(22),
        "CLASSDEF" to intArrayOf(20, 21),
        "CLASS_STYLE" to intArrayOf(25),
        "CLASS" to intArrayOf(24),
        "LLABEL" to intArrayOf(99, 100, 101, 102, 103),
        "ARROW_DIR" to intArrayOf(85, 86, 87, 88, 89, 90, 91),
        "BLOCK_ARROW" to intArrayOf(76, 81, 84),
        "NODE" to intArrayOf(37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 77, 80),
        "md_string" to intArrayOf(9, 10, 78, 79),
        "space" to intArrayOf(),
        "string" to intArrayOf(12, 13, 82, 83),
        "acc_descr_multiline" to intArrayOf(34, 35),
        "acc_descr" to intArrayOf(32),
        "acc_title" to intArrayOf(30),
        "INITIAL" to intArrayOf(0, 1, 2, 3, 4, 5, 6, 7, 8, 11, 14, 15, 16, 17, 18, 19, 23, 26, 29, 31, 33, 36, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 92, 93, 94, 95, 96, 97, 98, 104),
    )
}
